zalando/skipper

proxy/proxy.go
proxy/tracing.go
proxy/tracing_test.go

`skipper.route` tag contains serialized route in eskip format.
The value could be quite large, especially when route has loadbalanced
backend with many endpoints.
For payload size efficiency reasons this tag was already excluded at Zalando,
see https://github.com/zalando-incubator/kubernetes-on-aws/pull/2173
During profiling it was also dicovered that route eskip serialization
performance is suboptimal and may take more than 7% of the total
`proxy.ServeHTTP` call runtime.
While it is possible to optimize route eskip serialization (see e.g.
https://github.com/zalando/skipper/pull/1906) this change simply drops
it from the request path.
Users may still rely on `skipper.route_id` tag to resolve route configuration and
`http.url` tag to get actual backend address.
Signed-off-by: Alexander …

Removes `skipper.route` tag from proxy span

---

eskip/string.go
eskip/string_test.go

```
benchmark                      old ns/op     new ns/op     delta
BenchmarkLBBackendString-8     9714          1951          -79.92%
BenchmarkLBBackendString-8     8967          1960          -78.14%
BenchmarkLBBackendString-8     8975          1955          -78.22%
BenchmarkLBBackendString-8     9176          1944          -78.81%
BenchmarkLBBackendString-8     8938          1947          -78.22%
BenchmarkLBBackendString-8     8733          1953          -77.64%
BenchmarkLBBackendString-8     8690          1960          -77.45%
BenchmarkLBBackendString-8     8519          1960          -76.99%
BenchmarkLBBackendString-8     9161          1952          -78.69%
BenchmarkLBBackendString-8     9048          1814          -79.95%
benchmark                      old allocs     new allocs …
```

Optimizes loadbalanced backend string

---

routing/datasource.go
routing/datasource_test.go
routing/export_test.go

```
$ bin/skipper -inline-routes='r1: QueryParam() -> <shunt>; r2: Unknown() -> <shunt>; r3: Path("/r3") -> unknown() -> <shunt>; r4: Path("/r4") -> setPath() -> <shunt>;'
...
[APP]ERRO[0000] failed to process route r1: failed to create predicate "QueryParam": invalid predicate parameters
[APP]ERRO[0000] failed to process route r2: predicate "Unknown" not found
[APP]ERRO[0000] failed to process route r3: filter "unknown" not found
[APP]ERRO[0000] failed to process route r4: failed to create filter "setPath": invalid filter parameters
```

Adds predicate and filter name to error

---

config/config.go
net/host.go
net/host_test.go

Incoming request `Host` header may contain port number, a trailing dot or
have an uppercase value which are all valid according to various RFCs but are not common.
AWS Application Load Balancer (ALB) removes port number, trailing dot and
converts `Host` header to lower case so uncommon cases are never observed
by Skipper behind ALB.
AWS Network Load Balancer (NLB) passes `Host` header as is.
Several changes were introduced to account for uncommon port number and traling dot:
* `Host` predicate generated by kubernetes dataclient was changed to
match optional port and trailing dot by #1281 and #1863
* `rfcHost` filter was introduced to remove trailing dot #1864
Matching optional port and trailing dot makes `Host` regexp more complex and
adds a small performance penalty for the uncommon …

Adds incoming request host normalization

---

docs/reference/predicates.md
predicates/host/any.go
predicates/host/any_test.go
predicates/predicates.go
routing/datasource_test.go
routing/export_test.go
routing/host_test.go
skipper.go

`HostAny` predicate evaluates to true if request host exactly matches any of the configured values.
Benchmark demonstrates performance of mathching single host across 10k routes:
```
$ go test ./routing/ -run NONE -bench BenchmarkPredicateHost -benchmem -benchtime=10s
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/routing
BenchmarkPredicateHostRegexpSingleWithDotAndPort-8          4429           2749788 ns/op              48 B/op          1 allocs/op
BenchmarkPredicateHostRegexpMultipleWithDotAndPort-8        4633           2619966 ns/op              48 B/op          1 allocs/op
BenchmarkPredicateHostRegexpSingleDomainOnly-8              8666           1342919 ns/op              48 B/op          1 allocs/op …
```

Adds `HostAny` predicate

---

dataclients/kubernetes/kube.go
dataclients/kubernetes/kube_test.go
dataclients/kubernetes/update_test.go

dataclients/kubernetes: use healthcheck based on Shutdown predicate

---

config/config.go
routesrv/options.go
routesrv/routesrv.go
routesrv/routesrv_test.go
routesrv/testdata/ing-v1-lb-target-multi.eskip
routesrv/testdata/ing-v1-lb-target-multi.yaml
skipper.go

fix: #1916 routesrv should be able to fetch ingress v1 resources

fix: routesrv should be able to fetch ingress v1 resources

---

proxy/proxy.go
proxy/tracing_test.go

The tags are always empty because backed request has empty `RemoteAddr`

proxy: omit empty http.remote_addr and http.remote_ip proxy span tags

---

proxy/proxy.go
proxy/tracing.go
proxy/tracing_test.go

Removes `http.remote_addr` tag that contains request remote IP and port value.
There is still `http.remote_ip` tag that contains remote IP address without port.

proxy: remove http.remote_addr tracing tag

---

filters/auth/auth.go
filters/auth/jwt_validation.go
go.mod
go.sum

The purpose of this PR is to upgrade the `github.com/MicahParks/keyfunc` dependency from a pre-release to the newly release `v1.0.0`.
Running the tests in the `filters/auth` directory passes. I have _not_ run a project wide `go test -race -cover ./...` as I don't have all the required assets, like etcd. I assume they would pass as the change should be small, but it'd be best to run the full test suite.
Thank you to the maintainers from this project that have contributed to `github.com/MicahParks/keyfunc`!

Upgrade keyfunc to latest stable version

---

filters/auth/oidc_test.go
net/dnstest/dnstest.go
net/dnstest/dnstest_test.go

Adds utility to configure loopback names in tests and uses it to validate OIDC cookie domain.
Fixes #1926

Adds OIDC cookie domain tests

---

SECURITY.md

fix https://github.com/zalando/skipper/issues/1929 , add report via e-mail to maintainers in case there are issues with the reporting to security org

change SECURITY to e-mail to maintainers

---

docs/reference/filters.md
filters/auth/auth_test.go
filters/auth/webhook.go
filters/auth/webhook_test.go

Handle status code 403 from auth service in the `webhook` filter, propagating the 403 status code to the caller.
Fixes #1838

Propagate 403 status code from auth service in webhook filter

---

filters/auth/oidc.go
filters/auth/oidc_test.go

* Uses eskip to define filters in `TestOIDCSetup`
* Moves filter creation tests from `TestOIDCSetup` to `TestCreateFilterOIDC`

filters/auth: refactor OIDC tests

---

eskip/roundtrip_test.go
eskip/string.go
eskip/string_test.go

The #1341 removed backslash escaping which leads to incorrect
serialization of strings with a backslash.

Fixes eskip backslash escaping

---

proxy/proxy.go
proxy/proxy_test.go

remove logging in makeBackendRequest to log it once in one place instead, such that we have no double logging anymore

remove logging in makeBackendRequest

---

delivery.yaml

CDP is pushing a new concept called `runtime`s for setting up the build environment. It's similar to `overlay`s but is implemented slightly different (as a docker container as opposed to a tar extracting the content on the VM filesystem).
The runtime and overlay for go are pretty much identical in terms of tools installed etc. so try it out with a real project like skipper :)

Switch to CDP runtime instead of overlay

---

docs/kubernetes/ingress-controller.md

As a comment in https://github.com/zalando/skipper/issues/1028 shows, this part of the docs needs an improvement.

doc: --kubernetes-ingress-class=<regexp> instead of plain string compare

---

dataclients/kubernetes/clusterclient.go
dataclients/kubernetes/ingress.go
dataclients/kubernetes/routegroup.go

optimize struct packing in kubernetes dataclient
Basically I ran `structslop -apply -v`, but had to reset files which are only loaded once and have a lot of godoc, which seem better to be grouped by name as by type.

optimize struct packing in kubernetes dataclient

---

docs/reference/filters.md
scheduler/scheduler.go
scheduler/scheduler_test.go
skipper.go

Multiple `lifo` filter instances on the route share the same job queue but claim multiple slots per request.
This is not obvious when users configure `lifo` filter in the ingress manifest and another instance is added
by the `-default-filters-prepend` flag.
The change keeps only the last `lifo` filter instance on the route to enable default configuration override.

scheduler: ensure single lifo instance per route

---

scheduler/export_test.go
scheduler/scheduler.go
scheduler/scheduler_test.go

Closing of a lifo queue on route deletion while in-flight requests try
to get a slot from it results in `Unknown error for route based LIFO: queue closed for host`
error and 500 response to the client.
To mitigate the problem this change puts deleted queues aside and closes them after one minute.
The proper fix would be to close queue when all route's in-flight requests complete, see #202.
Updates #1851

scheduler: delays closing of deleted lifo queues

---

filters/scheduler/lifo_test.go
scheduler/scheduler.go

The tests was introduced by #1944
It may happen that not all spans are finished by the time test verifies response results (because spans are closed after response has been served).
This change waits for all mock spans to finish and forces scheduler metrics update.

filters/scheduler: wait for spans finishing in lifo errors test

---

filters/auth/oidc.go
filters/auth/oidc_test.go

fix https://github.com/zalando/skipper/issues/1968

fix: oidc*Claims filter paniced if no claims were used as input argument

---

.gitignore
docs/tutorials/development.md

It can be helpful to run Skipper in a debug session locally that enables one to inspect variables and do other debugging activities in order to analyze filter and token states.
adding docs how a VSCode launch configuration for a full OIDC roundtrip could look like

debugging in VSCode

---

docs/reference/development.md
docs/tutorials/development.md
filters/auth/oidc.go
filters/auth/oidc_introspection_test.go
filters/auth/tokeninfo.go
filters/auth/tokeninfo_test.go
filters/auth/tokenintrospection.go
filters/auth/tokenintrospection_test.go
filters/auth/webhook.go
filters/auth/webhook_test.go

* removes auth filters `Close` methods: they are never called due to #202 and
it makes no sense to close shared auth clients anyway
* removes mention of `Close` from the developement docs
Updates #202

filters/auth: do not close shared auth clients

---

delivery.yaml

Pins go version until tooling (e.g. `staticcheck` https://twitter.com/dominikhonnef/status/1503793590991994882) is ready to support 1.18

Pins go version to 1.17

---

skipper.go

Uses debug level for `http: URL query contains semicolon`

---

cmd/eskip/doc.go

cmd/eskip: fixes go1.18 vet error

---

metrics/metrics_test.go

```
$ go test -count=10 github.com/zalando/skipper/metrics -run NONE -bench BenchmarkMeasureSince -benchmem
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/metrics
BenchmarkMeasureSincePrometheus-8        7068398               165.5 ns/op            16 B/op          1 allocs/op
BenchmarkMeasureSincePrometheus-8        7408232               164.5 ns/op            16 B/op          1 allocs/op
BenchmarkMeasureSincePrometheus-8        7264077               161.6 ns/op            16 B/op          1 allocs/op
BenchmarkMeasureSincePrometheus-8        6803798               161.9 ns/op            16 B/op          1 allocs/op
BenchmarkMeasureSincePrometheus-8        7437289               161.7 ns/op            16 B/op          1 allocs/op …
```

metrics: add MeasureSince benchmark

---

.github/workflows/master.yaml
.github/workflows/pr.yaml
Makefile
delivery.yaml
innkeeper/client.go
loadbalancer/healthchecker.go
proxy/proxy.go
queuelistener/listener.go

`staticcheck` has been updated to work with Go 1.18 so attempt to update the version used for building.

Build with Go 1.18

---

filters/auth/oidc.go
filters/auth/oidc_test.go

If OIDC cookies are invalid, the client is redirected but the cookies are not cleared.
In case that the new cookie will produce smaller set of chunks, an invalid chunk is not overwritten and kept in the browser and Skipper will try to attach this junk to the new set.
This changes the behaviour in that regard that it clears relevant cookies in case of a new auth session.

clear invalid cookies

---

dataclients/kubernetes/kube.go
docs/kubernetes/deploy/daemonset/rbac.yaml
docs/kubernetes/deploy/deployment/rbac.yaml
docs/kubernetes/east-west-usage.md
docs/kubernetes/ingress-controller.md
docs/kubernetes/ingress-usage.md
docs/kubernetes/routegroups.md
docs/tutorials/operations.md

deprecate ingress v1beta1 and change all the docs, examples and deployment files
relates to https://github.com/zalando/skipper/pull/1999

deprecate ingress v1beta1 

---

config/config.go
config/config_test.go
filters/auth/oidc.go
filters/auth/oidc_introspection_test.go
filters/auth/oidc_test.go
skipper.go

fixes: #1955
This solution is scoped to Azure behaviour, taking into account the specs from
https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims
There are some Azure related API calls included but trying to support other providers, which is though unknown at this time.
it transforms a distributed claim
```json
{
"_claim_names": {
"groups": "src1"
},
"_claim_sources": {
"src1": {
"endpoint": "https://graph.windows.net/.../getMemberObjects"
}
}
}
```
into a full populated token, which is saved in `statebag` and in the `cookie` for follow up processing
```json
{
"_claim_names": {
"groups": "src1"
},
"_claim_sources": {
"src1": {
"endpoint": "https://graph.windows.net/.../getMemberObjects"
}
},
"groups": [
"group1",
"group2",
...
]
}
```

resolve Aggregated and Distributed Claims

---

docs/reference/architecture.md
docs/reference/predicates.md
docs/tutorials/basics.md

docs: predicate should have fragment by name to reference easily

---

docs/reference/filters.md
filters/filters.go
filters/ratelimit/leakybucket.go
filters/ratelimit/leakybucket_test.go
net/redisclient.go
ratelimit/leakybucket.go
ratelimit/leakybucket.lua
ratelimit/leakybucket_test.go
skipper.go

The `clusterLeakyBucketRatelimit` filter implements ratelimiting _meter_ variant of [Leaky Bucket algorithm](https://en.wikipedia.org/wiki/Leaky_bucket)
and uses Redis as a storage. Leaky Bucket algorithm is also known as [Generic cell rate algorithm](https://en.wikipedia.org/wiki/Generic_cell_rate_algorithm).
Prior art
---
* https://github.com/throttled/throttled - implements CGRA algorithm,
uses optimistic locking i.e. two queries (get and set) to the storage per request
* https://github.com/brandur/redis-cell - implements GCRA as a Redis module
* https://github.com/rwz/redis-gcra - implements GCRA as Redis lua
script, uses Redis time, microsecond-only precision, floating point, divisions and rounding.
* https://github.com/go-redis/redis_rate - for go-redis v7 currently used by skipper …

Implements cluster leaky bucket rate limit filter

---

readme.md

Former link returns an error page.

Fixes link to ratelimiter docs

---

config/breakerflags.go
config/mapflags.go
config/ratelimiterflags.go
dataclients/kubernetes/defaultfilters.go
etcd/etcd_test.go
filters/apiusagemonitoring/pathinfo.go
filters/auth/oidc.go
filters/auth/oidc_introspection.go
filters/auth/oidc_test.go
filters/builtin/compress.go
go.mod
go.sum
net/net.go
predicates/forwarded/forwarded.go
proxy/breaker_test.go
script/script.go
tracing/tracers/basic/basic.go
tracing/tracers/instana/instana.go
tracing/tracers/jaeger/jaeger.go
tracing/tracers/lightstep/lightstep.go

This PR uses Go 1.18 `strings.Cut` function and replaces usage of `strings.Split` and `strings.SplitN` where possible.
Resolves https://github.com/zalando/skipper/issues/1963

refactor: use strings.Cut for strings parsing

---

Makefile
delivery.yaml
docs/tutorials/basics.md
packaging/Dockerfile
packaging/Dockerfile.arm64
packaging/Dockerfile.armv7
packaging/Makefile

This adds build steps to build a new multi-arch container image for `skipper` (and tools) for `linux/amd64` and `linux/arm64`.
The heart of this change is the additional Makefile step called `docker.push.multiarch` which builds a multi-arch image using `buildx` by providing multiple platform arguments.
In order to do that I needed to change several parts of the Makefile but tried to keep everything backwards compatible. I would prefer to make the multi-arch build the single container image artifact and remove the separate Dockerfiles for `.arm` and `.arm64`. However, currently we don't have a public registry that supports multi-arch images where we publish skipper to, so I leave them in place for now.
The new multi-arch image is pushed to our private registry for now and since its base …

Add instructions to build multi-arch container image

---

packaging/Makefile

When using `buildx` the images stay in the remote build cache. So you either have to use `--push` to push them directly or use `--load` to import them to the local daemon and `docker push` from there.
Curiously, this worked fine for the `amd64` version but failed for the arm ones. I think the amd64 build is run by the local daemon (since it's the native platform) whereas the arm ones are used by the separate buildkit builder, hence it failed there. 
Let's do it correctly by loading the image to the local daemon first. Note, `--load` only works with single-arch images, which is the case here.

Make sure to import the built image to the local daemon

---

packaging/Makefile

This must be installed if we want to build the armv7 image.

Install arm (32-bit) emulator to build armv7 image

---

config/config.go
config/config_test.go
net/query.go
net/query_test.go

fix: Query predicate could be bypassed by prepared request, config is enabled by default and you can disable with -validate-query=false or

fix: query

---

dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/ingressv1beta1.go
dataclients/kubernetes/testdata/ingress/ingress-data/ing-with-prule-wrong-ing-port.default-filters/bar.foo
dataclients/kubernetes/testdata/ingress/ingress-data/ing-with-prule-wrong-ing-port.eskip
dataclients/kubernetes/testdata/ingress/ingress-data/ing-with-prule-wrong-ing-port.yaml
dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-prule-wrong-ing-port.default-filters/bar.foo
dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-prule-wrong-ing-port.eskip
dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-prule-wrong-ing-port.yaml
dataclients/kubernetes/testdata/routegroups/convert/target-endpoints-not-found.default-filters/myapp.default
dataclients/kubernetes/testdata/routegroups/convert/target-endpoints-not-found.eskip
dataclients/kubernetes/testdata/routegroups/convert/target-endpoints-not-found.yaml

dataclients/kubernetes: ignore `Ingress` user filters when no endpoints

---

dataclients/kubernetes/hosts.go
dataclients/kubernetes/ingress.go
eskip/string.go
eskip/template.go
filters/apiusagemonitoring/filter_endpointmetrics_test.go
filters/auth/oidc_test.go
metrics/utils.go
proxy/loopback_test.go
proxy/proxy_test.go
rfc/patchhost.go

Replace `strings.Replace(s, old, new, -1)` with `strings.ReplaceAll(s, old, new)`. `strings.ReplaceAll` is a wrapper function for `strings.Replace`, but `strings.ReplaceAll` is more readable and removes the hardcoded `-1`.

refactor: replace strings.Replace with strings.ReplaceAll

---

config/config.go
net/query.go
net/query_test.go

pull out logging query into separate handler such that we can log without blocking

pull out logging query into separate handler 

---

docs/reference/filters.md
filters/filters.go
filters/shedder/admission.go
filters/shedder/admission_test.go
proxy/proxytest/proxytest.go
skipper.go

load shedding filter admissionControl, part of https://github.com/zalando/skipper/issues/2004

feature: admissionControl filter

---

config/config.go
config/config_test.go
dataclients/kubernetes/clusterclient.go
dataclients/kubernetes/clusterstate.go
dataclients/kubernetes/ingressdefinitions.go
dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/ingressv1beta1.go
dataclients/kubernetes/kube.go
dataclients/kubernetes/routegroup.go
go.mod
go.sum
net/redisclient.go
net/redisclient_test.go
net/redistest/redistest.go
ratelimit/registry.go
skipper.go

In case of kubernetes dataclient we can detect the number of redis shards available and trigger an update to the redis ringclient.
In order to use this feature we have to use a forked version of go-redis (see replace directive in go.mod) until it is merged and released https://github.com/go-redis/redis/pull/2093

feature: dynamic detect and resize redis instances

---

.github/workflows/master.yaml
.github/workflows/pr.yaml
delivery.yaml

Pin build to Go 1.18 until it's ready for Go 1.19
Go 1.19 is being addressed in #2053 but is not a straight forward upgrade. So pin to 1.18 for now.

Pin build to Go 1.18

---

skipper.go

fix https://github.com/zalando/skipper/issues/2062
ignore gosec g114 for support and debug listener which should not be exposed to untrusted entities

ignore gosec g114 for support and debug listener

---

Dockerfile
go.mod
go.sum
packaging/Dockerfile
packaging/Dockerfile.arm64
packaging/Dockerfile.armv7
packaging/Makefile

This updates the base image to alpine 3 which always ensures the latest minor version being used. For opensource images this is `alpine:3` and for Zalando images this is `container-registry.zalando.net/library/alpine-3:latest`. Right now this will resolve to `3.16`.
Additionally it updates the `golang.org/x/crypto/ssh` library.
Both things addresses vulnerabilities reported for the latest images:
```
trivy i container-registry.zalando.net/teapot/skipper:v0.13.237
2022-08-22T19:28:15.151+0200	INFO	Vulnerability scanning is enabled
2022-08-22T19:28:15.151+0200	INFO	Secret scanning is enabled
2022-08-22T19:28:15.151+0200	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-08-22T19:28:15.151+0200	INFO	Please see also …
```

Update alpine base image to latest minor version

---

routing/datasource.go
routing/datasource_test.go
routing/export_test.go
routing/routing.go

This PR adds the ability to provide extra weight for custom predicates (there were some conversations about it in https://github.com/zalando/skipper/pull/1338, even if no consensus).
Some details:
- It's an opt-in feature: by default, predicates do not have any custom weight associated with it (on top of the weight they already have "[because they exist](https://github.com/ruudk/skipper/blob/master/routing/matcher.go#L58)")
- It's backwards compatible: no effect to all existing predicates
I think the implementation is pretty straight forward, it doesn't impact the core types (Predicate and PredicateSpec remain the same), it's memory efficient (it doesn't store a new weight integer per predicate, and instead has the integer in the PredicateSpec itself) and it gives a ton of flexibility for …

Add custom weight for custom predicates

---

config/config.go
skipper.go
skipper_test.go

Allow insecure connections on an alternate port when using TLS. This
will remove the requirement to encrypt all traffic when enabling TLS.
Fixes: #2065

feature: allow insecure connections when using tls

---

filters/shedder/admission.go
loadbalancer/healthchecker.go
secrets/encrypter.go

Fix: memory leak in admissionControl filter. In case routing changes triggers a lot of routing updates (f.e. every 3s) this would cause a leak of tickers and updates would be sent to the channel by Go runtime.

Fix: memory leak in admissionControl filter.

---

ratelimit/registry.go

fix: on close of ratelimit registry it should close all filters

---

filters/scheduler/fifo.go
filters/scheduler/fifo_test.go
scheduler/export_test.go
scheduler/fifo_test.go
scheduler/proxy_test.go
scheduler/scheduler.go
scheduler/scheduler_test.go

fix: counter should reflect semaphore state, right now metrics show only 0 or 1 sometimes 2 as "active"

fix: fifo error metric counted "other" errors in case there is no error

---

filters/scheduler/loopback_test.go
proxy/proxy.go

`*Proxy.do()` maybe called for the `<loopback>` backend which resulted in double call of pending `done` handlers.
In case `fifo` is configured on the main and loopback route double call leads to panic:
```sh
./bin/skipper -inline-routes='loop: Path("/loop") -> fifo(100, 100, "1s") -> inlineContent("ok") -> <shunt>; main: Path("/") -> fifo(100, 100, "1s") -> setPath("/loop") -> <loopback>;'
curl -v localhost:9090/
[APP]ERRO[0015] http: panic serving 127.0.0.1:44918: semaphore: released more than held
```

proxy: fix FIFO/LIFO cleanup

---

docs/reference/filters.md
loadbalancer/algorithm.go
loadbalancer/algorithm_test.go
loadbalancer/fadein_test.go

closes https://github.com/zalando/skipper/issues/2081
Leaves the same implementation for random and roundRobin
Logic for consistentHash when a chosen endpoint is fading and it is decided not to send traffic to it:
- If all endpoints are fading, return original choice from consistent hash
- Else run consistent hash again, but only using non-fading endpoints

Implement fadeIn for consistent hash algorithm

---

config/config.go
routesrv/options.go
routesrv/polling.go
routesrv/routesrv.go
routesrv/routesrv_test.go
routesrv/testdata/internal-host-explicit-route-predicate.eskip
routesrv/testdata/internal-host-explicit-route-predicate.yaml
routesrv/testdata/lb-target-multi-with-default-filters.eskip
routesrv/testdata/lb-target-multi-with-oauth2-callback.eskip
routesrv/testdata/lb-target-multi-with-prepend-default-filters.eskip

In efforts to solve https://github.bus.zalan.do/pg9/issues/issues/33
We need to decrease number of skipper instances pulling routes from kubeapiserver, right now if we have 100 skipper instances all of them will pull from kubeapiserver, which will put some unneeded pressure on it.
The solution was to make a server to only pull routes from kubeapiserver and skipper will pull from that server.
**Old**
```
skipper -> apiserver
```
**New**
```
skipper -> routeSRV -> apiserver
```
RouteSRV was already implemented, but not deployed. In this PR we try to make sure there is no difference between `/routes` endpoints in skipper and routeSRV, while also moving all route handling to routeSRV instead of skipper.
- DefaultFilters
-  - [x] Implementation
-  - [x] Tests
-  - [ ] Docs
- OAuth2
-  - [x] …

Make use of default filters in `RouteSRV`

---

proxy/upgrade.go
proxy/upgrade_test.go

Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de> identified the change https://github.com/golang/go/commit/770e0e584a98dfd5e8d0d00558085c339fda0ed7 that processes 1xx response status headers differently.
This change refactors tests and adds handling of non-standard `101 Switching Protocols` response with `Connection: close` header.

proxy: fix connection upgrade test for go 1.19

---

routesrv/eskipbytes.go
routesrv/polling.go
routesrv/routesrv_test.go

add option to use Etag for /routes which serves eskip-formatted routes

---

swarm/nodeinfo.go
swarm/swarm.go

Fixes issue of panicking swam by handling the case where `NodeInfo` pointer is `nil`.
https://github.com/zalando/skipper/issues/2003

Fix swarm.Join() when NodeInfo pointer is nil

---

swarm/swarm.go

Fixes the panic in swarm `broadcast` function when the swarm pointer is `nil`.
Fixes: #1005 
Signed-off-by: noor <noormuhammadmalik95@gmail.com>

Fix swarm panic when swarm is `nil`.

---

delivery.yaml

Build step pushes multiple docker images which may fail in the middle before git tag is created. Subsequent pipeline ends up reusing the tag from the previously failed pipeline and fails to push docker image with `tag invalid: tag already exists`.
Also adds `set -euo pipefail` to prevent masking of shell pipeline errors.

build: create git tag early

---

routesrv/options.go
routesrv/routesrv.go

Implementation of this [issue](https://github.com/zalando/skipper/issues/2138) 
Signed-off-by: Nikhil Goel <nikhil8877@gmail.com>

allow route server to filter k8s client serverside resources using label selectors

---

eskip/eskip.go
eskip/eskip_test.go

CloneRoute Preprocessor was dropping builtin predicates resulting in wrong eskip
Refactor test cases for prepocessor and add one to test builtins.
Fixes up on #2134

bug: `CloneRoute` dropping builtin predicates

---

logging/access.go
logging/access_test.go
proxy/proxy.go

The auth filter already stores the username of the identified user in the state bag. This PR forwards this value to the access log filter by storing it in the AccessEntry structure.
It is then used in the `authuser` field of the Common Log Format formatter. It can also be accessed by other formatters (such as the JSON formatter) via the `auth-user` field of the logrus Entry.

Fill the authuser field of the access log

---

filters/ratelimit/ratelimit.go
filters/ratelimit/ratelimit_test.go

fix: Change group name in case maxShards are set to not cause downtime on reconfiguration of maxShards which configures the vnode shards. This will relax the config to allow double amount of requests during the reconfiguration, which seems to be a better choice than being more strict by a factor, that depends on former and new value of maxShards.

fix: Change group name in case maxShards are set

---

.github/workflows/codeql-analysis.yml
.github/workflows/gh-packages.yaml
.github/workflows/master.yaml
.github/workflows/pr.yaml

Addresses https://github.com/zalando/skipper/issues/2137 by adding permissions for CI jobs for security hardening.
Signed-off-by: noor <noormuhammadmalik95@gmail.com>

Add permissions hardening for the CI

---

.github/workflows/pr.yaml

The PR adds [semgrep](https://github.com/dgryski/semgrep-go) based checking on the source code. Adds it as a new job to the CI to be triggered upon `pr`.
Addresses: #2055

Add semgrep job in the CI

---

.github/workflows/codeql-analysis.yml

fix: codeql v1->v2 migration https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
see also: https://github.com/zalando/skipper/actions/runs/3546170144/jobs/5954934959#step:3:55

fix: codeql v1->v2 migration

---

docs/tutorials/basics.md

What?
Remove the sentence describing that the used needed go version >= 1.11
because of go modules.
Why?
This sentence was misleading since currently you need go version >= 1.19
and this was added just to make clear the necessity of go modules which
by now is something that can be assumed, since the go project uses
go modules for quite some time now.
The idea to just remove it instead to update the version is that this is
something pretty straight forward to find out and without this sentence
here we don't need to remember to update the docs everytime we update
the version.
-----
Signed-off-by: Lucas Thiesen <lucas.thiesen@zalando.de>

Update minimal version to build skipper in docs

---

proxy/upgrade.go

See https://github.com/golang/go/issues/4373

proxy: use errors.Is instead of string match

---

dataclients/kubernetes/kubernetestest/api.go
dataclients/kubernetes/kubernetestest/api_test.go
dataclients/kubernetes/kubernetestest/testdata/kind-list.yaml

This is useful for testing cluster snapshots obtained e.g. like:
```sh
kubectl get routegroups,ingresses,services,endpoints -A -o yaml > snapshot.yaml
```

dataclients/kubernetestest: support `kind: List` fixtures

---

eskip/eskip.go
eskip/eskip_test.go
eskip/lexer.go

```
name               old time/op    new time/op    delta
ParsePredicates-8    4.80µs ± 4%    3.11µs ± 8%  -35.27%  (p=0.000 n=10+9)
name               old alloc/op   new alloc/op   delta
ParsePredicates-8    6.22kB ± 0%    0.74kB ± 0%  -88.03%  (p=0.000 n=10+10)
name               old allocs/op  new allocs/op  delta
ParsePredicates-8      37.0 ± 0%      35.0 ± 0%   -5.41%  (p=0.000 n=10+10)
```

eskip: reuse lexer and parser

---

go.mod
go.sum
proxy/context.go
proxy/debug.go
proxy/debug_test.go
proxy/proxy.go
proxy/proxy_test.go

In case of filter panic proxy abrupts filter chain and responds with 500 InternalServerError.

proxy: refactor filter panic handling

---

ratelimit/swim.go

In case the Swarm is not operative, an error is logged.
However, that error is only logged and proceeded unverified.
This leads eventually into a panic of a nil pointer dereference.
fixes: #2197
Signed-off-by: Samuel Lang <gh@lang-sam.de>

swarm nil pointer dereference panic

---

filters/shedder/admission.go

Text of the log message makes me think that such log message should not be printer not always but only in case where calculated RPS is less than required minimum.

Moved logging in admissionControl under the right if condition

---

docs/tutorials/auth.md
filters/auth/grant_test.go

Documents a way to provide a fixed value of the `redirect_uri` authorization flow parameter and adds a test for it.

filters/grant: document `redirect_uri` configuration

---

cmd/eskip/args.go
cmd/eskip/args_test.go
cmd/eskip/doc.go
cmd/eskip/load.go
eskip/string.go
eskip/string_test.go

Create `-sort-predicates` flag for eskip

---

filters/auth/grant.go
filters/auth/grant_test.go
filters/auth/grantcallback.go
filters/auth/grantclaimsquery_test.go
filters/auth/grantconfig.go
filters/auth/grantcookie.go
filters/auth/grantcookie_test.go
filters/auth/grantlogout.go
filters/auth/grantlogout_test.go
filters/auth/grantprep.go

filters/auth: make oauthGrant check token cookie is allowed for request domain
This prevents reuse of leaked cookie in another domain

filters/auth: make `oauthGrant` check token cookie is allowed for request domain

---

dataclients/kubernetes/kube_test.go
eskip/eskip.go
eskip/eskip_test.go
filters/auth/forwardtoken_test.go
filters/auth/grant_test.go
filters/auth/grantlogout_test.go
filters/builtin/decompress_test.go
filters/builtin/inlinecontent_test.go
filters/builtin/inlinecontentifstatus_test.go
filters/shedder/admission_test.go
filters/tee/tee_test.go
filters/tee/teeloopback_test.go
predicates/traffic/traffic_test.go
proxy/backendratelimit_test.go
proxy/fallbackgroup_test.go
proxy/lb_failingbackend_test.go
proxy/split_test.go
routesrv/routesrv_test.go
routing/host_test.go

This is useful in tests to reduce boilerplate (similar to e.g. https://pkg.go.dev/regexp#MustCompile).
See also discussion https://github.com/golang/go/issues/54297

eskip: add `MustParse`

---

Makefile

See https://github.com/securego/gosec/issues/925

gosec: disable G307

---

proxy/proxy_test.go

The test is failing in CDP with go1.20

proxy: fix TestFlusherImplementation

---

proxy/proxytest/cert.go
proxy/proxytest/proxytest.go
proxy/proxytest/proxytest_test.go

* introduces Config to simplify creation of test proxy
* adds helper to create certificate for given domains
* starts TLS server when certificate is present

proxy/proxytest: add TLS support

---

filters/auth/grant_test.go
filters/auth/grantclaimsquery_test.go
filters/auth/grantconfig.go
filters/auth/grantlogout_test.go

Token cookie domain has Secure attibute and its domain is derived from the request.Host value. This change uses request.Host to build original and redirect url and enforces https scheme for consistency. It also refactors tests to use https.

filters/auth/grant: use request.Host and https scheme in original and redirect urls

---

net/redistest/redistest.go
ratelimit/redis_test.go

Such performance tests are needed for us to find out how huge keys can Skipper ratelimiter use without significant performance degradation.

Added the performance clusterLimitRedis.Allow operation

---

proxy/proxy.go
proxy/proxy_test.go
proxy/utils.go

refactor: proxy error response to always have a response defined to simplify the logic

refactor: proxy error response

---

config/config.go
filters/auth/grant.go
filters/auth/grant_test.go
filters/auth/grantcallback.go
filters/auth/grantconfig.go
filters/auth/grantlogout.go
secrets/file.go
skipper.go

This change enables `{host}` placeholder in the client id and secret filenames.
E.g. for the request to `foo.example.org` when flag values are `-oauth2-client-id-file=/var/run/secrets/{host}-client-id` and `-oauth2-client-secret-file=/var/run/secrets/{host}-client-secret` the client id and secret files would be `/var/run/secrets/foo.example.org-client-id` and `/var/run/secrets/foo.example.org-client-secret` respectively.

filters/auth/grant: support client id and secret file placeholders

---

secrets/file.go
secrets/file_test.go

This change tracks registered paths instead of secret files and re-reads directory contents on each refresh cycle to discover added or removed files.
Fixes https://github.com/zalando/skipper/issues/1858

secrets: discover files added or removed to the directory path

---

config/config.go
config/config_test.go
script/script.go
script/script_test.go
skipper.go

feature that fixes https://github.com/zalando/skipper/issues/2262
config option -lua-sources allows to set:
- `-lua-sources=none` to disable lua sources
- `-lua-sources=file` to only allow file sources
- `-lua-sources=inline` to only allow inline scripts
- `-lua-sources=inline -lua-sources=file` to allow both, which is also the default as before.

feature: lua config to selective enable inline,file,none

---

.github/workflows/openssf-scorecard.yaml
readme.md

add openssf scorecard and auto update GH action
doc fix: cii best practices is called openssf best practices nowadays
Following https://github.com/ossf/scorecard-action#installation

add openssf scorecard and auto update GH action

---

filters/apiusagemonitoring/filter.go

fix: apiUsageMonitoring to be able to observe client timeout error case and record 499 status codes
fix this: https://github.com/zalando/skipper/issues/1238#issuecomment-727878056

fix: apiUsageMonitoring to be able to observe client timeout

---

filters/auth/auth.go
filters/auth/forwardtoken.go
filters/auth/forwardtokenfield.go
filters/auth/grant.go
filters/auth/grantcallback.go
filters/auth/grantlogout.go
filters/auth/jwt_validation.go
filters/auth/oidc.go
filters/auth/oidc_introspection.go
filters/auth/tokeninfo.go
filters/auth/tokenintrospection.go
filters/auth/webhook.go
filters/builtin/decompress.go
filters/builtin/inlinecontentifstatus.go
filters/builtin/preservehost.go
filters/diag/logheader.go
filters/filters.go
filters/filtertest/filtertest.go
filters/log/log.go
filters/ratelimit/ratelimit.go
filters/ratelimit/ratelimit_test.go
filters/scheduler/fifo.go
filters/scheduler/lifo.go
filters/tee/tee.go
filters/tee/teeloopback.go
proxy/context.go
tracing/tracing.go

Provide TraceID in the logs

---

.github/workflows/codeql-analysis.yml
.github/workflows/docs.yaml
.github/workflows/gh-packages.yaml
.github/workflows/master.yaml

fix: openssf card scan told to remove top level permissions, as every job has a set of permissions we should be able to drop top-level permissions to 0

fix: openssf card scan told to remove top level permissions

---

dataclients/kubernetes/ingress_test.go
dataclients/kubernetes/kube_test.go
dataclients/kubernetes/path_test.go
dataclients/kubernetes/testdata/ingress/ingress-data/ing-with-prule-wrong-ing-port.default-filters/bar.foo
dataclients/kubernetes/testdata/ingressV1/traffic/1-2-3-4.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/1-2-3-4.yaml
dataclients/kubernetes/testdata/ingressV1/traffic/20-60-20.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/20-60-20.yaml
dataclients/kubernetes/testdata/ingressV1/traffic/25-45-3-27.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/25-45-3-27.yaml
dataclients/kubernetes/testdata/ingressV1/traffic/60-140.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/60-140.yaml
dataclients/kubernetes/testdata/ingressV1/traffic/three-backends-with-one-zero-weight.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/three-backends-with-one-zero-weight.yaml
dataclients/kubernetes/testdata/ingressV1/traffic/two-backends-no-weights.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/two-backends-no-weights.yaml
dataclients/kubernetes/testdata/ingressV1/traffic/two-backends-with-one-zero-weight.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/two-backends-with-one-zero-weight.yaml
dataclients/kubernetes/testdata/ingressV1/traffic/with-path-30-70.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/with-path-30-70.yaml

This change converts tests of computeBackendWeightsV1 into equivalent Ingress fixtures which should simplify refactoring of the weight calculation algorithm.

dataclients/kubernetes: use fixtures to test Ingress backend weights

---

filters/auth/grant_test.go
filters/auth/grantclaimsquery_test.go
metrics/metricstest/metricsmock.go
proxy/metrics_test.go
proxy/proxy.go
proxy/proxytest/proxytest.go

* Adds previously missing tests for proxy metrics
* Adds GetBody helper to the proxytest client
For https://github.com/zalando/skipper/issues/2307

proxy: add uncompressed response counter

---

Makefile

doc: makefile self documented similar to kubernetes project does it
https://github.com/kubernetes-sigs/kubebuilder/blob/d0a1806c1d25c70777004271a4b773b490de3bcd/Makefile#L43-L44
```
% make help
Usage:
make <target>
help             Display this help
lib              build skipper library
skipper          build skipper binary
eskip            build eskip binary
build            build libe and all binaries
install          install skipper and eskip binaries into your system
check            run all tests
shortcheck       run all short tests
cicheck          run all short and redis tests
check-race       run all tests with race checker
bench            run all benchmark tests
fuzz             run all fuzz tests
lint             run all linters
clean            clean temorary files and …
```

doc: makefile self documented similar to kubernetes project does it

---

proxy/upgrade_test.go

test: fix data race in upgrade header test
```
--- FAIL: TestAuditLogging (0.00s)
--- FAIL: TestAuditLogging/on (0.00s)
upgrade_test.go:427: failed to enable audit log
==================
WARNING: DATA RACE
Write at 0x00c0004894a0 by goroutine 3828:
bytes.(*Buffer).grow()
/opt/hostedtoolcache/go/1.20.4/x64/src/bytes/buffer.go:128 +0x450
bytes.(*Buffer).Write()
/opt/hostedtoolcache/go/1.20.4/x64/src/bytes/buffer.go:170 +0xcd
io.(*multiWriter).Write()
/opt/hostedtoolcache/go/1.20.4/x64/src/io/multi.go:85 +0xc5
io.copyBuffer()
/opt/hostedtoolcache/go/1.20.4/x64/src/io/io.go:429 +0x2de
io.Copy()
/opt/hostedtoolcache/go/1.20.4/x64/src/io/io.go:386 +0x93
github.com/zalando/skipper/proxy.copyAsync.func1()
/home/runner/work/skipper/skipper/proxy/upgrade.go:218 +0x72
Previous read at 0x00c0004894a0 …
```

test: fix data race in upgrade header test

---

docs/reference/predicates.md
eskip/eskip.go
predicates/predicates.go
predicates/traffic/export_test.go
predicates/traffic/segment.go
predicates/traffic/segment_test.go
proxy/context.go
proxy/proxy.go
routing/context.go
routing/datasource_test.go
skipper.go

This change adds routing context to pass information between multiple predicates and uses it to implement new TrafficSegment predicate.

predicates: add TrafficSegment predicate

---

dataclients/kubernetes/definitions/routegroups.go
dataclients/kubernetes/definitions/testdata/validation/duplicate-default-backend.log
dataclients/kubernetes/definitions/testdata/validation/duplicate-default-backend.yaml
dataclients/kubernetes/definitions/testdata/validation/route-with-duplicate-backend-reference.log
dataclients/kubernetes/definitions/testdata/validation/route-with-duplicate-backend-reference.yaml

dataclients/kubernetes: reject RouteGroups with duplicate backend references

---

docs/kubernetes/ingress-usage.md
docs/reference/filters.md

According to the filter reference, localRateLimit is deprecated and replaced by clientRateLimit.
This fixes this.
In addition, I noticed that in [the rendered docs page](https://opensource.zalando.com/skipper/reference/filters/#rate-limit) the `~~` is not rendered as a strike-through. The second commit tries to fix that (by using `<del>` directly).
I didn't try generating the documentation (as I didn't find an description on how to do this locally).

Ingress docs: localRateLimit → clientRateLimit

---

etcd/etcd_test.go

After the etcd tests are done, etcd is not terminated.
Subsequent tests may therefore fail because an etcd process is still running and a new process of etcd can't start.
For example, if tests are run locally.
Executing os.Exit() terminates the program immediately; the deferred `etcdtest.Stop()` function is not executed [1].
The provided patch would terminate the etcd process in the end.
[1]\: https://pkg.go.dev/os#Exit

fix: terminate etcd process after running tests

---

etcd/etcd.go
etcd/etcd_test.go
etcd/etcdtest/mocketcd.go

Since we process a very large number of routes, we want to automatically clean up deprecated and thus expired routes.
Therefore, we use the TTL of etcd to automatically expire and remove old routes stored in etcd.
Currently routes with expired TTL are removed from etcd but stay active in Skipper until a restart of Skipper is performed.
Expiring routes from etcd provoke a parsing error when `LoadUpdate()` is executed.
This patch would allow Skipper to support both the already supported etcd `delete` action and additionally the `expire` action to ensure that routes are removed.
The tests are extended accordingly to verify the correct behavior of expiring routes.
`TestReceiveExpire` adds a route with the minimum TTL of 1 second. This route must expire and be removed.

feature: add TTL support for routes in etcd

---

dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/testdata/ingressV1/traffic/no-weights.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/no-weights.yaml
dataclients/kubernetes/testdata/ingressV1/traffic/three-backends-with-one-zero-weight.eskip

When there are more than two backend services and no weights are specified, dataclient should add correct number of `True()` predicates to adjust route weights.
Example:
```
rN: Path("/foo") && Traffic(...) && True() && True() ... True() -> ...
...
r3: Path("/foo") && Traffic(...) && True() && True() -> ...
r2: Path("/foo") && Traffic(...) && True() -> ...
r1: Path("/foo") && Traffic(...) -> ...
r0: Path("/foo") -> ...
```

dataclients/kubernetes: fix Ingress backend weights for more than two services

---

go.mod
go.sum
metrics/metrics_test.go

update: github.com/rcrowley/go-metrics - codahale
test: fix metrics tests to use separate created metrics instead relying on implicitly defined runtime metrics, which are dropped by sync.Once package global in https://github.com/rcrowley/go-metrics/commit/615496d9b7277a58d61fdeb8f9a3d4185fcf1bb2

update: github.com/rcrowley/go-metrics - codahale

---

dataclients/kubernetes/testdata/ingressV1/traffic/issue2268.eskip
dataclients/kubernetes/testdata/ingressV1/traffic/issue2268.yaml
dataclients/kubernetes/testdata/routegroups/traffic/issue2268.eskip
dataclients/kubernetes/testdata/routegroups/traffic/issue2268.yaml

This change adds tests to demonstrate the problem described in #2268

dataclients/kubernetes: add tests for traffic split with custom route

---

dataclients/kubernetes/testdata/routegroups/traffic/issue2268-2.eskip
dataclients/kubernetes/testdata/routegroups/traffic/issue2268-2.yaml

This change adds test to demonstrate the problem with custom route with traffic split described in #2268

dataclients/kubernetes: add test for traffic split with custom route

---

dataclients/kubernetes/definitions/definitions.go
dataclients/kubernetes/definitions/ingressv1.go
dataclients/kubernetes/definitions/routegroups.go
dataclients/kubernetes/ingress.go
dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/routegroup.go
dataclients/kubernetes/traffic.go

* use the same algorithm to calculate arguments for Traffic() predicate for both Ingress and RouteGroup
* add GetBackendTrafficCalculator factory method to support alternative implementations
For #2268

dataclients/kubernetes: refactor Ingress and RouteGroup backend weight calculation

---

predicates/traffic/segment.go
predicates/traffic/segment_test.go

* use test request with exactly the same random value as min and max arguments
* add tests for common edge cases
For #2268

predicates/traffic: add TrafficSegment min equals max tests

---

dataclients/kubernetes/ingress.go
dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/kube.go
dataclients/kubernetes/kubernetestest/fixtures.go
dataclients/kubernetes/routegroup.go
dataclients/kubernetes/routegroups_test.go
dataclients/kubernetes/testdata/routegroups/traffic-segment/0-1-2.eskip
dataclients/kubernetes/testdata/routegroups/traffic-segment/0-1-2.kube
dataclients/kubernetes/testdata/routegroups/traffic-segment/0-1-2.yaml
dataclients/kubernetes/testdata/routegroups/traffic-segment/20-30-50.eskip
dataclients/kubernetes/testdata/routegroups/traffic-segment/20-30-50.kube
dataclients/kubernetes/testdata/routegroups/traffic-segment/20-30-50.yaml
dataclients/kubernetes/testdata/routegroups/traffic-segment/issue2268.eskip
dataclients/kubernetes/testdata/routegroups/traffic-segment/issue2268.kube
dataclients/kubernetes/testdata/routegroups/traffic-segment/issue2268.yaml
dataclients/kubernetes/testdata/routegroups/traffic-segment/no-weights.eskip
dataclients/kubernetes/testdata/routegroups/traffic-segment/no-weights.kube
dataclients/kubernetes/testdata/routegroups/traffic-segment/no-weights.yaml
dataclients/kubernetes/testdata/routegroups/traffic-segment/one-backend.eskip
dataclients/kubernetes/testdata/routegroups/traffic-segment/one-backend.kube
dataclients/kubernetes/testdata/routegroups/traffic-segment/one-backend.yaml
dataclients/kubernetes/traffic.go
dataclients/kubernetes/traffic_segment.go

* adds backend traffic split algorithm implementation based on TrafficSegment predicate
* adds BackendTrafficAlgorithm k8s dataclient option (for now only available in tests)
* adds basic test suite for the implementation
This is part 1 of N in series of changes.
For #2268

dataclients/kubernetes: add TrafficSegment-based backend traffic calculator

---

queuelistener/listener.go
queuelistener/listener_test.go
queuelistener/ring.go
skipper.go

optimize: change max from 1GB to 4GB to accept tcp connections in the tcp listener
otherwise we throttle performance for large nodes

optimize: change max from 1GB to 4GB to accept tcp conns

---

skipper.go
skipper_test.go

* fix swarm init error handling
* remove TestDataClients invalid swarm options

skipper: fix TestDataClients

---

skipper.go
skipper_test.go

Currently CertRegistry is created when KubernetesEnableTLS is set but this may change in the future so this change refactors tlsConfig to check CertRegistry instead of KubernetesEnableTLS option.

skipper: decouple tlsConfig from KubernetesEnableTLS option

---

predicates/traffic/segment_test.go

Test failure could be reproduced via:
```
go test ./predicates/traffic/ -count=100 -run=TestTrafficSegmentSplit
```
* use delta of expected value instead of total number of test requests
* use predefined number of test requests for all tests
Based on the biggest difference seen for 1000 test requests:
```
Max difference between 500 and 462 allowed is 25, but difference was 38
```
the delta should be 38/500=0.076
To reduce flakiness:
* increase total number of samples to 10'000
* then increase delta to 6% based on the failed test case output

predicates/traffic: fix flaky TrafficSegment tests

---

dataclients/kubernetes/ingress.go
dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/routegroup.go
dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-prule-wrong-ep-port.log
dataclients/kubernetes/testdata/ingressV1/tls/tls-invalid-secret.log
dataclients/kubernetes/testdata/ingressV1/tls/tls-invalid-tls.log
dataclients/kubernetes/testdata/ingressV1/tls/tls-missing-host.log
dataclients/kubernetes/testdata/ingressV1/tls/tls-missing-secret.log
dataclients/kubernetes/testdata/routegroups/convert/failing-filter.log
dataclients/kubernetes/testdata/routegroups/convert/failing-filter.yaml
dataclients/kubernetes/testdata/routegroups/convert/failing-predicate.log
dataclients/kubernetes/testdata/routegroups/convert/failing-predicate.yaml
dataclients/kubernetes/testdata/routegroups/convert/failing-route-groups-ignored.eskip
dataclients/kubernetes/testdata/routegroups/convert/failing-route-groups-ignored.log
dataclients/kubernetes/testdata/routegroups/convert/failing-route-groups-ignored.yaml
dataclients/kubernetes/testdata/routegroups/convert/invalid-backend-implicit-route.log
dataclients/kubernetes/testdata/routegroups/convert/missing-service.log
dataclients/kubernetes/testdata/routegroups/convert/no-catchall-for-failed-route-group.log
dataclients/kubernetes/testdata/routegroups/convert/service-not-cluster-ip-type.log
dataclients/kubernetes/testdata/routegroups/convert/single-failing-route-makes-the-group-fail.log
dataclients/kubernetes/testdata/routegroups/convert/target-port-not-found.log
dataclients/kubernetes/testdata/routegroups/default-filters/invalid-filters-explicit-route.log
dataclients/kubernetes/testdata/routegroups/default-filters/invalid-filters-implicit-route.log
dataclients/kubernetes/testdata/routegroups/east-west-range/internal-host-error-transforming.log
dataclients/kubernetes/testdata/routegroups/with-ingress/failing-ingress-item.log

Ingress context has a logger that logs related ingress name and namespace.
This change:
* adds kind, name and namespace logger fields
* adds logger to RouteGroup context
* uses context loggers instead of global where applicable
* removes `convertPathRuleV1: ` prefix and makes all log messages start from capital letter

dataclients/kubernetes: improve logging

---

dataclients/kubernetes/export_test.go
dataclients/kubernetes/ingress.go
dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/kube.go
dataclients/kubernetes/logger.go
dataclients/kubernetes/logger_test.go
dataclients/kubernetes/routegroup.go

Log Ingress/RouteGroup processing messages at most once per minute unless log level is debug.

dataclient/kubernetes: reduce amount of logs

---

loadbalancer/algorithm.go
loadbalancer/fadein_test.go
loadbalancer/locked_source.go
loadbalancer/locked_source_test.go

+ Introduced lockedSource type to avoid concurrent use of rand.Source
+ Added test calling lockedSource concurrently
+ Added benchmark for loadbalancer
+ Removed some unused fields from {random,roundRobin,consistentHash} structs
+ Preallocate slices
+ Do not use weightedSums slice
Updates https://github.com/zalando/skipper/issues/2346

Introduce lockedSource type to avoid concurrent use of rand.Source

---

dataclients/kubernetes/ingress.go
dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/kube.go
dataclients/kubernetes/logger_test.go
dataclients/kubernetes/routegroup.go

Logging should be enabled after loggingInterval elapsed since it was last enabled (and not since last update).
Followup on https://github.com/zalando/skipper/pull/2427

dataclients/kubernetes: fix logging

---

cmd/webhook/main.go
go.mod
go.sum

Kingpin is only used in webhook admission, it makes sense to remove it and use flag package like we do everywhere.
This will stay in draft mode sense we don't have a test case for webhook admission flags, so another PR will be created to test the flags first, then we will follow up on this.

Get rid of kingpin

---

Makefile
cmd/eskip/args_test.go
cmd/eskip/write_test.go
net/redistest/redistest.go
script/options_test.go

Use ./... instead of loop over packages.
Originally loop over packages was added by #359 that introduced glide package manager. This manager fetches dependencies into vendor/ subdirectory (see https://glide.readthedocs.io/en/latest/getting-started/) and apparently loop over packages was necessary back then. glide usage was removed by #764
The change now also runs testable examples.
Also:
* increases redis testcontainer ping and shutdown timeouts after observed CI failures
* fixes cmd/eskip etcd shutdown similar to #2359
* fixes cmd/eskip test introduced by #2202
* fixes lua example
* removed bench target as it makes little sense
* .coverprofile-all can not be simplified yet due to https://github.com/golang/go/issues/45361

build: simplify go commands

---

Makefile
dataclients/routestring/example_test.go

Use ./... instead of loop over packages.
Followup on #2449 and #2450
Also:
* increases routestring Example timeout after observing sporadic failures

build: simplify go commands (2)

---

net/redistest/redistest.go

Redis testcontainer fails to start due to https://github.com/testcontainers/testcontainers-go/issues/1359 caused by https://github.com/golang/go/issues/61076 and we can not pin cdp-runtime/go to a working patch version before 1.20.6

Temporary skip tests using net/redistest

---

Makefile

* remove unnecessary bin target
* remove bin directory during clean
* fix typo
* do not clean entire go build cache (see https://github.com/golang/go/issues/53725)

build: cleanup Makefile

---

config/config.go
filters/auth/grant_test.go
filters/auth/grantconfig.go
filters/auth/grantcookie.go
skipper.go

Add a flag to allow insecure grant flow:
* issue token cookie without secure attribute
* use http schem for callback url

filters/auth: allow insecure grant flow

---

packaging/Dockerfile

Dependabot does not update ARG instruction and updates only the first FROM instruction, see https://github.com/dependabot/dependabot-core/issues/2057
This change uses workaround described here https://github.com/dependabot/dependabot-core/issues/2057#issuecomment-1351660410

packaging: fix Dockerfile to support dependabot updates

---

.github/workflows/pr.yaml

Looks like the project is abandoned:
* https://github.com/praetorian-inc/gokart/issues/88 is not fixed since several months.
* last commit is ten months old.
Updates #2161

build: remove gokart

---

cmd/skipper/main.go

This disables `level=fatal msg="<nil>"` message after succesfull shutdown.

skipper: do not log nil error after shutdown

---

skipper_test.go

Make test request in parallel to ensure another request is refused not only after shutdown started but also while shutdown is still in progress (i.e. while test request is still in progress).
Verify shutdown completes after test request is finished.
Rename tests to have the same prefix.
Updates #988 #1865

skipper: fix shutdown test

---

docs/reference/filters.md
filters/cookie/cookie.go
filters/cookie/cookie_test.go

filters/cookie: allow expiration

---

queuelistener/listener_test.go

Queuelistener continously calls Accept on the testListener which keeps a buffer of last accepted testConnections in the conns channel.
The test code races to receive from the same channel so Accept goroutine may occasionally block receiving from the empty channel which would be detected by goroutine leak detector introduced by the #2499.
The problem could be reproduced e.g. by running:
```
GODEBUG=tracebackancestors=10 go test ./queuelistener/ -run=TestTeardown/connections_accepted_from_the_wrapped_listener_closed_after_tear_down -count=1000
noleak: 1 active
goroutine 2655 [chan receive]:
github.com/zalando/skipper/queuelistener.(*testListener).Accept(0xc0000e7830)
...
```
This change avoids blocking Accept on potentially empty channel.

queuelistener: fix testListener goroutine leak

---

predicates/traffic/segment_test.go

TrafficSegment tests perform 10k test requests per test case.
Add `inlineContent("")` to test routes to have `Content-Length: 0` response header that disables chunked encoding and speeds up the tests.
Before:
```
go test ./predicates/traffic/ -count=1 -run=TestTrafficSegment
ok      github.com/zalando/skipper/predicates/traffic   8.928s
```
After:
```
go test ./predicates/traffic/ -count=1 -run=TestTrafficSegment
ok      github.com/zalando/skipper/predicates/traffic   4.285s
```
To further speedup make test requests in parallel:
```
go test ./predicates/traffic/ -count=1 -run=TestTrafficSegment
ok      github.com/zalando/skipper/predicates/traffic   1.554s
```
See related #2459 #1562

predicates/traffic: speedup TrafficSegment tests

---

filters/auth/oidc.go
filters/auth/oidc_test.go

We are facing a security vulnerability by the use of `DisplayName` as the unique identifier in Azure-AD.
Since this field can be duplicated it can be exploited to gain privileges.
https://morgansimonsen.com/2016/06/28/azure-ad-allows-duplicate-group-names/
Switching to the guaranteed unique identifier `onPremisesSamAccountName` available in the Microsoft Graph API

🚑️ OIDC: use Azure-AD unique identifier

---

cmd/eskip/load.go
etcd/etcd.go
filters/apiusagemonitoring/spec.go
routing/datasource.go

gosec started to produce false positives
"G601 (CWE-118): Implicit memory aliasing in for loop." for slices of struct pointers, see https://github.com/securego/gosec/issues/966
This changes fixes G601 rule wwarnings instead of muting it.

gosec: fix G601 rule

---

cmd/eskip/load.go
cmd/eskip/load_test.go

This change to `eskip check` validates no routes have empty backend. 
"empty url" error falls between the "_pure syntactical_" checks that `eskip check` runs at validation time and the "_route-specific setup-dependant_" checks that skipper does at runtime (making sure, for example, that all predicates / filters exist, etc).
While this is not a fatal error, and loading the skip files in skipper works (only the specific route gets discarded), we think having this validation in `eskip check` is a better approach, because this is an error that is known in advance (no URL can be empty) and we could not find a reason we'd ever want to, on purpose, push a non-working route to production.
Fixes #2523

Eskip check fails on empty URL on network backend.

---

proxy/backendtest/backendrecorder_test.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6a07a3]
goroutine 10 [running]:
github.com/zalando/skipper/proxy/backendtest.TestServerShouldCloseWhenAllRequestsAreFulfilled.func1(0x0?)
/workspace/proxy/backendtest/backendrecorder_test.go:20 +0xc3
created by github.com/zalando/skipper/proxy/backendtest.TestServerShouldCloseWhenAllRequestsAreFulfilled in goroutine 6
/workspace/proxy/backendtest/backendrecorder_test.go:15 +0x45
```

proxy/bakendtest: fix panic in test

---

routesrv/eskipbytes.go
routesrv/export_test.go
routesrv/polling.go
routesrv/routesrv.go
routesrv/routesrv_test.go

* fix flaky test by mocking clock instead of using sleep.
* add tracing tag on route update
Follows up on #2526

routesrv: fix flaky TestESkipBytesHandlerWithOldLastModified

---

proxy/backendtimeout_test.go

backendTimeout("1ms") in TestSlowService may cancel context during
dialing which results in `i/o timeout` error and 502 response status
```
$ go test ./proxy -run=TestSlowService -count=10000 | grep -F 'FAIL:' -C1
...
time="2023-08-18T20:50:57+02:00" level=error msg="error while proxying after 1.295026ms, route  with backend network http://127.0.0.1:38613/, status code 502: dialing failed true: failed to do backend roundtrip to 127.0.0.1:38613: dial tcp 127.0.0.1:38613: i/o timeout, remote host: 127.0.0.1, request: \"GET / HTTP/1.1\", host: 127.0.0.1:36801, user agent: \"Go-http-client/1.1\""
--- FAIL: TestSlowService (0.00s)
backendtimeout_test.go:40: expected 504, got: &{502 Bad Gateway 502 HTTP/1.1 1 1 map[Content-Length:[12] Content-Type:[text/plain; charset=utf-8] Date:[Fri, 18 Aug …
```

proxy: fix flaky TestSlowService

---

packaging/Dockerfile

```
~$ docker pull registry.opensource.zalan.do/library/alpine-3:latest
latest: Pulling from library/alpine-3
Digest: sha256:2213d4d74c39af5313b631cbde2630b4007755b280f0f6b98867f66103b76113
Status: Image is up to date for registry.opensource.zalan.do/library/alpine-3:latest
registry.opensource.zalan.do/library/alpine-3:latest
```
Related to #2536

packaging: update base image version

---

filters/auth/webhook_test.go

fix: test flakyness by changing sleeps and speedup test (follow up from #2540)
```
% go test ./filters/auth -run TestWebhook -count 100
ok      github.com/zalando/skipper/filters/auth 21.191s
```

fix: test flakyness by changing sleeps and speedup test

---

skipper.go
skipper_test.go

This PR enables applications that extends skipper to pre-initialize `Tracer` instance and feed it directly to Skipper overriding `OpenTracing`. The need for this arises due to the inherent behaviour of skipper making the `Tracer` available only via request context. Thus preventing the extending application to reuse the tracer instance.

add Tracer to skipper options (overrides OpenTracing)

---

cmd/webhook/admission/admission.go
cmd/webhook/admission/admission_test.go
cmd/webhook/admission/definitions.go
cmd/webhook/admission/ingress.go
cmd/webhook/admission/routegroup.go

* return admission response with Allowed=false in case of validation errors
* fix approved and rejected request metrics
* add tests for malformed requests

cmd/webhook: refactor error handling

---

.github/workflows/gh-packages.yaml
.github/workflows/master.yaml
.github/workflows/pr.yaml
go.mod

fix: https://pkg.go.dev/net/http#NewResponseController was added in Go1.20 so we should also tell dependencies that this is a requirement
Updates https://github.com/zalando/skipper/issues/2433

fix: NewResponseController was added in Go1.20

---

packaging/Dockerfile
packaging/Dockerfile.arm64
packaging/Dockerfile.armv7

When hash is specified the tag is ignored, see https://github.com/moby/moby/issues/37866
The tag apparently confused dependabot and prevents it from updating the image:
```
updater | 2023/08/29 00:21:53 INFO <job_714994438> Checking if library/alpine-3 latest needs updating
updater | 2023/08/29 00:21:53 INFO <job_714994438> Latest version is latest
proxy | 2023/08/29 00:21:53 [018] HEAD https://registry.opensource.zalan.do:443/v2/library/alpine-3/manifests/latest
proxy | 2023/08/29 00:21:53 [018] 200 https://registry.opensource.zalan.do:443/v2/library/alpine-3/manifests/latest
updater | 2023/08/29 00:21:53 INFO <job_714994438> Pull request already exists for library/alpine-3 with latest version latest
```

packaging: remove base image tag

---

proxy/backendratelimit_test.go

Reuse redis instance for multiple tests.
Before
```
$ go test ./proxy -short -count=1 -run=TestBackendRatelimitScenarios
ok      github.com/zalando/skipper/proxy        9.700s
```
After:
```
ok      github.com/zalando/skipper/proxy        2.510s
```

proxy: speedup TestBackendRatelimitScenarios

---

packaging/Dockerfile

Dependabot fails to update registry.opensource.zalan.do/library/alpine-3 base image hash, see https://github.com/dependabot/dependabot-core/issues/7387
This change removes image hash and re-introduces latest label. For multiarch and ghcr.io builds base image is specified via BASE_IMAGE build argument and also uses latest label.
Followup on #2546

packaging: use latest label in Dockerfile

---

packaging/Dockerfile

* uses COPY instead of ADD following https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
* prints alpine release version during build
* removes redundant commands
* does not touch Dockerfile.arm64 and Dockerfile.armv7 - they are almost identical to Dockerfile and we may unify and use a single Dockerfile for all builds later.
Followup on #2546

packaging: update Dockerfile

---

proxy/upgrade.go
proxy/upgrade_test.go

The TestAuditLogging could flake because it checks audit log after receiving response message from the connection which may happen before write to audit log by io.MultiWriter has finished.
It could be reproduced via:
```
go test ./proxy -run=TestAuditLogging -count=10000 -failfast
```
This change writes to auditLog before writing to the connection which also would show failed message in the audit log in case write to connection fails.
Fixes #2572

proxy: fix flaky TestAuditLogging

---

cmd/eskip/args.go
cmd/eskip/doc.go
cmd/eskip/load.go
eskip/eskip_test.go
eskip/string.go
eskip/string_test.go

PRs #2202 and #2208 added SortPredicates flag to PrettyPrintInfo
and -sort-predicates flag to eskip tool which enables sorting
of built-in and regular predicates.
Header and HeaderRegexp built-in predicates are represented as maps
internally therefore sorting is necessary to obtain stable
eskip serialization of a route.
This was planned to be used in routesrv which serves routes in eskip
format and supports HTTP caching via ETag.
Regular predicates are evaluated in ordered and short-circuit manner
which makes it possible to put "cheap" predicates before "expensive".
Sorting regular predicates therefore breaks short-circuit evaluation.
With the above in mind it makes sense to sort built-in Header and
HeaderRegexp predicates unconditionally and leave regular predicates intact.
This change: …

eskip: sort built-in predicates

---

filters/fadein/fadein.go
filters/fadein/fadein_test.go
loadbalancer/algorithm.go
loadbalancer/algorithm_test.go
loadbalancer/fadein_test.go
proxy/proxy.go
routing/endpointregistry.go
routing/endpointregistry_test.go
routing/routing.go
skipper.go

This component is needed to create an easy way for loadbalancer, fadein, etc. to find out required information about endpoints to increase readability of those parts and enable us to provide new features there, for example, passive health checks for endpoints.

Introduce endpointregistry component

---

config/config.go
dataclients/kubernetes/clusterclient.go
dataclients/kubernetes/kube.go
skipper.go

Add flag to supply token file when running outside of cluster.
This is useful to test skipper/routesrv outside of the cluster without using kubectl proxy.

dataclients/kubernetes: add token file flag

---

routing/endpointregistry.go
routing/endpointregistry_test.go
routing/export_test.go

Do not use internal endpointregistry.lastSeen field in tests

Do not use internal endpointregistry.lastSeen field in tests

---

routing/routing.go
skipper.go

ref: https://github.com/zalando/skipper/issues/2595
adding Prometheus metrics for Routes health of `routes-total` and `routes-last-update` gauges that will allow to defines alerts if Skipper instances drift.

adding Prometheus metric for Routes health

---

dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/no-port-name-with-named-target-port.eskip
dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/no-port-name-with-named-target-port.kube
dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/no-port-name-with-named-target-port.yaml

For https://github.com/zalando/skipper/pull/2565

dataclients/kubernetes: add failing testcase for named service target port

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go

This PR adds the capability to use `response_headers_to_add` along with the Open Policy Agent based Skipper filter [opaauthorizerequest](https://opensource.zalando.com/skipper/reference/filters/#opaauthorizerequest), as described [here in Envoy external authorization filter](https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-additional-controls).

Add capability to set response headers in OPA filter

---

routing/endpointregistry.go
routing/endpointregistry_test.go

This check is needed for endpoints with latency more than lastSeenTimeout. They should still be kept in endpointregistry even after this timeout until all pending DecInflightOperations are done.

Check the absence of inflight requests before removing endpoint from endpointregistry

---

dataclients/kubernetes/kube.go

This should reduce log volume
For #2394

dataclients/kubernetes: log duplicate route error only when it differs

---

routesrv/polling.go

Log changed routes along with ids.
Use insert/updated/delete verbs to be consistent with datasource.go logging.

routesrv: log changed routes eskip

---

filters/scheduler/fifo_test.go

fix: flakytest TestFifo/fifo_with_reaching_max_concurrency_and_queue_timeouts https://github.com/zalando/skipper/issues/2557. The test is a little fuzzy so reduce the wanted ok rate by 0.0001 seems fine.

fix: flakytest TestFifo/fifo_with_reaching_max_concurrency_and_queue_timeouts

---

loadbalancer/algorithm.go
loadbalancer/algorithm_test.go

Get inflight requests number from endpointregistry instead of endpoint metrics

Get inflight requests number from endpointregistry instead of endpoint metrics

---

loadbalancer/algorithm.go
loadbalancer/algorithm_test.go
loadbalancer/fadein_test.go
proxy/proxy.go
routing/routing.go

The routing.Route field of routing.LBContext struct will be eventually removed because loadbalancer in general does not require the full information about route, only about endpoints to balance load between.
You can think about this PR as preliminary one for the https://github.com/zalando/skipper/pull/2634

Added LBEndpoint field in routing.LBContext struct

---

proxy/proxy.go

Rename setRequestURLForLoadBalancedBackend to selectEndpoint and move loadbalancing context creation inside
Followup on #2648

proxy: refactor loadbalanced endpoint selection

---

config/config.go
dataclients/kubernetes/definitions/routegroups.go
dataclients/kubernetes/ingress.go
dataclients/kubernetes/kube.go
dataclients/kubernetes/kubernetestest/fixtures.go
dataclients/kubernetes/routegroup.go
dataclients/kubernetes/testdata/ingressV1/ingress-data/disabled-catchall.eskip
dataclients/kubernetes/testdata/ingressV1/ingress-data/disabled-catchall.kube
dataclients/kubernetes/testdata/ingressV1/ingress-data/disabled-catchall.yaml
dataclients/kubernetes/testdata/routegroups/convert/disabled-catchall.eskip
dataclients/kubernetes/testdata/routegroups/convert/disabled-catchall.kube
dataclients/kubernetes/testdata/routegroups/convert/disabled-catchall.yaml
skipper.go

Catchall routes are created for Ingresses and RouteGroups that do not define predicates matching all requests for the host.
Initially catchall routes were introduced by #425 for #408. Later it was discovered that multiple Ingresses for the same host may create conflicting catchall routes which was fixed by #436.
Addition of RouteGroups #1180 introduced catchall routes for them as well but did not take into account that and Ingress and RouteGroup may use the same host which results in a catchall route created e.g. for RouetGroup that interferes with routes created for Ingress.
The plan is to remove catchall route logic because it simply shunts the request and responds with the default response status which matches the behaviour when Skipper can not look up route at all.
This change …

dataclients/kubernetes: allow disabling catchall routes

---

docs/reference/filters.md
filters/ratelimit/fail_closed.go
filters/ratelimit/fail_closed_test.go

ratelimitFailClosed is a route-wide configuration filter so it should apply to all ratelimit filters regardless of its position. 
PR consists of two commits: first refactors tests to simplify and allow routes with multiple filters and second makes ratelimitFailClosed apply regardless of the position in the route.

filters/ratelimit: apply ratelimitFailClosed regardless of the position in the route

---

delivery.yaml
packaging/Makefile

Fixes #2666
- The Windows binaries are now built as executables with the extension `.exe`
- The Windows binaries are now packed in a `zip` archive with the same directory structure as the `tar` archives for Linux and Darwin. The logic is overly complex due to the flattening function of the `zip` command not being as powerful as the one `tar` provides. If it is not a requirement to keep the directory structure inside the zip archive, the four lines for packaging the Windows binaries can be condensed to a single line. Let me know if this is desired please :smile: 
I am unable to verify if the changes to `delivery.yaml` are working as intended. 
Verification of archive structure:
``` shell
$ unzip skipper-73a77c9d9cc6a339022aae12f0b61d7d26e61572-windows-amd64.zip -d tmp
Archive: …
```

Update packaging procedure for Windows binaries

---

loadbalancer/algorithm.go
proxy/proxy.go

The performance of endpointregistry under circumstances of high concurenncy is the very discussable topic, it does not seem to work perfectly at the moment.

Do not use endpointregistry in the hotpath

---

.github/workflows/gh-packages.yaml
.github/workflows/master.yaml
.github/workflows/pr.yaml

fix: GH actions run an outdated Go version, trying to fix as stated in https://github.com/actions/setup-go/tree/main#check-latest-version

fix: GH actions run an outdated Go version

---

.github/workflows/master.yaml

fix: master build by dropping gosec from GH action, because of recent gosec changes
Follow up on #2681

fix: master build by dropping gosec from GH action

---

filters/scheduler/fifo_test.go
net/httptest/client.go

* separate argument tests from behaviour test
* use eskip to define filter configuration
* use TestFifo prefix for all test names

filters/scheduler: refactor fifo tests

---

docs/reference/filters.md
filters/builtin/builtin.go
filters/filters.go
filters/scheduler/fifo.go
filters/scheduler/fifo_test.go
proxy/proxy.go
scheduler/scheduler.go

feature: filter fifoWithBody that works similar to fifo(), but release deferred until body streaming to client was finished
fix: https://github.com/zalando/skipper/issues/2579
fix: we did not check context canceled before, see also https://github.com/golang/go/issues/63615

feature: filter fifoWithBody

---

cmd/webhook/admission/admission_test.go
cmd/webhook/admission/testdata/rg/rg-with-multiple-filters.json
cmd/webhook/admission/testdata/rg/rg-with-multiple-predicates.json
dataclients/kubernetes/definitions/definitions_test.go
dataclients/kubernetes/definitions/routegroups.go
dataclients/kubernetes/definitions/routegroupvalidator.go
dataclients/kubernetes/definitions/testdata/errorwrapdata/errors.log
dataclients/kubernetes/definitions/testdata/errorwrapdata/routegroups.json
dataclients/kubernetes/definitions/testdata/validation/route-with-empty-filter.log
dataclients/kubernetes/definitions/testdata/validation/route-with-empty-predicate.log
dataclients/kubernetes/definitions/testdata/validation/route-with-multiple-filters-one-item.log
dataclients/kubernetes/definitions/testdata/validation/route-with-multiple-filters-one-item.yaml
dataclients/kubernetes/definitions/testdata/validation/route-with-multiple-predicates-one-item.log
dataclients/kubernetes/definitions/testdata/validation/route-with-multiple-predicates-one-item.yaml

Related to https://github.com/zalando/skipper/issues/1618.

Prevent multiple items per yaml item

---

dataclients/kubernetes/endpointslices.go
dataclients/kubernetes/testdata/ingressV1/ingress-data/lb-target-multi-multiple-endpointslices-conditions-all-serving.eskip
dataclients/kubernetes/testdata/ingressV1/ingress-data/lb-target-multi-multiple-endpointslices-conditions-all-serving.yaml

see also https://github.com/zalando/skipper/issues/2684
added: test case for `ready: false` and `nil` cases

fix: endpointslices should not consider Serving condition

---

cmd/webhook/admission/admission_test.go

Test shouldn't be working without validator initialized or at least some of them, related to https://github.com/zalando/skipper/issues/1618.

validation webhook: Initialize validator object in tests

---

filters/tee/tee_test.go
net/redistest/redistest.go

fix: flakytest for all redistest based tests
fix: flakytest increase timeout for starting container
fix: flakytest defer close(channel) is leading to double close

fix: flakytest for all redistest based tests

---

.github/workflows/master.yaml
Makefile

migrate publish coverage report from codecov.io to coveralls.io and use GH action to do the auth

migrate publish coverage report from codecov.io to coveralls.io 

---

.github/workflows/master.yaml

update: gh action as pinned dependency as OpenSSF scorecard suggests

update: gh action as pinned dependency as OpenSSF scorecard suggests

---

delivery.yaml
mkdocs.yml

Use CDP runtime instead of deprecated overlay to build doc site.
Tested locally via:
```
docker run -it -p 8000:8000 --rm -v $PWD:/workspace pierone.stups.zalan.do/cdp-runtime/mkdocs-v9 sh -c 'pipx inject mkdocs-material markdown-include && serve-docs'
```

build: use CDP runtime to build docs

---

cmd/webhook/admission/admission_test.go
cmd/webhook/admission/testdata/rg/rg-with-invalid-backend-path.json
dataclients/kubernetes/definitions/routegroupvalidator.go
dataclients/kubernetes/definitions/testdata/errorwrapdata/errors.log
dataclients/kubernetes/definitions/testdata/errorwrapdata/routegroups.json
dataclients/kubernetes/definitions/testdata/validation/route-with-invalid-backend-with-path.log
dataclients/kubernetes/definitions/testdata/validation/route-with-invalid-backend-with-path.yaml
dataclients/kubernetes/definitions/testdata/validation/route-with-multiple-filters-one-item.log
dataclients/kubernetes/definitions/testdata/validation/route-with-multiple-predicates-one-item.log

Make sure that network backends doesn't include paths.

Validate backend path

---

docs/reference/filters.md
filters/auth/secretheader.go
filters/auth/secretheader_test.go
filters/filters.go
skipper.go

Add a filter to set request header value from secret with optional prefix and suffix.
It is similar to `bearerinjector` which is equivalent to `setRequestHeaderFromSecret("Authorization", "/tokens/my-token", "Bearer ")`
For #1952

filters/auth: add setRequestHeaderFromSecret filter

---

routesrv/eskipbytes.go
routesrv/polling.go
routesrv/routesrv_test.go

Support gzip encoding to reduce response size.

routesrv: accept gzip encoding

---

docs/reference/filters.md

docs: clarify clusterClientRatelimit empty client id logic

---

filters/tracing/statebagtotag.go
filters/tracing/statebagtotag_test.go

* reduce allocations when tag value is string
* check statebag value first to bail out early if it is absent
* restrict max number of arguments to two
```
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/filters/tracing
│   HEAD~1    │                HEAD                 │
│   sec/op    │   sec/op     vs base                │
StateBagToTag_StringValue-8   313.1n ± 2%   124.3n ± 1%  -60.29% (p=0.000 n=10)
│   HEAD~1   │                HEAD                │
│    B/op    │   B/op     vs base                 │
StateBagToTag_StringValue-8   19.00 ± 0%   0.00 ± 0%  -100.00% (p=0.000 n=10)
│   HEAD~1   │                HEAD                 │
│ allocs/op  │ allocs/op   vs base                 │
StateBagToTag_StringValue-8   2.000 ± 0%   0.000 …
```

filters/tracing: improve stateBagToTag 

---

docs/reference/filters.md
filters/builtin/builtin.go
filters/diag/tarpit.go
filters/diag/tarpit_test.go
filters/filters.go

feature: tarpit() filter to let connection to the client open until it closes the connection

feature: tarpit() filter

---

cmd/webhook/admission/admission_test.go
dataclients/kubernetes/definitions/routegroupvalidator.go
dataclients/kubernetes/definitions/testdata/errorwrapdata/errors.log
dataclients/kubernetes/definitions/testdata/validation/route-with-invalid-backend-with-path.log

Disable address validation to prevent errors for existing RouteGroups.
Reverts #2719

dataclients/kubernetes: disable network backend address validation

---

.clusterfuzzlite/Dockerfile
.clusterfuzzlite/build.sh
.clusterfuzzlite/project.yaml
.github/workflows/cflite_pr.yaml

add [clusterfuzzlite](https://google.github.io/clusterfuzzlite/) PR fuzzing.
it uses the same code as oss-fuzz but it will trigger fuzzing on every PR and it runs for 300 seconds

add clusterfuzzlite PR fuzzing.

---

dataclients/kubernetes/endpoints.go
dataclients/kubernetes/endpointslices.go
dataclients/kubernetes/kubernetestest/fixtures.go

Preallocate some obvious cases found by https://github.com/alexkohler/prealloc

dataclients/kubernetes: preallocate slices

---

routing/datasource.go
routing/testdataclient/dataclient.go

Preallocate cases (except in *_test.go) found by https://github.com/alexkohler/prealloc

routing: preallocate slices

---

filters/fadein/fadein.go
filters/fadein/fadein_test.go
loadbalancer/algorithm_test.go
loadbalancer/fadein_test.go
proxy/fadeintesting_test.go
routing/endpointregistry.go
routing/endpointregistry_test.go
skipper.go

This PR is intended to make endpointregistry component lock-free
+ use sync.Map to get entries by key
+ convert all entry fields to atomics
+ make GetMetrics method return the entry instead of copy to decrease complexity in general and number of calls to sync.Map's Load in particular
The benchmark results show that it could be slow to call `GetMetrics` too much, but if the user will find a way to reuse its return value, the performance will be much better both than current master and new version:
```
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/routing
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
│   master.txt   │     endpointregistrySyncMap.txt     │
│     sec/op     │   sec/op     vs base                │
GetInflightRequests/1_goroutines-16      163.900n ±  7%   6.977n …
```

Use sync.Map in the endpointregistry

---

routesrv/shutdown_test.go

Give more time for server to complete the shutdown before checking
endpoints availability.

routesrv: fix race in shutdown test

---

dataclients/kubernetes/clusterclient_test.go
dataclients/kubernetes/routegroup.go
dataclients/kubernetes/testdata/routegroups/convert/failing-route-groups-ignored.log
dataclients/kubernetes/testdata/routegroups/convert/missing-service-1-of-2.eskip
dataclients/kubernetes/testdata/routegroups/convert/missing-service-1-of-2.log
dataclients/kubernetes/testdata/routegroups/convert/missing-service-1-of-2.yaml
dataclients/kubernetes/testdata/routegroups/east-west-range/internal-host-error-transforming.log

Ignore routes that reference missing service.

dataclients/kubernetes: partially create RouteGroup routes on missing service

---

circuit/ratebreaker.go
circuit/registry.go
proxy/fadeintesting_test.go
secrets/certregistry/certregistry.go

refactor: sync.Mutex is fine as value object and needs no initialization

refactor: sync.Mutex is fine as value object and needs no initialization

---

filters/fadein/fadein.go
proxy/fadeintesting_test.go
routing/endpointregistry.go
routing/endpointregistry_test.go

https://github.com/zalando/skipper/pull/2795
```
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/routing
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
│ endpointregistryMinor.txt │
│          sec/op           │
GetInflightRequests/1_goroutines-16                    6.960n ±  0%
GetInflightRequests/2_goroutines-16                    3.808n ±  2%
GetInflightRequests/3_goroutines-16                    2.963n ±  4%
GetInflightRequests/4_goroutines-16                    2.499n ±  4%
GetInflightRequests/5_goroutines-16                    2.438n ±  2%
GetInflightRequests/6_goroutines-16                    2.124n ±  2%
GetInflightRequests/7_goroutines-16                    2.035n ±  3%
GetInflightRequests/8_goroutines-16                    1.897n ± 18% …
```

Fixed the remaining comments from previous endpointregistry PR

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go
filters/openpolicyagent/openpolicyagent.go
filters/openpolicyagent/openpolicyagent_test.go

**Insert config labels in opa runtime**
Without runtime config, it is not possible to determine the environment information within rego code. With this PR, non sensitive configuration are added so that they will be available with opa.runtime() built-in function.
https://github.com/open-policy-agent/opa/blob/main/plugins/plugins.go#L302 this function is used to set runtime.

Open-policy-agent: Insert config labels in opa runtime

---

filters/diag/absorb.go
proxy/teebody.go

refactor: if-else drop else part

---

docs/reference/filters.md
filters/builtin/builtin.go
filters/diag/logbody.go
filters/diag/logbody_test.go
filters/filters.go
go.mod

feature: logBody() filter to log request or response body while streaming
doc: add logBody()
fixes: https://github.com/zalando/skipper/issues/2282
first part to replace https://github.com/zalando/skipper/pull/2428

feature: logBody filter 

---

filters/fadein/fadein.go
loadbalancer/algorithm.go
net/net.go
net/net_test.go
routing/datasource.go

This change is needed for proxy to easily have normalized host and use it in endpointregistry for dynamic host-wide data to be easily fetchable.
This PR should make changes in #2823 easier.

Write normalized scheme and host to routing.Route fields

---

filters/auth/auth.go
filters/auth/oidc.go
filters/auth/tokeninfo.go
filters/auth/tokeninfo_test.go

```
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/filters/auth
│   HEAD~1    │                HEAD                 │
│   sec/op    │   sec/op     vs base                │
OAuthTokeninfoRequest/oauthTokeninfoAllScope-8   422.5n ± 4%   246.2n ± 1%  -41.74% (p=0.000 n=10)
OAuthTokeninfoRequest/oauthTokeninfoAnyScope-8   413.5n ± 4%   251.5n ± 0%  -39.19% (p=0.000 n=10)
geomean                                          418.0n        248.8n       -40.48%
│   HEAD~1   │                 HEAD                  │
│    B/op    │   B/op    vs base                     │
OAuthTokeninfoRequest/oauthTokeninfoAllScope-8   112.0 ± 0%   0.0 ± 0%  -100.00% (p=0.000 n=10)
OAuthTokeninfoRequest/oauthTokeninfoAnyScope-8   112.0 ± 0%   0.0 ± 0%  -100.00% …
```

filters/auth: reduce allocations for tokeninfo scope and claims checks

---

docs/reference/filters.md

PR #1923 added SubdomainsToRemove which is applicable to all three OIDC filters: oauthOidcUserInfo, oauthOidcAnyClaims and oauthOidcAllClaims.

docs: document SubdomainsToRemove parameter for other two OIDC filters

---

routing/endpointregistry.go

EndpointRegistry.GetMetrics always allocates new entry even when data for the key already exists.
sync.Map does not provide lazy initialization for the new value, see https://github.com/golang/go/issues/44159
This change uses suggested best-effort to avoid allocating a new value on each load.
Follow up on #2795

routing: avoid allocating new entry in EndpointRegistry.GetMetrics

---

eskip/eskip_test.go

Add test cases from #2755 discovered by fuzzing.

eskip: add comment test cases for ParsePredicates

---

.github/workflows/codeql-analysis.yml

Codeql complains about go version being older that the one defined in `go.mod`, this is to address the issue

fix codeql error

---

dataclients/kubernetes/clusterclient_test.go
dataclients/kubernetes/routegroup.go
dataclients/kubernetes/testdata/routegroups/convert/failing-route-groups-ignored.log
dataclients/kubernetes/testdata/routegroups/convert/missing-service-1-of-2.log
dataclients/kubernetes/testdata/routegroups/east-west-range/internal-host-error-transforming.log

Do not log ignored route index to avoid logs bloat. The error message should be enough to figure out which routes were ignored. RouteGroup logger logs message without index only once per routegroup (see #2637).
Followup on #2796

dataclients/kubernetes: do not log route index

---

filters/diag/logbody.go
filters/diag/logbody_test.go

fixes the `logBody()` filter for handling unprintable chars correctly (by escaping them).
before:
```bash
$ ./bin/skipper -inline-routes='* -> flowId("reuse") -> logBody("request", 1024) -> inlineContent("ok") -> <shunt>'
[APP]INFO[0001] logBody("request") lol       
$ curl 127.0.0.1:9090 -d $'\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08lol      ' -H"X-Flow-Id: 11111111"
ok
```
after:
```bash
$ ./bin/skipper -inline-routes='* -> flowId("reuse") -> logBody("request", 1024) -> inlineContent("ok") -> <shunt>'
[APP]INFO[0001] logBody("request") 11111111: "\b\b\b\b\b\b\b\b\b\blol      "
$ curl 127.0.0.1:9090 -d $'\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08lol      ' -H"X-Flow-Id: 11111111"
ok
```
**Note:** `logHeader()` is not affected since it http server send 400 error when a header has unprintable …

fix logBody to escape unprintable chars.

---

loadbalancer/fadein_test.go

+ added tests for powerOfNRandomChoices monotony
+ added tests for case when all endpoints are new
+ added tests (obviously failing at the moment) for powerOfNRandomChoices to check new and old enpoints receive correct amount of requests

Improve fadeIn CI tests

---

eskip/eskip.go
eskip/eskip_test.go
eskip/lexer.go

* do not use fmt.Sprintf in ParseFilters and ParsePredicates
* avoid allocations for fixed tokens
* optimize scanWhile loop
* add scanEscaped fast path
* optimize scanRegexp and scanEscaped using strings.Builder
* optimize scanWhitespace
* optimize selectScanner using switch
```
goos: linux
goarch: amd64
│   HEAD~1    │                HEAD                 │
│   sec/op    │   sec/op     vs base                │
ParsePredicates-8   29.88µ ± 3%   11.33µ ± 2%  -62.09% (p=0.000 n=10)
│     B/op     │     B/op      vs base                │
ParsePredicates-8   4.863Ki ± 0%   2.008Ki ± 0%  -58.71% (p=0.000 n=10)
│   HEAD~1    │                HEAD …
```

eskip: improve lexer performance

---

.gitignore
eskip/eskip_test.go
eskip/lexer.go

* use plain ascii instead of unicode package
* use loop for scanSymbol
* call scan functions directly instead of selectScanner to aid inlining
```
goos: linux
goarch: amd64
│    HEAD~1    │                HEAD                 │
│    sec/op    │   sec/op     vs base                │
ParsePredicates-8   9.637µ ± 11%   8.894µ ± 4%   -7.71% (p=0.001 n=10)
Parse-8             329.1m ±  4%   272.7m ± 2%  -17.15% (p=0.000 n=10)
geomean             1.781m         1.557m       -12.56%
│    HEAD~1    │                HEAD                 │
│     B/op     │     B/op      vs base               │
ParsePredicates-8   2.008Ki ± 0%   2.008Ki ± 0%       ~ (p=1.000 n=10)
Parse-8             49.94Mi ± 0%   49.94Mi ± 0%       ~ (p=0.926 n=10)
geomean             320.4Ki …
```

eskip: improve lexer performance 2

---

skptesting/benchmark-proxy.sh
skptesting/benchmark.inc

feature: choose benchmark binary to test local modifications

feature: choose benchmark binary to test local modifications

---

eskip/eskip.go
eskip/parser.go
eskip/parser.y
eskip/parser_test.go

They are equivalent and using predicate reduces unnecessary copying. This is also consistent with parsing filters straight into `[]*Filter`.
```
goos: linux
goarch: amd64
│   HEAD~1    │                HEAD                │
│   sec/op    │   sec/op     vs base               │
ParsePredicates-8   9.192µ ± 2%   8.788µ ± 3%  -4.40% (p=0.007 n=10)
Parse-8             273.1m ± 2%   260.6m ± 2%  -4.58% (p=0.000 n=10)
geomean             1.585m        1.513m       -4.49%
│    HEAD~1    │                HEAD                 │
│     B/op     │     B/op      vs base               │
ParsePredicates-8   2.008Ki ± 0%   1.961Ki ± 0%  -2.33% (p=0.000 n=10)
Parse-8             49.94Mi ± 0%   49.02Mi ± 0%  -1.83% (p=0.000 n=10)
geomean             320.4Ki …
```

eskip: use Predicate instead of matcher

---

eskip/eskip_test.go

Check value of error message to simplify followup fixes.
E.g. #1885 introduced last route id to the error message without tests but last route could be empty or should not be present at all for `ParsePredicates` and `ParseFilters`.

eskip: refactor parsing tests to check error message

---

eskip/eskip_test.go
eskip/json_test.go

Add a benchmark of unmarshalling 10000 routes from JSON and compare its performance to eskip parsing.
This establishes a baseline for future optimizations.
```
$ benchstat -col .name <(go test ./eskip -run=NONE -bench='BenchmarkJsonUnmarshal|BenchmarkParse$' -count=10)
goos: linux
goarch: amd64
│    Parse    │             JsonUnmarshal              │
│   sec/op    │    sec/op      vs base                 │
*-8   247.1m ± 1%   1281.4m ± 16%  +418.51% (p=0.000 n=10)
│    Parse     │            JsonUnmarshal            │
│     B/op     │     B/op      vs base               │
*-8   49.02Mi ± 0%   46.54Mi ± 0%  -5.06% (p=0.000 n=10)
│    Parse    │            JsonUnmarshal            │
│  allocs/op  │  allocs/op   vs base                │
*-8   1.080M ± 0% …
```

eskip: add BenchmarkJsonUnmarshal

---

cmd/webhook/admission/admission_test.go
dataclients/kubernetes/definitions/routegroupvalidator.go
dataclients/kubernetes/definitions/testdata/errorwrapdata/errors.log
dataclients/kubernetes/definitions/testdata/validation/route-with-invalid-backend-with-path.log

Revert "dataclients/kubernetes: disable network backend address validation (#2780)"
This reverts commit 4502bb6c445fb81c551e6c44c2a9b46b8099803e.

dataclients/kubernetes: enable network backend address validation

---

eskip/eskip_test.go
eskip/gob_test.go

```
$ benchstat -col .name <(go test ./eskip -run=NONE -bench='BenchmarkGobUnmarshal|BenchmarkParse$' -count=10)
goos: linux
goarch: amd64
│    Parse    │            GobUnmarshal            │
│   sec/op    │   sec/op     vs base               │
*-8   238.8m ± 1%   227.9m ± 1%  -4.57% (p=0.000 n=10)
│    Parse     │            GobUnmarshal             │
│   bytes/op   │   bytes/op    vs base               │
*-8   15.99Mi ± 0%   17.05Mi ± 0%  +6.62% (p=0.000 n=10)
│    Parse     │             GobUnmarshal             │
│     B/op     │     B/op      vs base                │
*-8   49.02Mi ± 0%   70.53Mi ± 0%  +43.88% (p=0.000 n=10)
│    Parse    │            GobUnmarshal            │
│  allocs/op  │ …
```

eskip: add gob unmarshal benchmark

---

docs/reference/plugins.md
packaging/Makefile
skptesting/run_fadein_test.sh

Remove GO111MODULE env variable which is required only for Go 1.11

---

readme.md

doc: skipper version promise as we did informal in the past
we had a public poll in https://app.slack.com/client/T029RQSE6/C82Q5JNH5 and the common practice seems fine, but we also got useful input by @xavivars which we consider useful for our future practice.

doc: skipper version promise as we did informal in the past

---

dataclients/kubernetes/definitions/ingressvalidator.go

Relates to https://github.com/zalando/skipper/pull/2753
Disabling duplicate hostname for ingress can have other side effects since we can have duplicate hostname but for different service/path.

Remove duplicate hostname from ingressValidator

---

dataclients/kubernetes/clusterclient.go
dataclients/kubernetes/ingress.go
dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-invalid-routes-annotation-missing-header-argument.log
dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-invalid-routes-annotation-missing-header-argument.yaml

Relates to https://github.com/zalando/skipper/issues/1618
IngressValidator was introduced in https://github.com/zalando/skipper/pull/2493 while we still validate inside skipper with some functions that will only drop the annotation but Ingress will still pass and work for example https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/ingress.go#L257C1-L269C2 which will drop the annotation only if parsing fail.
This PR should fix this and at least drop the Ingress resource if validation for skipper annotations fail.

validator: use ingress validator with dataclient

---

proxy/fadein.go

This function is called from hotpath, and it is possible not to call GetMetrics() which calls sync.Map.Load(). This will increase performance of the hotpath.

Avoid calling EndpointRegistry.GetMetrics() in filterFadeIn

---

loadbalancer/algorithm_test.go
proxy/fadein.go
proxy/fadein_internal_test.go
proxy/proxy.go
routing/routing.go

Some minor changes after https://github.com/zalando/skipper/pull/2634 just to make code a little bit more readable.

minor: refactor fadeIn code

---

eskip/lexer.go

Create a copy of string token value in lexer
to avoid referencing input data array.
The string value becomes a filter or predicate argument or an endpoint value. Using such value as a long-living cache key may create a memory leak.
```
goos: linux
goarch: amd64
│   HEAD~1    │                HEAD                │
│   sec/op    │   sec/op     vs base               │
ParsePredicates-8   7.656µ ± 6%   8.281µ ± 3%  +8.16% (p=0.002 n=10)
Parse-8             241.0m ± 1%   252.9m ± 6%  +4.96% (p=0.000 n=10)
geomean             1.358m        1.447m       +6.55%
│     B/op     │     B/op      vs base                │
ParsePredicates-8   1.961Ki ± 0%   2.352Ki …
```

eskip: copy string token value

---

eskip/lexer.go

Create a copy of symbol token value in lexer
to avoid referencing input data array.
The symbol value becomes a filter or predicate name or a route id value. Using such value as a long-living cache key may create a memory leak.
```
goos: linux
goarch: amd64
│    sec/op    │    sec/op     vs base                │
ParsePredicates-8   17.07µ ±  3%   18.80µ ± 18%  +10.17% (p=0.000 n=10)
Parse-8             538.9m ± 19%   545.5m ± 21%        ~ (p=0.631 n=10)
geomean             3.033m         3.203m         +5.60%
│    HEAD~1    │                HEAD                 │
│     B/op     │     B/op      vs base               │
ParsePredicates-8   2.352Ki ± 0% …
```

eskip: copy symbol token value

---

docs/reference/filters.md
filters/builtin/builtin.go
filters/builtin/comment.go
filters/filters.go
skipper.go

One example use case is to use it in more complex objects like RouteGroups and have something that is shown also on kubectl edit rg case

feature: comment() filter to comment a given filter chain.

---

cmd/webhook/admission/admission.go
proxy/longpoll_test.go

This fixes `go vet` issues discovered in Go 1.22: https://go.dev/doc/go1.22
```
cmd/webhook/admission/admission.go:123:61: call to time.Since is not deferred
proxy/longpoll_test.go:122:2: the cancel function is not used on all paths (possible context leak)
proxy/longpoll_test.go:125:3: this return statement may be reached without using the cancel var defined on line 122
```

Address vet issues found in Go 1.22

---

.github/workflows/master.yaml

Reverts zalando/skipper#2908
https://github.com/google/capslock/issues/87 was fixed and tested locally.

Revert "build: fix go1.22 issue with capslock"

---

filters/auth/oidc.go

Removed subdomains should share the cookie with the corresponding hostname if all other parameters are the same
e.g. foo.bar.baz (with `SubdomainsToRemove` = 1) and bar.baz (with `SubdomainsToRemove` = 0) should share the same OIDC cookie to prevent duplication. Currently this parameter is taken into account for cookie hashing which leads to multiple cookies.
See also d1457a3c7de06f72c614ce194d7cdd0eb6925ccb

feat: deduplicate OIDC cookies for subdomains

---

routesrv/polling.go

`routesrv` may be configured to produce no routes,
e.g. to only serve Redis endpoints from the namespace without
Ingresses/RouteGroups:
```sh
bin/routesrv \
-enable-kubernetes-endpointslices \
-kubernetes-namespace=my-redis-ns \
-kubernetes-redis-service-namespace=my-redis-ns \
-kubernetes-redis-service-name=my-redis \
-kubernetes-https-redirect=false \
-kubernetes-healthcheck=false \
...
```
For #2476

routesrv: do not log empty routes as error

---

docs/reference/filters.md
filters/builtin/builtin.go
filters/filters.go
filters/tls/pass_client.go
filters/tls/pass_client_test.go

https://github.com/zalando/skipper/issues/1780#issuecomment-1926971779 showed interest in a filter that passes TLS client cert from the request to the proxy as header to the backend similar to a traefik feature. I trimmed it down to pem only support, but I think it's the one that is interesting without too much configuration.
Cc @containerpope

Feature: tlsPassClientCertificates filter

---

cmd/webhook/admission/admission_test.go
config/config_test.go
dataclients/kubernetes/testdata/routegroups/convert/failing-filter.log
dataclients/kubernetes/testdata/routegroups/convert/no-catchall-for-failed-route-group.log
eskip/eskip.go
eskip/eskip_test.go
eskip/lexer.go
eskip/parser.go
eskip/parser.y
eskip/parser_test.go

Introduce start tokens to allow separate parsing of
eskip document, predicates and filters, see
https://www.gnu.org/software/bison/manual/html_node/Multiple-start_002dsymbols.html
Also remove `stringval` and `regexpval` rules.
These rules are aliases for `stringliteral` which can be used directly.
This reduces parser stack depth and item size.
The change fixes parse error position value and speeds up predicates/filters parsing.
```
goos: linux
goarch: amd64
│   HEAD~1    │                HEAD                 │
│   sec/op    │   sec/op     vs base                │
ParsePredicates-8   8.531µ ± 2%   7.464µ ± 5%  -12.51% (p=0.000 n=10)
Parse-8             257.3m ± 1%   251.4m ± 2%   -2.32% (p=0.000 n=10) …
```

eskip: separate parsing of predicates and filters

---

net/redistest/redistest.go

https://raw.githubusercontent.com/redis/redis/7.2/00-RELEASENOTES

net: use redis 7

---

net/redisclient_test.go

Add delay before checking updater calls after close.
Followup on #2177

net: fix flaky TestRedisClient

---

net/redistest/network.go
net/redistest/redistest.go
redis_test.go

Containers on test network will use the same port and different addresses unlike containers on the host network, which use different ports and the same loopback address.

net/redistest: run redis containers on test network

---

.github/workflows/master.yaml
.github/workflows/pr.yaml

Disable reaper container for github builds.
This should hopefully eliminate testcontainer-related test flakes.
See https://golang.testcontainers.org/features/garbage_collector/#ryuk
Updates #2668
Updates #2621
Updates #2556

github: disable testcontainers Ryuk

---

delivery.yaml

Disable reaper container for CDP builds.
This should hopefully eliminate testcontainer-related test flakes.
See https://golang.testcontainers.org/features/garbage_collector/#ryuk and previous #2930
Updates #2668
Updates #2621
Updates #2556

cdp: disable testcontainers Ryuk

---

delivery.yaml

`build-docs` deploys documentation so no additional step is necessary
Followup on #2736

build: remove outdated docs hint

---

dataclients/kubernetes/client_test.go
dataclients/kubernetes/kube_test.go

TestGetEndpointAddresses was broken because it used shared TestAPI instance and did not re-initialize it for each test.
In partucular "Ingress with endpointslices" was actually testing endpoints and not endpointslices (testAPI.ServeHTTP does not even serve endpointslices).
This change refactors GetEndpointAddresses test
using kubernetestest.NewAPI and existing fixture files.
For #2476

dataclients/kubernetes: refactor GetEndpointAddresses test

---

dataclients/kubernetes/kubernetestest/api.go
dataclients/kubernetes/kubernetestest/api_test.go

This is useful for testing getting endpoints by service name.
For #2476

dataclients/kubernetes/kubernetestest: support getting resource by name

---

proxy/healthy_endpoints_test.go

There are three tests with the similar idea:
1) send a lot of requests
2) check for failure rate to be as expected
3) let endpointregistry update stats related to PHC
4) send a lot of requests
5) check for failure rate to be as expected after stats update
The cases are:
+ single healthy endpoint
+ multiple healthy endpoints
+ multiple healthy + single unhealthy endpoint
Splitted from https://github.com/zalando/skipper/pull/2888 to reduce amount of code merged in the single time.

Created mock tests for ongoing Passive Health Check feature

---

config/config.go
config/config_test.go
docs/reference/filters.md
filters/filters.go
filters/openpolicyagent/evaluation.go
filters/openpolicyagent/internal/envoy/envoyplugin.go
filters/openpolicyagent/internal/envoy/skipperadapter.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go
filters/openpolicyagent/openpolicyagent.go
filters/openpolicyagent/openpolicyagent_test.go
filters/openpolicyagent/response.go
skipper.go

This PR adds the ability to use the request's body in authorisation decisions with Open Policy Agent. 
It supports the OPA Envoy plugin behaviour and only parses the body up to a configurable maximum size and otherwise tees the request body. This is to avoid parsing large bodies and create memory and performance issues inside Skipper. 
Disabling body parsing can be configured via the Open Policy Agent configuration file. It supports the same content types that the upstream OPA plugin supports: `application/json` and `multipart/form-data`. 
To make negative impact on latency or memory consumption measurable, two new filter names are introduced that capture the intent to use the body. The implementation is also smart in the sense that it will check if the policy actually uses the body on …

OPA: authorization based on request body

---

skipper.go

PR #2518 introduced a variable re-declaration that effectively renders the Open Policy Agent filters useless when used in standalone mode (this does not apply to use as a go library).

Fix Open Policy Agent filter in standalone use

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go

This PR adds basic benchmarks for the OPA filters
BenchmarkAuthorizeRequest/authorize-request-minimal-8         	   45476	     22514 ns/op	   20789 B/op	     388 allocs/op 
BenchmarkAuthorizeRequest/authorize-request-jwt-validation-8  	    5868	    195705 ns/op	   55493 B/op	     864 allocs/op

Go Benchmark for OPA filters

---

docs/reference/filters.md

Add missing quote and fix invalid id (dash is not allowed).
Follow up on #1454

docs/reference/filters: fix teeLoopback example

---

net/redisclient.go
net/redisclient_test.go

Fix use of logger before initialization.
Followup on #2261

net/redisclient: fix nil pointer dereference

---

go.mod
go.sum
net/redistest/redistest.go
net/redistest/redistest_test.go

Update https://github.com/redis/go-redis/releases/tag/v9.5.0 broke support of redis:6
Unfortunately we did not catch it because we updated test redis to redis:7 recently, see #2895
This change adds test to verify client supports both redis:6 and redis:7
The issue seems to be https://github.com/redis/go-redis/pull/2915

net/redistest: update go-redis client to work with redis:6

---

filters/builtin/stripquery.go
filters/builtin/stripquery_test.go

This is continuation of https://github.com/zalando/skipper/pull/2918/files
I have discovered that for certain cases string builder performs better than buffer, which is usually a go-to option for Go Developers. String builder was introduced in 1.10+ Go.
results (also attached to last commit message)
```
pkg: github.com/zalando/skipper/filters/builtin
│   HEAD~1    │                HEAD                │
│   sec/op    │   sec/op     vs base               │
Sanitize-8   802.1n ± 0%   748.3n ± 0%  -6.71% (p=0.000 n=10)
│   HEAD~1   │                HEAD                │
│    B/op    │    B/op     vs base                │
Sanitize-8   472.0 ± 0%   192.0 ± 0%  -59.32% (p=0.000 n=10)
│   HEAD~1   │               HEAD                │
│ allocs/op  │ allocs/op   vs base               │
Sanitize-8 …
```

filters/builtin: minor performance optimization for sanitize in StripQuery Filter

---

cmd/skipper/main.go

When skipper is installed via `go install` it has empty version and commit values:
```
~$ go install github.com/zalando/skipper/cmd/skipper@latest
go: downloading github.com/zalando/skipper v0.21.2
~$ skipper -version
Skipper version  (commit: , runtime: go1.22.0)
```
Current build process of binaries specifies version and commit via `-ldflags`.
This change uses debug buildinfo to get version and commit if they are not specified by `-ldflags` which is compatible with the current build process but should also work for `go install` case.
If this change fixes `go install` case (which can only be tested after package version is published) then we can add the same snippet to other binaries and get rid of COMMIT_HASH ldflag.
We can not get rid of `-ldflags` fully though because `go build` does …

cmd/skipper: fix version and commit for go install

---

config/config.go
docs/operation/operation.md
filters/fadein/fadein_test.go
loadbalancer/algorithm_test.go
metricsinit_test.go
proxy/fadein_internal_test.go
proxy/healthy_endpoints.go
proxy/healthy_endpoints_test.go
proxy/proxy.go
proxy/proxy_test.go
proxy/proxytest/proxytest.go
redis_test.go
routing/endpointregistry.go
routing/endpointregistry_test.go
skipper.go
skipper_test.go

There is huge ongoing effort to enable Passive Health Checks is Skipper to check backends for errors and try not to send requests to the backends that tend to fail the requests.
The initial idea I have at the moment is the following:
+ leverage the endpointregistry component (https://github.com/zalando/skipper/pull/2535) developed recently to collect more data about endpoints (total amount of reqs sent to the endpoint, amount of reqs that were timed out because of backend outage)
+ if ratio of requests that were timed out is too high for particular endpoint, then send lower amount of requests to this endpoint, the decrease of RPS is configurable
+ once in a while (once in `statsResetPeriod`) update the stats to check endpoints' states change

Passive health checks

---

cmd/skipper/main.go

Binary installed via `go install github.com/zalando/skipper/cmd/skipper@latest` does not contain `vcs.revision`, see https://github.com/golang/go/issues/65904
Followup on #2954

cmd/skipper: do not show empty commit

---

dataclients/kubernetes/ingress.go

The name could be a little bit misleading because actually this function calculates the number of Path{,Subtree} predicates in the single route. Nobody calculates the number of routes here, there is only one route which this function takes as input.
Therefore n variable corresponds to the number of predicates, not the routes how it seems to be when taking a look at the code.

minor: countPathRoutes function

---

go.mod
go.sum

Fixes https://pkg.go.dev/vuln/GO-2024-2611
See https://github.com/protocolbuffers/protobuf-go/compare/v1.32.0...v1.33.0

deps: update google.golang.org/protobuf to v1.33.0

---

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml

See changes
* https://github.com/szuecs/routegroup-client/pull/31
* https://github.com/szuecs/routegroup-client/pull/32
It restores a link to the origin removed by #2814
to make it clear that CRD is the copy.

crd: update RouteGroup CRD

---

filters/openpolicyagent/openpolicyagent_test.go
go.mod
go.sum

Use google.golang.org/protobuf to avoid direct dependency on github.com/golang/protobuf (which is still imported indirectly):
```
$ go mod why -m github.com/golang/protobuf
github.com/zalando/skipper/filters/openpolicyagent
github.com/envoyproxy/go-control-plane/envoy/config/core/v3
github.com/golang/protobuf/ptypes/any
```

filters/openpolicyagent: use google.golang.org/protobuf

---

loadbalancer/algorithm.go
proxy/healthy_endpoints_test.go

`consistentHash` is the only load balancer algorighm which uses index of original endpoints list, that is why `ctx.Route.LBEndpoints` (original list) should be used there instead of `ctx.LBEndpoints` (list with filtered endpoints).

Fix (*consistentHash).Apply

---

proxy/healthy_endpoints_test.go

Refactor healthy_endpoints_test.go

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go

Address #2962
Integration tests for OPA seem to re-use the port of a `httptest` server, i.e. requests from one test reach the server of another.

Fix flaky OPA tests

---

docs/reference/scripts.md
script/script.go
script/script_test.go

script: allow storing lua tables into state bag

---

go.mod
go.sum

update golang.org/x/net to fix osv-scanner finding

update golang.org/x/net to fix osv-scanner finding

---

filters/auth/oidc_test.go
go.mod
go.sum

https://github.com/square/go-jose was archived in favor of https://github.com/go-jose/go-jose, so dependency change makes sense

fix: vulnerable dependency go-jose

---

docs/reference/scripts.md
script/script.go
script/script_test.go
script/testdata/log_header.lua

Introduce `add` and `values` methods to set and get multiple header values.

script: support multiple header values

---

filters/auth/oidc.go
go.mod
go.sum

update: vulnerability in transitive dependency github.com/coreos/go-oidc found

update: vulnerability in transitive dependency oidc filters

---

filters/auth/grant.go
filters/auth/grantcallback.go
filters/auth/grantconfig.go
filters/auth/grantcookie.go
filters/auth/grantcookie_test.go
filters/auth/grantlogout.go
skipper.go

Add CookerEncoder interface to allow custom implementation of grant cookie encoding.
For example custom implementation may store token value in some permanent key-value storage and encode key into the cookie.
Another implementation may encode token value into multiple cookies.

filters/auth: add grant cookie encoder

---

docs/reference/filters.md
filters/builtin/annotate.go
filters/builtin/annotate_test.go
filters/builtin/builtin.go
filters/filters.go

Add `annotate` filter to annotate routes and a helper to retrieve annotations.

filters/builtin: add annotate filter

---

docs/reference/filters.md
filters/auth/jwt_metrics.go
filters/auth/jwt_metrics_test.go
filters/filters.go
skipper.go

Add jwtMetrics filter that parses JWT token and increments a set of counters,
see documentation for details.

filters/auth: add jwtMetrics

---

docs/reference/filters.md
filters/auth/grant.go
filters/auth/grant_test.go

For single page applications user may want to return javascript stub that stores location hash into localstorage and then redirects user to the authorization url.

filters/auth: add login redirect stub support

---

proxy/metrics_test.go
proxy/proxy.go
skipper.go

Use configed metrics and fallback to global for backwards compatibility.
Updates #3026

proxy: support configurable metrics

---

docs/reference/filters.md
filters/auth/jwt_metrics.go
filters/auth/jwt_metrics_test.go

Extend configuration of `jwtMetrics` (#3020) to support opt-out - disable metrics collection when any of the configured route annotations (#3022) is present.
This can be used to collect data about missing/invalid JWT tokens per hostname in multitenant ingress setup.
Add `jwtMetrics` filter to all routes using `-default-filters-append` flag and allow users to annotate routes that do not require JWT token.

filters/auth: implement opt-out support for jwtMetrics

---

proxy/healthy_endpoints.go
proxy/proxy.go
routing/endpointregistry.go

Added PHC-related logs

---

filters/openpolicyagent/evaluation.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go
filters/openpolicyagent/openpolicyagent.go
filters/openpolicyagent/tracing.go
filters/openpolicyagent/tracing_test.go
skipper.go

For the Open Policy Agent filters, tracing information is currently mainly added for the evaluation path of the filters. This is useful for monitoring everything that is related to requests passing through Skipper.
The PR adds tracing for asynchronous http calls that happen during discovery, bundle download, status updates and decision uppload. This allows to monitor how the OPA instances interact with their control plane.

OPA: Add tracing for outbound http calls

---

filters/openpolicyagent/tracing.go
filters/shedder/admission.go
net/httpclient.go
proxy/proxy.go
ratelimit/leakybucket.go
ratelimit/redis.go
tracing/tracingtest/testtracer.go

OpenTelemetry-OpenTracing bridge span kind can not be changed after creation, see https://github.com/open-telemetry/opentelemetry-go/issues/3953
The workaround is to specify span kind on creation which works for both Open Tracing and Open Telemetry bridge spans.
For #2104

Specify tracing span kind on creation

---

config/config_test.go
config/testdata/test.yaml

Make `defaultConfig` return configuration equal to one created from default flags and modified by a helper function for defining expected test case values.

config: refactor test defaultConfig

---

filters/filters.go
filters/openpolicyagent/openpolicyagent.go
proxy/context.go

Deprecate OpenTracing FilterContext getters and remove their usage from filters.
For #2104

filters: deprecate OpenTracing in FilterContext

---

proxy/healthy_endpoints.go

Logging every request produces too many log lines.
However, we can still keep the logs of stats updater https://github.com/zalando/skipper/blob/v0.21.65/routing/endpointregistry.go#L172 because their amount does not depend on requests count.

Change condition of PHC to reduce amount of produced logs 

---

filters/filters.go

The ParentSpan is not a proxy span but either ingress span of "filters" span when enabled.
Follow up on #3044

filters: update godoc for deprecated FilterContext OpenTracing fields

---

docs/reference/filters.md
filters/auth/jwt_metrics.go
filters/auth/jwt_metrics_test.go

Allow opt-out via state bag key.
The usecase is to opt-out metrics collection for routes that use `oauthTokeninfo*` and `oauthGrant` filters.

filters/auth: extend jwtMetrics opt-out options

---

config/yamlflag.go
config/yamlflag_test.go

YAML flag parses (preferably flow-style) YAML value from the command line or unmarshals object yaml value from the yaml config file.
Example value:
```
bin/skipper -foo-flag='{foo: hello, bar: [world, "1"], baz: 2, qux: {baz: 3}}'
```
and equivalent branch in config yaml:
```yaml
foo-flag:
foo: hello
bar:
- world
- "1"
baz: 2
qux:
baz: 3
```
This will be useful for #2104
It is also a better alternative to manual parsing of micro-syntax like e.g. implemented in #2888

config: add yaml flag

---

eskip/eskip.go
etcd/etcd.go

eskip package is generally useful without proxy or filters and therefore ideally should have minimal number of dependencies.
This change deprecates GenerateIfNeeded which is only used by etcd dataclient and reimplements it to remove dependency on github.com/zalando/skipper/filters/flowid
See 35ba6cc76dee89a57cc7869e79824bd9fc56e750

eskip: remove flowid dependency

---

docs/operation/operation.md
proxy/healthy_endpoints.go
proxy/healthy_endpoints_test.go

related to https://github.com/zalando/skipper/pull/3035
depends on https://github.com/zalando/skipper/pull/3058

phc: add new metric to counter number of unique requests mitigated

---

filters/auth/jwt_metrics.go
filters/auth/jwt_metrics_test.go

Add tracing tag for requests with problematic JWT tokens.

filters/auth: add tracing tag for jwtMetrics

---

config/defaultfilterflags.go
config/defaultfilterflags_test.go

This is useful for templated configurations that conditionally add various default filters.

config: support multiple default filters flag values

---

config/config.go
metrics/metrics.go
metrics/prometheus.go
metrics/prometheus_test.go
skipper.go

Add start label to each counter with the value of counter creation timestamp as unix nanoseconds.
This enables OpenTelemetry cumulative temporality, see https://opentelemetry.io/docs/specs/otel/metrics/data-model/#temporality
Example:
```
~$ curl -s localhost:9911/metrics | grep host_count
skipper_serve_host_count{code="200",host="bar_test",method="GET",start="1717066533598500794"} 1
skipper_serve_host_count{code="200",host="foo_test",method="GET",start="1717066538031805059"} 2
```
Fixes #3087

metrics: add start label for prometheus counters

---

filters/openpolicyagent/evaluation.go
filters/openpolicyagent/internal/envoy/skipperadapter.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go

Currently the Open Policy Agent filters send decision logs with an error to the control plane if the http path is invalid UTF-8 or if the evaluation is cancelled (the client closes the connection before the evaluation finishes). 
This disguises real errors and leads to a non-zero baseline of decision errors in the control plane. 
This PR pre-validates if paths are valid UTF-8 and do not send decisions for cancelled evalutations to the control plane.

Reduce errors in decision logs that are operational

---

packaging/Makefile

Add -trimpath flag to remove filesystem paths and make stacktraces shorter, see https://pkg.go.dev/cmd/go

build: trim path

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest.go

This PR brings the information on the span for the `opaAuthorizeRequest*` filters to the same level as the metrics by including the decision's result if it is available under the `opa.decision.allowed` tag. 
This allows to pull similar metrics from the traces as directly from the Skipper instances.

OPA: Add decision outcome to span

---

routing/datasource.go
routing/routing.go

Add and log route update counter to observe delay between receiving and applying routes.

routing: log route update id

---

routing/datasource.go
routing/routing.go

* add route update latency metric - the time it takes to apply routes update after receival.
* remove redundant setting of `created` location to UTC - its value is only exposed via Unix() which is always in UTC.

routing: measure route update latency

---

filters/openpolicyagent/tracing.go
filters/openpolicyagent/tracing_test.go

The current span for control plane requests of the Open Policy Agent based filters does not include the actual response from the control plane. 
Apart from hard network errors this makes it hard to pinpoint authN / authZ failures or intermittent unavailability (5xx status) of the control plane. 
This PR both adds the control plane responses' http status code to the spans and also flags them as erroneous for all status with a value of 4xx or 5xx.

OPA: Add response status to control plane traces

---

metrics/all_kind.go
metrics/codahale.go
metrics/codahale_test.go
metrics/metrics.go
metrics/metricstest/metricsmock.go
metrics/prometheus.go
routing/datasource.go
routing/datasource_test.go
routing/host_test.go
routing/matcher_test.go

Add `MeasureFilterCreate` method to `Metrics` interface similar to existing `MeasureFilterRequest` and `MeasureFilterResponse`.
The alternative would be to use `MeasureSince` but then filter name would have to be embedded into metric key.

routing: measure CreateFilter latency

---

config/defaultfilterflags.go
config/defaultfilterflags_test.go

Do not store values that contaion no filters,
e.g. empty strings or eskip comments only.
Follow up on #3084

config: fix defaultFiltersFlags.String

---

config/defaultfilterflags_test.go

Fix yaml input to verify empty filters are ignored.
Follow up on #3127

config: fix defaultFiltersFlags yaml test case

---

docs/reference/filters.md
filters/auth/auth.go
filters/auth/tokeninfo.go
filters/auth/tokeninfo_test.go
filters/filters.go
skipper.go

The `oauthTokeninfoValidate` filter obtains token info and allows request if there was no error otherwise it responds with
`401 Unauthorized` status and configured response body.
It does nothing if any preceding filter already validated the token or if route is annotated with configured annotations.
It is useful as a default filter to ensure each request has a valid token.
Since its logic is diffrent from existing oauthTokeninfo* filters it is implemented as a separate filter type.

filters/auth: add token validator filter

---

metrics/prometheus.go
metrics/prometheus_test.go

metrics: register skipper_filter_create_duration_seconds

---

config/config.go
config/config_test.go
skipper.go
skipper_test.go

Golang maintains a list of cipher suites considered insecure, which are still allowed if requested. This flag will allow those cipher suites to be completely excluded.
Options considered:
**Use a list of allowed cipher suites**
This may need some maintenance over time as cipher suites are updated, introduced or deprecated. 
**Exclude used cipher suites based on name**
Less maintenance overhead than maintaining desired list of cipher suites, excluding the ones not desired would also require some maintenance overtime as cipher suites are considered insecure.
**Exclude known insecure cipher suites** 
Using golang's list of [InsecureCipherSuites](https://pkg.go.dev/crypto/tls#InsecureCipherSuites) reducing maintenance overhead by allowing list to be maintained by golang.
Fixes …

cmd/skipper: allow exclusion of insecure cipher suites

---

metrics/prometheus.go

Register prometheus metrics right after creation
to reduce likelihood of missing registration.
Follow up on #3129

metrics: refactor prometheus metric registration

---

mkdocs.yml

ref: https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/ was introduced by a0fa5d8e99117d5a43b84c4948cf819c16715efe "enable math rendering" (#2041)

fix: remove polyfill.io js

---

docs/kubernetes/ingress-backends.md

you can also use the newer lifecycle hook target "sleep" to let kubelet sleep for you, so no need to have a binary inside your container

docs: running as ingress backend

---

net/httpclient.go
net/httpclient_example_test.go
net/httpclient_test.go

feature: net.Transport got beforeSend and afterResponse hooks that a user can set via net.Options 
```go
// BeforeSend is a hook function that runs just before executing RoundTrip(*http.Request)
BeforeSend func(*http.Request)
// AfterResponse is a hook function that runs just after executing RoundTrip(*http.Request)
AfterResponse func(*http.Response, error)
```
replaces https://github.com/zalando/skipper/pull/3137

feature: httpclient before and after hooks

---

docs/reference/filters.md
filters/auth/grant.go
filters/auth/grant_test.go

Login redirect stub introduced by #3028 uses `{{authCodeURL}}` placeholder which is a valid mustache tag and hence inconvenient to use from mustache templates.
This change adds a second `{authCodeURL}` placeholder and `X-Auth-Code-Url` response header.

filters/auth: add second login redirect stub placeholder

---

docs/tutorials/auth.md
filters/openpolicyagent/evaluation.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/openpolicyagent.go
filters/openpolicyagent/openpolicyagent_test.go

The release of the feature Facilitate OPA decision correlation with business flows ([PR](https://github.com/zalando/skipper/pull/3041/files)) led to the a [bug](https://github.bus.zalan.do/pg9/issues/issues/624) that leads to the skipper restarts. This is because an object of same reference is being shared among the different instances of opa instances. 
Error log from the reported bug (for those who cannot access the bug details):
```
goroutine 191993 [running]:
github.com/zalando/skipper/filters/openpolicyagent.setDecisionIdInRequest(0x4004494720, {0x40067c6440?, 0x10?})
github.com/zalando/skipper/filters/openpolicyagent/evaluation.go:92 +0xe4
github.com/zalando/skipper/filters/openpolicyagent.(*OpenPolicyAgentInstance).Eval(0x40059ef400, {0x16b6bb0, 0x40044946c0}, 0x4004494720) …
```

Facilitate OPA decision correlation with business flows

---

.github/dependabot.yml

fix: dependabot should update clusterfuzzlite
build failure happened in https://github.com/zalando/skipper/pull/3193

fix: dependabot should update clusterfuzzlite

---

proxy/proxy.go
proxy/proxy_test.go
proxy/request_test.go

Respond with 400 instead of 500 in case of invalid chunked request body.

proxy: handle invalid chunked requests

---

filters/auth/grant_test.go
filters/auth/grantconfig.go

Do not propagate trailing question mark from the initial request to redirect URI.
Construct redirect url from scratch instead of resetting URL.ForceQuery.
See related https://github.com/golang/go/issues/13488

filters/auth: handle trailing question mark in grant flow

---

skipper.go
skipper_test.go

Add a callback to register additional filters that can also re-use already registered filters.

options: Add RegisterFilters callback

---

skipper_test.go

Test that built-in and CustomFilters are registered before RegisterFilters callback.
Follow up on #3203

options: test filter registration order

---

filters/openpolicyagent/opaserveresponse/opaserveresponse.go

This PR adds to two minor improvements to make the opaServeResponse* filters symmetric with opaAuthorizeRequest* filters
1. **Include the `decision['allowed']` outcome to the trace span**
Similar to the change introduced in [PR](https://github.com/zalando/skipper/pull/3096), this PR adds the OPA decision's result (if available `decision['allowed']` outcome, without the body) under the `opa.decision.allowed` tag of spans for `opaServeResponse*` filters.
2. Increment/Update the decision count as a skipper custom filter metric [similar](https://github.com/zalando/skipper/blob/168e443c979d155f581940aaf8e25460232c0f84/filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest.go#L154-L161) to the opaAuthorizeRequest filter

Minor improvements to opaServeResponse filter

---

dataclients/kubernetes/definitions/definitions.go
dataclients/kubernetes/definitions/ingressvalidator.go
dataclients/kubernetes/definitions/routegroupvalidator.go

check https://pkg.go.dev/errors#Join
follow up on https://github.com/zalando/skipper/pull/2492

use standard `errors.Join` since we already use go1.22

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/openpolicyagent.go

Due to a detected performance concern for CPU as seen below,
**Memory profile**
_alloc_objects profile_
<details>
<summary>Using a request body as below with a simple policy to check email domain.</summary>
```
{
"email": "loadtest@zalando.de",
"user": {
"id": "12345",
"name": {
"first_name": "John",
"last_name": "Doe"},
"contact": {
"phone_number": "+49-123-456-7890",
"address": {
"street": "Main Street 123",
"city": "Berlin",
"zip_code": "10115",
"country": "Germany"}}},
"account": {
"created_at": "2023-08-28T10:15:30Z",
"status": "active",
"preferences": {
"language": "en",
"currency": "EUR"},
"subscriptions": {
"newsletter": true,
"alerts": {
"email": true,
"sms": false}}},
"meta": {
"last_login": "2023-08-28T10:20:00Z",
"login_count": 42,
"roles": [
"user",
"tester"],
"tags": [ …
```

Remove OPA filter `dependency.base` calculation in optional body parsing

---

config/config.go
docs/reference/filters.md
filters/auth/grantconfig.go
filters/auth/oidc.go
skipper.go

Similar to [secureOauthTokenintrospectionAllKV](https://github.com/search?q=repo%3Azalando%2Fskipper%20os.LookupEnv&type=code), support falling back to environment varible for client id and secret for oidc and oauth2 filters, when the values passed in are empty strings.
This will allow compatibility with external secret stores.
Testing:

fallback to env variable for oidc,oauth2 client id and secret

---

filters/openpolicyagent/internal/envoy/skipperadapter.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go

Improve the envoy request adapting logic to include query parameters sent in the request.
This would allow the policy evaluation `opaAuthorizeRequest*` and `opaServeResponse*` filters to make use of query parameters/values in the policy.

opa: pass URL query parameters to OPA policy evaluation

---

filters/auth/jwt_metrics.go
filters/auth/jwt_metrics_test.go
filters/auth/tokeninfo.go
filters/auth/yamlconfig.go
filters/auth/yamlconfig_test.go

Cache parsed yaml config for `jwtMetrics` and `oauthTokeninfoValidate` filters to avoid parsing the same configuration over and over when these filters are appended as default filters to all routes.
```
│     HEAD~1     │                 HEAD                 │
│     sec/op     │    sec/op     vs base                │
JwtMetrics_CreateFilter-8   30777.00n ± 6%   18.45n ± 11%  -99.94% (p=0.000 n=10)
│     B/op     │    B/op      vs base                 │
JwtMetrics_CreateFilter-8   24.33Ki ± 0%   0.00Ki ± 0%  -100.00% (p=0.000 n=10)
│   HEAD~1   │                HEAD                │
│ allocs/op  │ allocs/op  vs base                 │
JwtMetrics_CreateFilter-8   180.0 ± 0%    0.0 ± 0%  -100.00% (p=0.000 n=10)
```

filters/auth: cache yaml config

---

predicates/host/any_test.go

Current implementation uses linear probe that works well for small number of hosts.
I thought about implementing it using map lookup but that is slower for less than 50 hosts so I propose to only keep the benchmark that may be used for future improvements.
Here is comparison with map-based implementation for reference:
```
│    HEAD~1    │                 HEAD                  │
│    sec/op    │    sec/op      vs base                │
HostAny/1-8      3.738n ± 3%    5.844n ±  3%  +56.36% (p=0.000 n=10)
HostAny/2-8      7.728n ± 4%    9.274n ±  2%  +20.02% (p=0.000 n=10)
HostAny/5-8      11.32n ± 4%    13.09n ±  4%  +15.63% (p=0.000 n=10)
HostAny/10-8     22.35n ± 3%    11.86n ± 15%  -46.94% (p=0.000 n=10)
HostAny/20-8     7.684n ± 2%   11.310n ±  9%  +47.19% (p=0.000 n=10)
HostAny/50-8 …
```

predicates/host: add HostAny benchmark

---

filters/auth/tokeninfocache_test.go

Second argument of assert.Equal should be expected value.

filters/auth: fix assert usage in tokeninfocache tests

---

filters/auth/tokeninfocache.go
filters/auth/tokeninfocache_test.go

Cached value is readonly so release cache mutex early to
copy and adjust cached value outside of critical section.
```
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/filters/auth
│    sec/op    │    sec/op     vs base                │
TokeninfoCache/tokens=1,cacheSize=1,p=0-8           639.4n ± 21%   271.9n ±  6%  -57.48% (p=0.000 n=10)
TokeninfoCache/tokens=2,cacheSize=2,p=0-8           625.7n ± 24%   420.4n ± 32%  -32.81% (p=0.000 n=10)
TokeninfoCache/tokens=100,cacheSize=100,p=0-8       869.8n ± 17%   463.4n ±  3%  -46.72% (p=0.000 n=10)
TokeninfoCache/tokens=100,cacheSize=100,p=10000-8   670.8n ± 12%   594.6n ±  2%  -11.36% (p=0.000 n=10) …
```

filters/auth: release tokeninfo cache mutex earlier

---

docs/reference/filters.md

Implementation allows single argument variant which is used in the wild so document it.
Follow up on #1160 and #1168

docs: document single argument variant of `tracingBaggageToTag`

---

proxy/fadein.go
proxy/fadein_internal_test.go
proxy/healthy_endpoints.go
proxy/proxy.go

Just a small removal of unsued field.

minor: remove unused endpointRegistry field from healthyEndpoints and fadeIn

---

.github/workflows/gh-packages.yaml
packaging/Dockerfile
packaging/Makefile

Add [opencontainer image labels](https://github.com/opencontainers/image-spec/blob/main/annotations.md) (except org.opencontainers.image.created) to multiarch image.
Decided not touch Dockerfile.arm* because it is better to unify them with Dockerfile (see e.g. #2566).
Github action already adds opencontainer image labels:
```console
docker inspect ghcr.io/zalando/skipper:v0.21.209 | jq .[0].Config.Labels
{
"maintainer": "Team Gateway&Proxy @ Zalando SE <team-gwproxy@zalando.de>",
"org.opencontainers.image.created": "2024-09-26T09:40:09.452Z",
"org.opencontainers.image.description": "An HTTP router and reverse proxy for service composition, including use cases like Kubernetes Ingress",
"org.opencontainers.image.licenses": "NOASSERTION",
"org.opencontainers.image.revision": …
```

packaging: add opencontainers image labels

---

skipper.go

* add context message to returned errors
* remove duplicate logging - errors will be logged by the caller (main)

skipper: improve createDataClients errors

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go

- Fix test case that uses an invalid rego query in the test case
- Include a test case to validate policy evaluation based on `input.attributes.request.http.path` (http path set in the envoy check request)

Improvements to OPA filter unit test cases

---

config/config.go
config/config_test.go
filters/openpolicyagent/openpolicyagent.go
filters/openpolicyagent/openpolicyagent_test.go
skipper.go

This PR
* reduces the default buffer size for reading the request body to 8KB
* and makes it configurable via command line and Skipper config

OPA filters: Reduce default buffer size for reading the requests' body

---

dataclients/kubernetes/clusterclient.go

This is helpful for debugging k8s permissions.

dataclients/kubernetes: add resource URI to error message

---

config/config.go
skipper.go

Add an option and a flag to configure TLS Client Authentication policy of the Server.
Fixes https://github.com/zalando/skipper/issues/3280

skipper: add TLS client authentication config

---

docs/kubernetes/ingress-controller.md

Fix typos/broken anchors in docs

docs: Fix typo

---

filters/auth/jwt_metrics_test.go
filters/scheduler/fifo_test.go
filters/scheduler/lifo_test.go
filters/tracing/tag_test.go
net/httpclient_example_test.go
net/httpclient_test.go
proxy/tracing_test.go
tracing/tracingtest/mocktracer.go

This pull requests is split from https://github.com/zalando/skipper/pull/3318 to refactor change of testTracer to make it more reusable.

Move testTracer struct in tracingtest package and reuse it

---

.github/dependabot.yml

We decided to ignore automatically updating OPA dependencies. It was already done in https://github.com/zalando/skipper/pull/3332#issuecomment-2522944619 & https://github.com/zalando/skipper/pull/3320#issuecomment-2522931582
This PR is to add visibility and we will run `@dependabot unignore ...` after merging.
See [`ignore` docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore)

dependabot: ingore OPA updates

---

predicates/traffic/export_test.go
predicates/traffic/rand_test.go
predicates/traffic/segment.go
predicates/traffic/segment_test.go

Use fixed random sequence to deflake TestTrafficSegmentSplit.
Fixes #2665

predicates/traffic: deflake TestTrafficSegmentSplit

---

proxy/proxy.go

Remove debug mode check for clarity and because
other metrics are updated without checking for debug mode.

proxy: always count route lookup failures

---

docs/reference/filters.md

Add an example using template placeholder for the tag value.
Follow up on #3202

docs: add example for tracingTagFromResponseIfStatus

---

filters/shedder/admission.go
filters/shedder/admission_test.go

Updates https://github.com/zalando/skipper/issues/3317

Add more tags to the admissionControl span to increase visibility

---

.github/dependabot.yml

follow up on https://github.com/zalando/skipper/pull/3334

dependabot: ignore another OPA dependency update

---

filters/auth/grant.go
filters/auth/grant_test.go
filters/auth/oidc_introspection.go

This method allows third-party filters to set the oidcClaimsCacheKey which enables the use of the oidcClaimsQuery filter.
Closes #3139

oid_introspection: add SetOIDCClaims

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go

**Changes**
- Rego rules are made specific to test scenarios whenever it matters.
- A new test is added to confirm fragment is ignored from HTTP request path.
Pending :  HTTP2 headers are not tested as of yet. An internal ticket is present to address this.

Refactor opa filter tests to use specific rules

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go
filters/openpolicyagent/openpolicyagent_test.go
filters/openpolicyagent/tracing_test.go
filters/tracing/baggagetotag_test.go
filters/tracing/statebagtotag_test.go
filters/tracing/tag_test.go
proxy/tracing_test.go
redis_test.go
skipper_test.go
tracing/tracingtest/mocktracer.go
tracing/tracingtest/mocktracer_test.go
tracing/tracingtest/testtracer.go

Follow up on https://github.com/zalando/skipper/pull/684 (https://github.com/zalando/skipper/pull/684#issuecomment-399030290) and
deprecate hand-rolled test tracer implementation in favour of
MockTracer added by https://github.com/zalando/skipper/pull/3322 that wraps github.com/opentracing/opentracing-go/mocktracer and waits for finished spans.
Fix MockTracer:
* return MockSpan that has proper Tracer() implementation
* return MockSpan wrappers from FinishedSpans
* panic on timeout waiting for finished spans
Closes https://github.com/zalando/skipper/issues/2084
Updates https://github.com/zalando/skipper/issues/2104

tracing/tracingtest: deprecate Tracer and Span types

---

cmd/webhook/admission/admission_test.go
dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-invalid-routes-annotation-missing-header-argument.log
eskip/eskip.go
eskip/eskip_test.go

Add route id and predicate name to the error message.

eskip: improve invalid predicate arguments error message

---

config/config.go
config/config_test.go
dataclients/kubernetes/annotations.go
dataclients/kubernetes/ingress.go
dataclients/kubernetes/ingress_test.go
dataclients/kubernetes/ingressv1.go
dataclients/kubernetes/kube.go
dataclients/kubernetes/kubernetestest/fixtures.go
dataclients/kubernetes/routegroup.go
dataclients/kubernetes/routegroups_test.go
dataclients/kubernetes/testdata/ingressV1/annotation-filters/annotation-filters-append.eskip
dataclients/kubernetes/testdata/ingressV1/annotation-filters/annotation-filters-append.kube
dataclients/kubernetes/testdata/ingressV1/annotation-filters/annotation-filters-append.yaml
dataclients/kubernetes/testdata/routegroups/annotation-filters/annotation-filters-append.eskip
dataclients/kubernetes/testdata/routegroups/annotation-filters/annotation-filters-append.kube
dataclients/kubernetes/testdata/routegroups/annotation-filters/annotation-filters-append.yaml
skipper.go

Similar to #3328 this change adds new flags to configure filters appended to routes created for Kubernetes resources having specific annotation.

dataclients/kubernetes: append filters to routes of Ingress/RouteGroup having specific annotation

---

net/httpclient.go
net/redisclient.go
ratelimit/registry.go
routesrv/routesrv.go
secrets/secrettest/secrettest.go

Remove (some) unused fields detected via:
```
$ go install honnef.co/go/tools/internal/cmd/unused@latest
$ unused -field-writes-are-uses=false ./... 2>/dev/null
```

all: remove unused fields

---

docs/kubernetes/ingress-usage.md

Clarify relation between `zalando.org/skipper-routes` and `zalando.org/skipper-filter` annotation.
Follow up on #3323

docs: clarify Ingress annotations

---

filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go

Confirm the included cases of envoy input format included in Skipper.
HTTP2 headers are not supported yet.
Also below items are not supported though available in the envoy input format.
``
input.attributes.request.http.protocol == "HTTP/1.1"
input.attributes.destination.address.socketAddress.address == "10.25.95.68"
input.attributes.destination.address.socketAddress.portValue == 8000
input.attributes.source.address.socketAddress.address == "10.25.95.69"
input.attributes.source.address.socketAddress.portValue == 33772
input.attributes.request.http.headers[":authority"] == "example-app"
``

Add a test case on input contract validation

---

filters/auth/jwt_metrics_test.go

```console
$ go test ./filters/auth/ -run=NONE '-bench=BenchmarkJwtMetrics$' -count=10 | benchstat -
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/filters/auth
│      -      │
│   sec/op    │
JwtMetrics-8   2.279µ ± 4%
│     -      │
│    B/op    │
JwtMetrics-8   747.0 ± 0%
│     -      │
│ allocs/op  │
JwtMetrics-8   19.00 ± 0%
```

filters/auth: add jwtMetrics benchmark

---

jwt/token.go
jwt/token_test.go

Function `jwt.Parse` currently splits (via a call to [strings.Split](https://pkg.go.dev/strings#Split)) its argument (which is untrusted data) on periods.
As a result, in the face of a malicious request whose _Authorization_ header consists of `Bearer ` followed by many period characters, a call to that function incurs allocations to the tune of O(n) bytes (where n stands for the length of the function's argument), with a constant factor of about 16. Relevant weakness: [CWE-405: Asymmetric Resource Consumption (Amplification)](https://cwe.mitre.org/data/definitions/405.html)
With this change, `jwt.Parse` allocates O(1) bytes even in the face of such malicious requests.
---
Some benchmark results:
```
goos: darwin
goarch: amd64
pkg: github.com/zalando/skipper/jwt
cpu: Intel(R) Core(TM) …
```

jwt: reduce heap allocations in jwt.Parse

---

net/net.go
net/net_test.go

Use strings.LastIndex instead of strings.Split to reduce memory allocations.
See #3403 for details.
```
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/net
│    HEAD~1    │                HEAD                 │
│    sec/op    │   sec/op     vs base                │
RemoteHostFromLast/no_header-8      144.10n ± 7%   99.73n ± 6%  -30.79% (p=0.000 n=10)
RemoteHostFromLast/single_value-8    210.8n ± 5%   163.6n ± 5%  -22.39% (p=0.000 n=10)
RemoteHostFromLast/many_values-8     374.3n ± 4%   166.0n ± 3%  -55.66% (p=0.000 n=10)
geomean                              224.9n        139.4n       -38.01%
│   HEAD~1    │                HEAD                │
│    B/op     │    B/op     vs base                │
RemoteHostFromLast/no_header-8 …
```

net: use strings.LastIndex to parse header

---

predicates/forwarded/forwarded.go

Use strings.Index instead of strings.Split to reduce memory allocations.
See #3403 for details.

predicates/forwarded: use strings.Index to parse header

---

filters/openpolicyagent/opaauthorizerequest/benchmark_test.go

Observed a race condition in parallel benchmark execution in OPA filter benchmark tests when testing it out with policy bundles that manipulate headers (leading to concurrent modification of the filter context created and used in tests with the way it is written now).
Changes,
- Moved context creation to b.RunParallel loop to prevent concurrent modification.
- Added some missing assertions in benchmark tests.
- Removed duplicate test resource.

filters/openpolicyagent: Resolve race conditions in OPA filter benchmark tests

---

logging/log.go
logging/log_test.go
skipper.go

This PR adds the ability to use a custom access log formatter.
Currently, accessLogs can be configured in three ways:
- If `AccessLogJSONEnabled` is defined, you can either pass a JSONFormatter, or have Skipper initialize one.
- If `AccessLogJSONEnabled` is not defined, it uses a basic text formatter.
There are cases (for example, when configuring NewRelic logrus integration, [see here](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/nrlogrus), that a custom formatter is needed, but current logger can't be configured.
My initial approach was to change type on `AccessLogJsonFormatter` (typed parameter in Skipper options) to be able to pass any logrus.Formatter (interface), as it wouldn't break anything. But it would be weird to have something called …

Add access log formatter

---

logging/access.go
logging/access_test.go

This change allows accesslog entries to be enriched with requests' context, if a custom formatter uses that context.

Add context to log entry

---

filters/auth/oidc.go
filters/auth/oidc_test.go

The `skipperOauthOidc` cookies are only intended for Skipper, so they don't need to be forwarded to the application.
With this PR we simply drop those cookies before forwarding the request. This will reduce the overall header size of requests.
The implementation is inspired by the [`oauthGrant` filter](https://github.com/zalando/skipper/blob/6b448b1fe90cc113e365be8fba7cd6d122ad7a6d/filters/auth/grantcookie.go#L93-L100)
Closes https://github.com/zalando/skipper/issues/3459

Drop skipperOauthOidc cookies in oauthOidc filter

---

go.mod

The [master pipeline](https://github.com/zalando/skipper/actions/runs/14443139827/job/40497621133) is currently failing due to a [security vulnerability](https://osv.dev/GO-2025-3563) in Go 1.23.6.
This PR upgrades Go to v1.23.8.

go.mod: Upgrade to 1.23.8

---

proxy/upgrade.go
proxy/upgrade_test.go

When a backend server responded with a non-101 status code during WebSocket upgrade attempts, the response headers were not forwarded to the client. This fix ensures all headers from the backend response are copied to the client response before writing the status code.

fix: Copy headers from backend in upgrade proxy

---

eskipfile/watch.go
eskipfile/watch_test.go

Do not parse routes if file content did not change since last successful read.
Note that after https://github.com/zalando/skipper/pull/2304 RemoteWatch does not update file if response Etag did not change but underlying Watch would still parse routes.
```
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/eskipfile
│     HEAD~1     │                 HEAD                 │
│     sec/op     │    sec/op     vs base                │
WatchLoadUpdate-8   17889.7µ ± 24%   220.0µ ± 24%  -98.77% (p=0.000 n=10)
│    HEAD~1     │                 HEAD                 │
│     B/op      │     B/op      vs base                │
WatchLoadUpdate-8   7837.4Ki ± 0%   528.5Ki ± 0%  -93.26% (p=0.000 n=10)
│     HEAD~1      │                HEAD …
```

eskipfile: optimize Watch.LoadUpdates

---

proxy/proxy.go
proxy/tracing.go
proxy/tracing_test.go

To be able to find bad backend application instances we can use group_by network.peer.address queries.

tracing: set OTel network.peer.address in proxy span

---

docs/kubernetes/deploy/deployment/hpa.yaml

autoscaling/v2beta1 is not serverd since kubernetes 1.25

update the hpa in docs to autoscaling/v2

---

docs/reference/filters.md

- fix clusterRatelimit filter example
- mention that filters having the same ratelimit group must use the same number of requests and period parameter values.

docs: improve clusterRatelimit filter documentation

---

config/config.go

We can not set  `skipper -metrics-flavour codahale -metrics-flavour prometheus` as I would expect from the args doc.
We have to set `skipper -metrics-flavour codahale,prometheus`

doc: metrics-flavour args were not clear how to set "both"

---

proxy/proxy.go
proxy/tracing_test.go

When a request is looped back, all tracing operations (such as tagging and creating new spans) are performed on the original request's span rather than on the loopback span. This results in inaccurate tracing data: tags are overwritten, and the ingress span incorrectly appears to have child spans that actually belong to the inner loopback spans.
This PR adds a test case to illustrate the issue, along with a potential bug fix.
The trace produced by the request to the routegroup below
Both loopbacks are children of the ingress span
<details>
<summary>routegroup definition</summary>
```yaml
---
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
name: loopback-test
spec:
hosts:
- loopback-test.playground.zalan.do
backends:
- name: loopback
type: loopback
- name: shunt
type: shunt
routes:
- …
```

proxy/tracing: loopback spans bugfix

---

docs/operation/operation.md
metrics/all_kind.go
metrics/codahale.go
metrics/metrics.go
metrics/metricstest/metricsmock.go
metrics/prometheus.go
routing/datasource.go
routing/datasource_test.go

**Prometheus metrics:**
- `skipper_route_invalid_routes_gauge{reason}` (gauge) - Current number of invalid routes by reason
**CodaHale metrics:**
- `route.invalid.gauge.{reason}` (gauge) - Current invalid routes count by reason
**Failure Reasons Tracked:**
- `failed_backend_split` - Backend URL parsing errors
- `unknown_filter` - Unknown or disabled filters used
- `unknown_predicate` - Unknown predicates used
- `invalid_filter_params` - Invalid filter parameters
- `invalid_predicate_params` - Invalid predicate parameters
- Any other validation errors that may occur
- **Graph Representation**: Displays a graph with points over specific time intervals.
- **Calculation**: `(routes.total - sum(route.invalid.gauge.%s)) / routes.total`, where `routes.total` is an existed gauge metric

metrics: add route validation gauge metrics

---

.github/dependabot.yml

- Add dedicated gomod group for OPA-related dependencies
- Keep existing configuration for other dependencies
This change helps manage OPA dependency updates more effectively by grouping them separately from other Go dependencies.

chore(deps): optimize dependabot configuration for OPA dependencies

---

filters/openpolicyagent/opaauthorizerequest/benchmark_test.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest.go
filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go
filters/openpolicyagent/opaserveresponse/opaserveresponse.go
filters/openpolicyagent/opaserveresponse/opaserveresponse_test.go
filters/openpolicyagent/openpolicyagent.go
filters/openpolicyagent/openpolicyagent_test.go
skipper.go

This PR is a no-op refactoring from a user perspective that moves the Open Policy Agent configuration to the registry. 
Originally it was designed to have a per filter configuration but practically it is always the same.
This is the precondition to allow instance pre-loading #3526 and will also to re-use config across filters.

Move OPA instance configuration to registry level

---

proxy/upgrade.go
proxy/upgrade_test.go

When a client sends a request to upgrade to a Websocket connection
and presents the value of the header `Connection` in lower-case
then Skipper fails to upgrade the request.
This change fixes the issue by using a function to read the header that is case insensitive.
The bug was likely introduced in #3553.

fix: Websocket requests fail if case of value in Connection header and case of key in Upgrade header do not match

---

.github/dependabot.yml

This reverts commit 342103181a61ff9ac82b06a6f18c534ce3829e41.

Revert "chore(deps): optimize dependabot configuration for OPA dependencies (#3568)"

---

filters/openpolicyagent/opaauthorizerequest/benchmark_test.go
filters/openpolicyagent/openpolicyagent.go
filters/openpolicyagent/openpolicyagent_test.go

With https://github.com/open-policy-agent/opa/pull/7274 Open Policy Agent added configurable token cache to io.jwt token verification built-in functions to improve performance. See [changelog](https://github.com/open-policy-agent/opa/releases/tag/v1.1.0). 
With this pull request JWT cache reading and writing is enabled and benchmark tests are added to measure JWT validation performance with cache configuration. 
**Fix in opa-envoy-plugin**
After initial round of benchmark tests that showed no impact on perfomence the bug was found in opa-envoy-plugin and [contribution with the fix was made](https://github.com/open-policy-agent/opa-envoy-plugin/pull/748). 
- results for test with vs without cache configuration
for 10 runs, each 20 s:
attached: …

OPA JWT token cache configuration

---

predicates/auth/jwt.go
predicates/auth/jwt_test.go

optimize: JWT regexp based predicates
Context:
Normally clients reuse their tokens so we can easily cache the matching result by token for each predicate.
This will speedup significantly FabricGateway matching lookups.
Adds a sync.Map that we use to perform a cache lookup of the wire string to the result.
A new type `registry` is used to cleanup all entries every hour. For simplicity we do not track timestamps. Tested by a benchmark to cleanup every Millisecond and the result does not change significantly, so we should not care about the recreation of the cache once in a while.
Benchmarks for benchstat comparision ran with count 20
```
goos: darwin
goarch: arm64
pkg: github.com/zalando/skipper/predicates/auth
cpu: Apple M2
│    old.txt    │               new.txt               │
│ …
```

Optimize: jwt regexp predicates

---

proxy/healthy_endpoints_test.go

Skip TestPHC that takes ~133.47s for short test so that short test finishes in a reasonable time (~80s).

proxy: skip TestPHC for short test

---

proxy/proxy.go

The request and response timing metrics weren't captured in makeBackendRequest. 
Added a defer block to ensure stopwatches are stopped and elapsed times are recorded in the context.
A follow up to https://github.com/zalando/skipper/pull/3603

fix: Add missing timing metrics in makeBackendRequest

---

dataclients/kubernetes/definitions/routegroups.go

fix: forward backend in routegroups
The validation webhook creates a ServiceBackend by adding +1 to eskip.LBBackend, which was ForwardBackend. 
It failed then by wanting to have a service_name which is not required nor makes sense in ForwardBackend. 
follow up ref https://github.com/zalando/skipper/issues/3649 
commit dd70bd65e7f99cfb5dd6b6f71885d9fe3b2707f6 broke the append for eskip backends.

fix: forward backend in routegroups
