zalando/skipper

main.go, run/run.go, settings/file.go
For now it is an either-or deal. Either use etcd or the file. But for our current use-case, that should be sufficient.
=> added ability to load routes from local file

proxy/proxy.go, proxy/proxy_test.go
just merging master here to the reviewed release branch
=> Release cleanup master merge

proxy/proxy.go, routing/datasource.go, routing/routing.go, routing/routing_test.go
#40 
in one way, i find it laser. in another way, it's ugly :)
what do you think?
=> add monitoring info to the constructed filter instances

filters/filters.go, filters/filtertest/example_test.go, filters/filtertest/filtertest.go, proxy/proxy.go
=> Added backend url to the filter context

metrics/handler_test.go, metrics/metrics.go, metrics/metrics_test.go
Big kudos to @vetinari for the `()` tip.
Also changed metrics reporting to match dropwizard's
=> Fixed the bug in the metrics and switched to the UniformSample

eskip/eskip_test.go, eskip/lexer.go
=> fix lexer to trim comments in last position

metrics/metrics.go, metrics/metrics_test.go, proxy/proxy.go
Added counters for routing failures (Skipper 404) and 2 other error counters, the backend and while streaming body to the client
=> Add some useful metrics

innkeeper/client_test.go, proxy/proxytest/proxytest.go
created an initial proxy testing
some go fmt sneaked in, too
=> add test proxy

eskip/doc.go, filters/builtin/builtin.go, filters/builtin/header_test.go, filters/builtin/headerfilter.go
=> Header filters

etcd/etcd.go, etcd/etcd_test.go
Small cosmetic refactoring.
Just review code and mention that this method can be done in more easy way.
=> simple endpointErrors to string convertation

logging/access.go, logging/access_test.go
=> Added requested host to the access log

readme.md
* Apache license badge directing to LICENSE file
* Go Report, checking misspell, formatting, lint, ...
=> Adding badges

etcd/etcd_test.go
PR for #124 - tests for endpoints rotation
=> #124: add enpoints rotation tests

etcd/etcd.go
Optimization and more understandable client.tryEndpoints
Seems rotation not tested well, so, I'm not sure that this is correct optimization, but test passed and have same rotation instructions as original code.
This version will work faster, since less array copy operations and so on.
Since I'm not 100% sure that it is not broke something, merge it at your own risk or after more test will be cover more cases.
=> client try endpoints optimization

skipper.go
a demo can be found here:
[https://github.com/aryszka/skipper-dataclient-demo](https://github.com/aryszka/skipper-dataclient-demo)
=> provide an option to set custom data clients

routing/matcher.go, routing/matcher_test.go, routing/routing_test.go
fix #116 with use changes in https://github.com/zalando/pathmux/pull/2
=> Fix matcher

routing/matcher.go, routing/matcher_test.go
Come from https://github.com/zalando/skipper/pull/133#discussion_r60588967
=> less return arguments in matchPathTree

filters/builtin/static.go
This change simplifies the delayed response construct, by not checking the content-length but considering the response done when the ServeFile handler returns. This also makes it possible to extract it from the static filter and make it reusable in other filters, wherever a filter wants to change the response body but still streaming.
=> Simplify static filter

filters/builtin/builtin.go, filters/diag/diag.go, filters/diag/diag_test.go
This pull request implements network throttling: latency, max bandwidth or custom chunking with delays.
=> Diagnostics tools - Network throttling

CONTRIBUTING.md
=> doc: Update Contributing.md

innkeeper/client.go
some changes slimmed through to master without being gofmt-ed
=> fix go formatting

predicates/cookie/cookie.go, predicates/cookie/cookie_test.go
=> create cookie predicate

cmd/eskip/args.go, cmd/eskip/doc.go, cmd/eskip/load.go, eskip/string.go, eskip/string_test.go
=> Added pretty print functionality

eskip/doc.go
=> Glob standard in docs

skipper.go
=> apply cookie predicate

filters/diag/diag.go, filters/diag/diag_test.go, innkeeper/client.go
refactoring based on reviews to #174
=> Diag refactor

filters/doc.go, proxy/proxy.go
=> Close current body

eskip/doc.go, routing/datasource.go, routing/datasource_test.go, routing/doc.go, routing/matcher.go, routing/routing.go, routing/tree_test.go
create PathSubtree() predicate
cover existing Path() predicate cases with additional tests
=> Pathsubtree

cmd/eskip/args.go, cmd/eskip/doc.go, cmd/eskip/load.go, eskip/eskip.go, eskip/eskip_test.go, routing/datasource.go, routing/matcher.go, routing/routing.go
This PR also continues some preparation work on refactoring eskip to not treat some predicates as built-in (Path in this case).
=> Eskip json

filters/diag/diag.go
outgoing backend response -> outgoing backend request
=> fix the documentation of the diag filters: 

filters/builtin/path.go, filters/builtin/query.go, routing/datasource.go
this PR is to fix some missing go fmt
=> Go formatting

.gitignore, packaging/.dockerignore, packaging/Dockerfile, packaging/Makefile, packaging/readme.md, readme.md
=> change dockerfile: support eskip and skipper, change to alpine base image

cmd/skipper/main.go
enable setting the log level from cli options
=> log level in cli options

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, filters/builtin/status.go, predicates/source/source.go, skipper.go
as part of #227 and https://github.com/zalando-incubator/kubernetes-on-aws/issues/169
=> Kube client

proxy/proxy.go, proxy/proxy_test.go
return 503 Service Unavailable on errors when connecting to a backend service
Closes #241
=> Service unavailable error

Makefile, cmd/eskip/readclient.go, eskipfile/file.go, etcd/etcd.go, etcd/example_test.go, filters/builtin/compress_test.go, filters/diag/diag_test.go, innkeeper/client.go, logging/loggingwriter_test.go, metrics/metrics_test.go, skipper.go
This pull request comes as first of a couple tooling and CI related PRs. Shipping it separate because it contains some code changes. These code changes are required to pass `go vet`.
=> go vet fixes

.travis.yml, Makefile, cmd/eskip/doc.go, cmd/eskip/eskip.go, cmd/skipper/main.go, packaging/version/version.go
DON'T MERGE JUST YET
Before merging, we have to tag an initial version. I'd like to start with v0.0.9, is it ok?
How it works:
1. on pushing to branches, it runs the tests as currently
2. on creating a pull request, it runs the tests, checks if formatting was applied, and runs go vet
3. merge:
a) when merging to master, it bumps the patch version
b) when merging to master, and the commit message contains "minor-release" (the branch name is automatically picked when merging), bumps the minor version
c) like 3b but for the major version
=> Introducing sem ver

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
=> Changed handling of transient kube apiserver errors

.zappr.yaml
Adding the zappr config file to resolve #235
=> Adding zappr config file

proxy/debug.go, proxy/debug_test.go
As mentioned in the issue #222, this adds filters and predicates for the debug listener response.
=> Add filters and predicates from debug listener

etcd/etcdtest/mocketcd.go
go vet ./... spots now the issue being fixed here
=> go vet fix: check error before using response

Makefile, packaging/Makefile
start creating docker images on every release automatically
=> automatically create docker images on releases

Makefile, packaging/Makefile
fix to the docker building ci task
=> Automatic docker on release

MAINTAINERS
I did some changes, I commented somme PRs, but there's really no reason for me to be listed as maintainer as I'm not having any maintainer impact. It makes much more sense for me not to be in this list.
=> remove Raffo from maintainers list

cmd/skipper/main.go, metrics/handler.go, metrics/handler_test.go, metrics/metrics.go, skipper.go
=> expose profile info

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, skipper.go
=> Unit tests for kubernetes client related functions 

filters/tee/tee.go, filters/tee/tee_test.go, proxy/proxy.go
- fix forwarding headers
- fix teeing requests with no body
- sync tests
=> tee filter fixes

skipper.go
=> fix-backend-host-metrics

readme.md
A tiny section mentioning Kubernetes ingress with some links to an example manifest.
=> add a small section kube ingress

readme.md
=> add missing an

Makefile, etcd/install.sh
- chaning the etcd install script to allow installation of a fixed version
- making it fail on the first error
=> Etcd install script

.travis.yml
changing the used go version for travis builds
=> bump go version in travis builds

Makefile
removing failing docker builds until figuring a way to authenticate to a docker hub
=> remove failing docker build

cmd/skipper/main.go, doc.go, eskip/doc.go, eskip/eskip.go, eskip/eskip_test.go, eskip/example_test.go, eskip/json.go, eskip/lexer.go, eskip/parser.go, eskip/parser.y, eskip/string.go, eskip/string_test.go, filters/filters.go, innkeeper/eskiptojson.go, proxy/context.go, proxy/loopback_test.go, proxy/proxy.go, proxy/proxy_test.go, routing/datasource.go, skipper.go
implement the loop backend #274
=> Loop backend

eskip/doc.go
Tiny eskip doc update from the loopback PR
=> Tiny eskip doc update for loopback

doc.go, eskip/example_test.go
update loopback related documentation: wording and example.
=> small documentation related fixes

eskip/doc.go, packaging/readme.md, proxy/doc.go, routing/doc.go
- Added missing info to `proxy/doc.go`
- Fixed a few typos
=> Updating docs with loopback info

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, skipper.go
added a flag to explicitly ignore the Kubernetes ingress class.
See the discussion in: #334
=> flag for ignoring the ingress class

Godeps/Godeps.json, cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, etcd/etcd.go, filters/builtin/preservehost.go, filters/diag/diag.go, filters/tee/tee.go, innkeeper/client.go, logging/access.go, logging/doc.go, logging/log.go, logging/log_test.go, logging/logger.go, metrics/metrics.go, proxy/debug.go, proxy/proxy.go, proxy/upgrade.go, skipper.go
upgrade the logging lib to its latest release
=> update the logrus dependency

.zappr.yaml
This is needed to have it master before merging #344 :smile:
=> make Zappr compliant

delivery.yaml
=> build with CDP

Makefile
include the deps task for coverage generating tests
fixes #348
=> provide deps for coverage generator

cmd/eskip/args.go
fixing in bug in processing input args
fixes: #354
=> fix eskip patch append

packaging/readme.md
fixes: #355 
https://github.com/zalando/zalando-howto-open-source#what-about-a-readme-note
=> add license to the readme for compliance

doc.go
mention kubernetes among the possible route sources
=> reference the Kubernetes route source

cmd/skipper/main.go, eskip/string.go, metrics/handler_test.go, metrics/metrics.go, metrics/metrics_test.go, routing/datasource.go, routing/matcher.go, routing/matcher_test.go, routing/routing.go, routing/routing_test.go, skipper.go
=> List current rules 

glide.lock, glide.yaml, routing/routing_intenal_test.go
Add tests to show that internal function slice is behaving correctly
=> Add internal tests for routing package

dataclients/kubernetes/kube.go
fix #377
refer e.g. to https://en.wikipedia.org/wiki/Localhost#Name_resolution
=> use proper netmasks for private subnets

Makefile, skptesting/benchmark-proxy-tls.sh, skptesting/benchmark-proxy.sh, skptesting/benchmark.inc, skptesting/print-mem-profile.sh, skptesting/readme.md
- vendoring fix for ./... builds
- help output for tls tests
- avoid pid based cleanup twice
- fix memory profile printing
- fix typo in readme
=> fix benchmark scripts

proxy/proxy.go, proxy/proxy_test.go
with the recent proxy refactor, unnecessary logs were introduced for the cases when the route lookup failed
=> remove unnecessary logs for 404 route lookup failures

pathmux/tree.go, routing/matcher.go, routing/subtreeconflict_test.go, routing/testdataclient/dataclient.go
Closes https://github.com/zalando/skipper/issues/375
=> Fix subtree conflict

routing/matcher.go
message to zappr: make this pr pass
=> remove rx copying from route lookup

readme.md
=> Small README edits

cmd/eskip/load.go, eskip/string.go, eskip/string_test.go
add an additional new line to the pretty printing separator to follow the de-facto standards
=> add an additional new line to the pretty printing separator

logging/loggingtest/logger.go, proxy/proxy.go, proxy/proxy_test.go
Closes: https://github.com/zalando/skipper/issues/400
- allows backend service set the Server header
- allows filters change or drop the Server header
=> Reduce branding

routing/routing.go, routing/routing_test.go
add a route count header and a head request for the routes endpoint
Closes: https://github.com/zalando/skipper/issues/399
=> Routes count

readme.md
to share our open proposal google drive, we should have a section about it in our readme
=> add community to readme

ratelimit/doc.go, readme.md
add rate limiter package godocs and in the checkpoint list in readme.md
=> Document rate limiters

ratelimit/doc.go
this will fix the godoc rendering for package ratelimit
=> show package ratelimit docs

CONTRIBUTING.md
Fixes broken links in the `CONTRIBUTING.md` file.
=> Fix broken markdown links in CONTRIBUTING.md

metrics/metrics.go, proxy/proxy.go
add metrics for the cases when a 5xx was received from the backend
=> add metrics for backend 5xx

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
this implements #414 rate limit support in ingress
documentation will be shown at https://godoc.org/github.com/zalando/skipper/dataclients/kubernetes
=> rate limit support in ingress

metrics/metrics_test.go
fix metrics check issue:
- look only for the expected key
- wait while the key gets registered in the background
=> fix metrics timing issue in metrics test check

.travis.yml
use latest go version in travis builds ' ' '
=> use latest go version in travis builds

eskip/eskip.go, eskip/eskip_test.go
an eskip.ParseFilters() function already exists, this is its pair for the predicates: ParsePredicates()
Closes: #464
=> function for parsing predicates individually

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
=> set arbitrary skipper filters from ingress annotation

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
implements #465, set predicates for ingress via ingress annotation, test and docs added
=> set predicates using ingress annotation

dataclients/kubernetes/kube.go
[doc] shadow traffic ingress example
=> Kubernetes - shadow traffic

readme.md
[doc] add public Google Group
[doc] add skipper-plugins
[doc] explain better requirements for kubernetes integration
[doc] fix godoc link to main godoc page
[doc] fix skrop url and skoap hint
=> changes readme.md to enable users

dataclients/kubernetes/kube.go
trying to fix godoc formatting:
- seems like normal text is required between a title and a code block
- the length of godoc titles is limited
=> try to fix godoc formatting

readme.md
add skipper as router and skipper as ingress guides
=> intro guides in readme

etcd/etcd.go
https://github.com/zalando/skipper/issues/474
=> Increase etcd index if delete the route root

dataclients/kubernetes/kube.go, dataclients/kubernetes/orderingbug_test.go
=> Ordering bug

circuit/consecutivebreaker.go, circuit/ratebreaker.go
=> Properly log the state of the circuits breakers.

filters/builtin/builtin.go
=> fix naming of new functions

readme.md
=> Fix link to docs 

docs/dataclients/kubernetes.md, readme.md
add more links to new mkdoc pages to be more present
=> add more links and docs

docs/dataclients/kubernetes.md
Just a minor thing, looks like those quotes are wrong, am I right?
=> Remove unnecessary quotes from app name in the doc

docs/dataclients/eskip-file.md
There was a question how to run skipper, so fix documentation
=> show how to run skipper using the routes file

readme.md, tracing/tracing.go
add plugins to the main doc and point out that we have also opentracing support
#500
=> doc plugins and opentracing

docs/dataclients/kubernetes.md
* add IP whitelisting in the docs 
* redo sectioning to have it better accessible from rendered doc site
=> doc IP whitelisting

routing/matcher.go
Replace for loop with expansion in append
=> routing: Replace for loop with expansion in append

readme.md
=> uncenter skipper figure

docs/dataclients/kubernetes.md
* add auth header based client ratelimits
* add A/B testing section
=> document use cases A/B test and auth header based rate limits

cmd/eskip/readclient.go, doc.go, docs/deployments.md, eskip/eskip.go, predicates/cookie/cookie.go, proxy/proxy.go, routing/datasource.go, routing/datasource_test.go, routing/routing_test.go, routing/testdataclient/example_test.go, skipper.go
Generated by [misspell](https://github.com/client9/misspell) tool.
=> all: fix typos

glide.lock, glide.yaml, script/script.go
to be rendered as JSON, requires
https://github.com/layeh/gopher-json/pull/2
to be merged
=> serve's body= parameter accepts a table

docs/scripts.md, mkdocs.yml
Add lua scripting docs for gh-pages
=> Scripts docs

cmd/skipper/main.go, proxy/proxy.go, skipper.go
Enable to set backend and frontend connections settings and set reasonable defaults
=> Conn handling

readme.md
There were a couple of extra quotes in there.
=> Fix sample demo-ing.yaml

filters/tee/tee_test.go
Otherwise it was almost to fail.
=> Fix tee test typo.

docs/dataclients/route-string.md, docs/kubernetes/ingress-usage.md
[doc] add service types and workaround to externalName with a reference to routestring
=> Docs - kubernetes service types supported and oneline proxy 

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
The last active backend (with a non-zero traffic weight) can get a weight of less than 1.0 due to floating point precision issues. Fix by forcibly setting a weight of 1.0.
=> computeBackendWeights: avoid rounding issues

docs/kubernetes/ingress-usage.md
add modPath to ingress usage docs
=> [doc] add modPath 

cmd/eskip/args.go, cmd/eskip/doc.go, cmd/eskip/load.go, eskip/string.go, eskip/string_test.go, routing/routing.go
implementing the -indent option #270 
I apologize any inconvenience by re-opening this !
=> implementing the -indent option #270

dataclients/kubernetes/definitions_test.go
fix formatting with gofmt -w -s (make fmt)
=> fix formatting, use -s switch

routing/datasource.go, routing/predicates_test.go
=> Support legacy predicates in generic list

docs/videos.md, mkdocs.yml
add first screencast to test the videos tab
=> docs videos tab

proxy/proxy.go
...this is the one which found #590 ;-)
=> more tracing details

filters/builtin/builtin.go, filters/cors/cors.go, filters/cors/cors_test.go, filters/cors/doc.go
Related to #559.
The rest of the headers can be set using setResponseHeader.
=> Add cors origin filter.

docs/kubernetes/ingress-usage.md
=> fix typo in ingress docs

doc.go
fix formatting from a previous commit
=> fix formatting

etcd/etcd.go, etcd/etcd_test.go
Fixes #487 
Added basic auth as additional mechanism to authenticate to etcd client. @szuecs What do you think about the prioritization vs OAuth?
=> Add basic auth

docs/kubernetes/ingress-usage.md
with inlineContent you can return arbitrary content and with <shunt> you can respond early
=> document inlineContent filter in ingress-usage

dataclients/kubernetes/kube.go, dataclients/kubernetes/lbtarget_test.go, loadbalancer/filter.go, loadbalancer/predicate.go
The decision header will disappear in the future, but we should not leak it to backends
=> do not leak decision header to backends

etcd/etcd_test.go
fixing failing tests in  etcd:
- using a mock server to capture the outgoing auth header
- checking the returned error on Delete
=> fix etcd auth header test

loadbalancer/concurrency_test.go
this should show the bug mentioned in #614 and #608.
=> add a concurrent test case with multple routes

readme.md
Add slack channel to the community
=> Doc: Add slack channel

docs/dataclients/eskip-file.md, docs/filters.md, docs/scripts.md, filters/diag/diag.go, mkdocs.yml
this is a list of all (non deprecated) built-in filters. Please help
to document the expected parameters and add descriptions on how to
use
=> [WIP] Filter docs

docs/kubernetes/ingress-controller.md
#613 document how to run multiple skippers and only select a subset of ingress with kubernetes annotation
=> doc: multiple skipper deployments

docs/predicates.md, mkdocs.yml
=> doc: add predicates documentation

proxy/proxy.go
Following the [semantics of Opentracing](https://github.com/opentracing/specification/blob/master/semantic_conventions.md) and trying to add more information to traces I have add and modified some tags and logs on proxy and ingress spans.
* Add http host (I think that this tag could be very interesting when querying traces in some cases).
* Add http path tag.
* Add remote address tag.
* Modify http url tag to set the full url (when available).
* Set server span kind on ingress span (important to know if the http data is from an ingress request or a egress one).
* Set component to `skipper`.
* Set error log on proxy span to follow the semantic convention of errors.
Example:
=> Improve trace tags in ingress and proxy spans

dataclients/kubernetes/kube.go
- goroutine leak is caused by IdleConnTimeout value being the same as a sleep value internally used by the go runtime
- tune some values to be more reasonable to production load
=> fix goroutine leak in kubernetes dataclient

dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/lbtarget_test.go, dataclients/kubernetes/orderingbug_test.go, dataclients/kubernetes/update_test.go
follow-up for: https://github.com/zalando/skipper/pull/658
cleaning up the background process
=> teardown background process

cmd/skipper/main.go
this is only a formatting of the command line options, primarily to reduce realigning too many lines when adding a new cmd line option
=> group command line options

proxy/proxy.go
- Added route ID to the proxy span.
=> Added ID of the matching route to open tracing span

dataclients/kubernetes/kube.go, dataclients/kubernetes/lbannotationfilters_test.go
=> don't add annotation filters to LB decision routes

dataclients/kubernetes/kube.go
=> use 308 in Kubernetes HTTPS redirect instead of 301

docs/filters.md
=> doc: add filter documentation for tokeninfo filter

proxy/proxy.go
fix #687: client closed request should not be reported as 5xx
=> client closed request should not be reported as 5xx

docs/predicates.md, predicates/auth/jwt.go, predicates/auth/jwt_test.go, skipper.go
JwtAnyKV("iss", "https://accounts.google.com")
JwtAllKV("iss", "https://accounts.google.com", "email", "skipper-router@googlegroups.com")
=> add predicates to match based on jwt content

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
fix #714 ingress backends can not have different ports from one service
=> fix #714 ingress backends same svc name but different ports

dataclients/kubernetes/kube.go
this TODO entry is not relevant since: https://github.com/zalando/skipper/pull/694
=> removing old TODO item: kubernetes LB + custom filters

filters/builtin/query.go, filters/builtin/query_test.go
needed for some old application that do not support ?foo=, but want to have ?foo
=> add setQuery(string) #723

docs/kubernetes/ingress-usage.md
doc: add authorization filters and predicates to the ingress-usage and link them to the predicates and filters docs.
doc: fix and add more docs to the custom-routes
=> docs: fix custom-routes and add auth to ingress use docs 

cmd/skipper/main.go, docs/operations.md, filters/auth/doc.go
- dropped comment 
- added user docs
- added default to dev docs
=> docs add oauth timeout

metrics/all_kind.go, metrics/codahale.go, metrics/codehale_test.go, metrics/prometheus.go, metrics/prometheus_test.go
- Add Gauges and their corresponding tests
=> Adds Gauges to metrics

docs/index.md
document:
- routing mechanism with matching, request filters, backend request, response filters
- route lookup mechanism
=> add docs about the route matching mechanism

docs/dataclients/inkeeper-api.md, docs/deployments.md, mkdocs.yml, readme.md, skipper.go
Close #709 
- Fix typo for innkeeper
=>  #709 Fix typo for innkeeper

metrics/codahale.go, metrics/metrics.go
- Fix Metrics struct
- Use snapshot before get Gauge value
- Fix Gauge type during marshalling
=> Fix Metrics interface

docs/development.md, mkdocs.yml
#751 Adds how to build a filter with docs, tests and implementation.
=> developer doc: how to build a filter

.gitignore, delivery.yaml, packaging/Dockerfile.lightstep, packaging/Makefile, packaging/skipper.sh
Added dockerfile and makefile for building skipper with lightstep integration. Also added new step to CDP build pipeline.
=> Added dockerfile for building skipper with lightstep integration.

packaging/Dockerfile.lightstep, packaging/skipper.sh
@mikkeloscar suggested in https://github.com/zalando/skipper/pull/758#discussion_r213749843 to simplfy the lightstep container
=> simplfiy as suggested

.gitignore
=> fix build to create non dirty containers

readme.md
=> doc known skipper users

readme.md
=> fix comment that I missed in the forst PR

readme.md
=> godoc link

docs/reference/development.md
Add instructions and patch file to use debugger.
=> Add doc for using debugger.

docs/reference/filters.md, filters/auth/doc.go, filters/auth/forwardtoken.go, filters/auth/forwardtoken_test.go, filters/builtin/builtin.go, go.mod, go.sum
Filter for fowarding tokeninfo and token introspection results.
=> Filter for fowarding tokeninfo and token introspection results.

filters/auth/auth.go, filters/auth/authclient.go, filters/auth/tokenintrospection_test.go
Fixes https://github.com/zalando/skipper/issues/810
Tried this against an IAM backend and it works now.
=> Fix introspection token key 

docs/reference/filters.md
doc for auditLog() filter, fixes #798
=> doc auditLog filter

proxy/proxy.go
fix typo retrieable -> retrievable
=> fix typo retrieable -> retrievable

docs/tutorials/auth.md
=> fix typo in tutorial

readme.md
=> add conference talk

docs/tutorials/basics.md
=> fix some comments in the docs

delivery.yaml
=> last step was missing to deploy on merge to master

docs/data-clients/eskip-file.md, docs/data-clients/route-string.md, docs/kubernetes/ingress-usage.md, docs/operation/operation.md, docs/reference/filters.md, docs/tutorials/auth.md
=> fixing html escape sequences in code renderings

readme.md
=> docs: fix build

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, docs/kubernetes/ingress-usage.md, skipper.go
=> add possibility to set east west domain

proxy/proxy.go
=> This bug was fixed and there is no need for the hack anymore

docs/kubernetes/ingress-controller.md
=> Fix a small typo in the docs

proxy/proxy.go, readme.md
=> 858 added flowid

docs/tutorials/ratelimit.md
=> doc: fix ratelimit tutorial

docs/operation/operation.md
=> doc fix #824

docs/kubernetes/ingress-usage.md
@grassator I hope this fix the issue you described internally
=> add explanation of the path handling for custom routes

docs/reference/filters.md
=> fix indentation level of oidc filters

readme.md
=> fixed several

docs/reference/predicates.md
=> add PATCH method to not confuse users

readme.md
=> add passing cii badge

filters/apiusagemonitoring/filter.go, filters/apiusagemonitoring/filter_endpointmetrics_test.go, filters/apiusagemonitoring/pathinfo.go, filters/apiusagemonitoring/spec.go
Replaces https://github.com/zalando/skipper/pull/855
=> Remove useless JSON and String serialisation

docs/data-clients/etcd.md
document etcd use cases and maintenance of route configuration in etcd
=> provide documentation on etcd usage

CODE_OF_CONDUCT.md, CONTRIBUTING.md, readme.md
add coc, ext blogpost to achieve silver badge
add more to the contributing guide which is needed to reach silver cii badge
=> silver cii badge - coc, contributing

delivery.yaml, go.mod, go.sum, proxy/proxy.go, proxy/upgrade.go
=> safe memory space and simplify code

filters/builtin/builtin.go, filters/ratelimit/ratelimit.go, ratelimit/ratelimit.go
=> fix #943 clientRatelimit was registered

proxy/upgrade.go
fix non compliant websocket requests that are made by many libraries out there
=> fix non rfc compliant websocket requests

proxy/proxy.go
=> use Debugf instead of Debug, since the message uses formatting

docs/kubernetes/ingress-controller.md
This pull reqeust is a modification of the document.
skipper sample yamls are not enough rbac setting.
=> Fix ingress_controller.md  ClusterRole not enough settings.

docs/reference/filters.md
Fix rendering of filter docs and add a little more description
=> Fix rendering of filter docs and add a little more description

proxy/upgrade.go
as it was pointed out here: https://github.com/zalando/skipper/pull/947#discussion_r255109018 , this comment is not required.
=> drop not required comment

docs/kubernetes/ingress-controller.md
update rbac to our current deployed version and update the skipper version in deployment parts
=> doc fix rbac

cmd/skipper/defaultfilterflags.go, cmd/skipper/main.go, eskip/eskip.go, eskip/eskip_test.go, proxy/loopback_test.go, proxy/proxy_test.go, routing/datasource.go, routing/routing.go, skipper.go
=> default filters as routing.PreProcessors

docs/kubernetes/ingress-controller.md
Added formatting in some places, changed wording in others.
=> Formatting and cleanup of Ingress comparison docs

filters/auth/oidc.go
=> use hostname from host header

docs/kubernetes/ingress-usage.md
=> doc: fix A/B example as mentioned by @fpozzobon

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, docs/operation/operation.md, skipper.go
=> k8s dataclient default filter config via config map

readme.md
=> Little update to the readme file concerning eskip check

proxy/proxy.go
add logs to possibly identify slow skipper client vs. slow backend
add tag client.request=canceled on 499, such that we could query this case
=> enhance opentracing

filters/apiusagemonitoring/filter.go
=> fix #1049: fix potential nil dereference

proxy/proxy.go, proxy/proxy_test.go, scheduler/scheduler_test.go
Closes #1045 
Signed-off-by: Maxim Tschumak <maxim.tschumak@gmail.com>
=> feat: provide the first stack trace on filter panic (#1045)

proxy/proxy_test.go
Related to #1045
Signed-off-by: Maxim Tschumak <maxim.tschumak@gmail.com>
=> remove log output in tests (#1045)

tracing/tracers/lightstep/lightstep.go
The recommended way to log information regarding issues is to use `SetGlobalEventHandler` (see [this](https://github.com/lightstep/lightstep-tracer-go/blob/master/options.go#L165) and the default logger logs only the first error event (see [this](https://github.com/lightstep/lightstep-tracer-go/blob/master/event_handlers.go#L72)).
I actually wanted to inject `logging.Logger`on [`InitTracer`](https://github.com/zalando/skipper/blob/master/tracing/tracing.go#L68). However, this would break the behavior described [here](https://github.com/zalando/skipper/blob/e20191f29c77e0eb8487356545f65d699ae75bf6/docs/reference/plugins.md#opentracing-plugins). Let me know you prefer to do this another way.
=> Log important events emitted by LightStep tracer

tracing/tracers/lightstep/lightstep.go, tracing/tracers/lightstep/lightstep_test.go
=> add config options grpc max buffer and min/max report times

docs/reference/filters.md, filters/auth/auth.go, filters/auth/doc.go, filters/auth/tokeninfo.go, filters/auth/tokeninfo_test.go, filters/auth/tokenintrospection.go, filters/auth/tokenintrospection_test.go
add failing tests that should work after fixing https://github.com/zalando/skipper/issues/1044
=> tokenin*AnyKV filters should be able to check same keys

docs/kubernetes/ingress-usage.md
=> add lb annotation to ingress user docs

go.mod, go.sum
=> remove dependency

predicates/auth/jwt.go, predicates/auth/jwt_test.go
- fix JWTPayloadAnyKV should have multi key assignment similar to token*AnyKV filters
- add more test coverage and fix edge case bug found by the test
=> fix JWTPayloadAnyKV should have multi key assignment similar to token*AnyKV filters

docs/reference/filters.md, docs/tutorials/ratelimit.md, filters/ratelimit/ratelimit.go, filters/ratelimit/ratelimit_test.go, ratelimit/ratelimit.go, ratelimit/ratelimit_test.go, ratelimit/registry.go
add tuple lookuper to client and clusterClient ratelimit facility
add more tests for ratelimit and filter
=> tuple client ratelimit

docs/reference/filters.md, filters/auth/forwardtoken.go, filters/auth/forwardtoken_test.go
* Add ability to mask keys in the JSON payload for the forwardToken filter
* Update docs in relation to forwardToken filter enhancements
* Add tests covering new functionality
=> Enrich forwardToken filter

docs/reference/filters.md, filters/auth/forwardtoken.go
cleanup from https://github.com/zalando/skipper/pull/1070
=> fix leftovers from comments

metrics/metrics.go, metricsinit_test.go, ratelimit/redis.go, skipper.go
move metrics initialization before packages depending on metrics.Default are initialized
=> initialization order, metrics

proxy/tracing.go
End event was named `start` :P
=> Fix span event name

filters/auth/oidc.go
If the request was received over a _TLS_ then set the `Secure` directive on the cookie. Fixes #1085
=> Set secure directive if request is receive on https

Makefile, go.mod, go.sum, proxy/proxy.go
refactor error vars in proxy to be constants as described in https://dave.cheney.net/2016/04/07/constant-errors
=> refactor error vars in proxy to be constants

filters/apiusagemonitoring/filter.go, filters/apiusagemonitoring/filter_endpointmetrics_test.go, filters/apiusagemonitoring/testutils_test.go, predicates/auth/jwt_test.go
=> fix: use path from request chain (#1094)

filters/log/log.go, filters/log/log_test.go
feature: unverifiedAuditLog filter with varargs #1090
=> feature: unverifiedAuditLog filter with varargs

docs/reference/filters.md, docs/tutorials/ratelimit.md
=> clarify ratelimit fitler docs

Makefile
=> fix release version var

packaging/Makefile
=> fix bash syntax missing "done"

delivery.yaml
=> fix upload flag

packaging/Makefile
=> fix shell var needs double $ to access

delivery.yaml
=> add armv7 and armv8 docker containers to release process

cmd/skipper/breakerflags.go, cmd/skipper/pluginflags.go, cmd/skipper/ratelimiterflags.go
=> handle string on list flags when called on nil

docs/kubernetes/ingress-usage.md, docs/reference/filters.md, docs/tutorials/common-use-cases.md
Make redirect handling docs more clear, fixes also #992 
=> make docs more clear and add links from reference to tutorial

proxy/proxy.go, proxy/proxy_test.go
=> do retries only if the request is retrieable

filters/diag/diag.go
follow up from https://github.com/zalando/skipper/pull/1136   by @max-neverov
=> fix ineffassign in throttle filter

Makefile, cmd/skipper/main.go, secrets/file.go, skipper.go
=> fix credentials poll should not be 0 for library users

mkdocs.yml
=> fix doc build and wire egress to reference section

docs/kubernetes/ingress-controller.md
Just a small PR to update docs to latest workload `apiVersion` :smile:
=> update apiVersion to apps/v1

docs/reference/predicates.md, predicates/auth/jwt.go, predicates/auth/jwt_test.go, skipper.go
This is useful for e.g. matching `azp` claims.
=> Add JWTPayloadAllKVRegexp, JWTPayloadAnyKVRegexp

docs/kubernetes/ingress-usage.md
=> Fix link to auth tutorial

dataclients/kubernetes/kube.go
split the methods in the kube data client
=> refactor kube data client

docs/reference/filters.md, docs/reference/predicates.md
=> fix issues identified in a workshop

docs/reference/filters.md, filters/tracing/baggagetotag.go
Update `baggageItemToTag` filter name to `tracingBaggageToTag `. See this PR for details https://github.com/zalando/skipper/pull/1160
=> feat: Update baggageItemToTag filter name

docs/tutorials/development.md, packaging/readme.md, readme.md
fix some random docs, while searching for the wrong build command that was used in https://github.com/zalando/skipper/issues/1187
=> small doc fixes

filters/builtin/creationmetrics.go
add logging for route creation time to help debugging if the issue is
1. with the route creation time logic 
2. the histogram bucket
3. or the route creation is actually slow
=> add logging for route creation time

filters/builtin/creationmetrics.go, filters/builtin/creationmetrics_test.go
=> monitor route creation time

filters/scheduler/lifo_test.go
=> add more unit test coverage for scheduler filters

dataclients/kubernetes/kube.go
set the origin marker after the diff of the routes was taken. (Currently the originMarkers are added to a different route on every poll, therefor an invalid update is detected.)
=> set origin markers only when there were any changes to the routes

filters/auth/auth.go, filters/auth/authclient.go, filters/auth/forwardtoken.go, filters/auth/oidc.go, filters/auth/tokeninfo.go, filters/auth/tokeninfo_test.go, filters/auth/tokenintrospection.go, filters/auth/webhook.go
make sure errors not rooted in the incoming requests are logged from the auth filters
=> logging auth errors

docs/tutorials/basics.md
=> Fix links to dataclients docs

docs/reference/filters.md
Add regex example for modPath.
=> Add regex example for modPath

docs/tutorials/basics.md
=> Fix broken link in docs

go.mod
=> update go version in go.mod

routing/matcher.go, routing/matcher_test.go, routing/predicates_test.go
fix conflict between Path("/**") and PathSubtree("/")
Fixes: #1198 
=> fix conflict between Path("/**") and PathSubtree("/")

filters/accesslog/control.go, logging/access.go, logging/access_test.go, logging/doc.go, logging/log_test.go, proxy/proxy.go
=> Feature to include additional data to the access log

docs/tutorials/basics.md
I've add a new yaml example with more flag types
=> improve config.yaml documentation

docs/reference/filters.md
https://github.com/zalando/skipper/pull/1218#discussion_r335900711
=> doc fix typo 

packaging/Makefile
=> use the version and commit hash in each build output

docs/reference/filters.md
doc: add redirectTo https example and clarify about the http to https redirect
=> doc: add redirectTo https example

delivery.yaml
=> automate changelog for GH release

delivery.yaml
=> fix docker command run

skptesting/benchmark.inc, skptesting/report.lua
=> create result.csv on bench run by report.lua used in wrk

docs/operation/operation.md
=> doc: fix operations toc

docs/reference/filters.md, filters/builtin/builtin.go, filters/tracing/tag.go, filters/tracing/tag_test.go
This adds a simple filter for adding a custom opentracing tag.
=> add tracingTag filter

filters/tracing/tag_test.go
improvements to the previous PR
=> improve error messages for the tracingTag filter tests

docs/tutorials/ratelimit.md
document security consideration, that client based ratelimits are based on client data chosen by the client, fix https://github.com/zalando/skipper/issues/1226
=> document security consideration

scheduler/scheduler.go, scheduler/scheduler_test.go
Close route and group (lifo() and lifoGroup()) queues when it's detected that they're not used anymore.
=> close unused route and group lifo queues

docs/operation/operation.md
=> list was no rendered correctly

docs/reference/filters.md, docs/tutorials/auth.md
fix https://github.com/zalando/skipper/issues/1284
=> doc fix oidc filters

docs/reference/filters.md, filters/builtin/builtin.go, filters/diag/absorb.go, filters/diag/absorb_test.go
absob absorbs request payload until the request stops sending it
=> absorb filter for diagnostics

filters/auth/oidc.go, filters/auth/oidc_test.go
This is the second part follow up of #1089 to properly deal with large JWT token and cookies.
Compression is trading computing with bandwidth, however we consider a 🐛 in conjunction with _AWS Application LoadBalancer_ which has a hard limit on header/cookies of 16kb, that we exceed right now! Skipper could with this PR not only solve this issue but improve the roundtrip through significantly less payload!
Confirmed it solves that describedcurrent problem, tested in integration setup:
`[APP]time="2020-01-29T13:39:51Z" level=debug msg="cookie compressed: 27695 to 11147"`
Also, since the payload for **requests (cookies) are reduced by a factor of ~2.5** the overall performance is measurable improved!
Tests showed that compression on the cookies pays off from >200 bytes payload which is …
=> adding compression for OIDC cookies

delivery.yaml, docs/python-constraints.txt
=> attempt to fix some python versioning stuff for mkdocs

delivery.yaml, docs/python-constraints.txt
checking if the mkdocs upstream was fixed
=> revert fixed python dependency versions

dataclients/kubernetes/api_test.go, dataclients/kubernetes/clusterclient.go, dataclients/kubernetes/clusterclient_test.go
=> reduce log spam by logging the failed detection only once

docs/reference/predicates.md
doc: have a better browsable section segmentation for path based predicates
=> doc: sectioning path based predicates

docs/reference/filters.md
Description and example was missing in the docs. Discovered during Kubernetes training :)
=> Add description for stripQuery filter

filters/builtin/compress.go
Since `sync.Pools` are garbage collected, the current implementation where the pools are warmed up at `init()` are purged after few cycles! This leads to empty pools after around 2 GC cycles (ref: https://go-review.googlesource.com/c/go/+/162919/)
This implementation changes to not pre-create pools but rather use the constructor to create them on demand.
Regarding memory consumption, currently it would be `CPUs x 4` or `num of concurrent threads` whichever is bigger. New implementation would be also maximum number of concurrent threads, but degrades if not used.
The existing benchmark already shows that, regarding the amount of concurrent calls, this implemenation is faster.
```
BenchmarkCompress6-8 (currently)        234	   5687061 ns/op	 3315737 B/op	      61 allocs/op …
```
=> performance issue sync.Pool flushed by GC

docs/reference/predicates.md, predicates/methods/methods.go, predicates/methods/methods_test.go
This PR adds new Methods predicate which allows filtering on multiple methods.
```
Methods("POST")
Methods("GET", "POST")
```
Resolves #1272
=> Methods predicate

filters/builtin/compress.go, filters/builtin/compress_test.go
fixing: https://github.com/zalando/skipper/issues/1312
=> close encoder before putting back to the pool

docs/kubernetes/ingress-usage.md
I just found while reading the docs that **authentication** was a bit miss typed as `autnetication`. 
So here is the fix for it.
=> fixed type in ingress-usage.md

docs/reference/filters.md, filters/builtin/builtin.go, filters/diag/logheader.go, filters/diag/logheader_test.go
=> Header logger

secrets/readers_test.go
=> add tests for secret readers

docs/kubernetes/routegroups.md
=> update state of rg

packaging/helm/skipper-aws/README.md
* Added some clarity around IAM policies and linked off to documentation on creating the roles. (I'm not sure about kube-aws-iam-controller-role)
* Added table of configurable values
=> Updated Helm chart readme

docs/reference/predicates.md
=> Docs > Fix typo in URL

routing/datasource.go, routing/datasource_test.go
For beginners, it's very easy to mix predicates and filters. Also when using Kubernetes annotations, sometimes a mistake is easy to make.
Instead of returning `failed to process route (kube_x): filter not found: 'PathRegexp'` it will now return `failed to process route (kube_x): trying to use 'PathRegexp' as filter, but it is only available as predicate`
=> Explain when using predicate as filter

docs/data-clients/route-string.md
=> Docs > Simplify route example

docs/operation/operation.md
=> doc: add debug listener example in operations guide

dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/routestring/string_test.go, eskip/eq.go, eskip/eq_test.go, eskip/eskip.go, eskip/eskip_test.go, eskip/parser.go, eskip/parser.y, eskip/parser_test.go, eskip/string.go, eskip/string_test.go, etcd/etcd_test.go, filters/builtin/redirect_test.go, filters/builtin/static_test.go, filters/builtin/status_test.go, filters/diag/diag_test.go, innkeeper/client_test.go, innkeeper/eskiptojson.go, proxy/example_test.go, proxy/proxy.go, routing/datasource.go
I see lots of deprecated stuff in the codebase that was deprecated long time ago. Maybe it's time to cleanup?
=> Remove deprecated Route.Shunt

dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/redirect.go, dataclients/kubernetes/testdata/routegroups/https-redirect/custom-code.eskip, dataclients/kubernetes/testdata/routegroups/https-redirect/no-redirect-for-east-west.eskip, dataclients/kubernetes/testdata/routegroups/https-redirect/no-redirect-if-proto-predicate.eskip, dataclients/kubernetes/testdata/routegroups/https-redirect/redirect-implicit-route.eskip, dataclients/kubernetes/testdata/routegroups/https-redirect/redirect-simple.eskip, docs/reference/architecture.md, docs/reference/predicates.md, docs/tutorials/basics.md, eskip/eskip_test.go, eskip/lexer.go, eskip/parser_test.go, eskip/string.go, eskip/string_test.go, predicates/cookie/cookie.go, routing/datasource.go, routing/matcher.go, routing/routing.go, routing/weight_test.go
=> Sync v1 with master

docs/kubernetes/deploy/deployment/rbac.yaml
=> Fix RBAC example

filters/auth/tokenintrospection_test.go, net/httpclient.go
=> reduce the flaky test

etcd/etcdtest/mocketcd.go, filters/builtin/compress_test.go, proxy/lb_failingbackend_test.go, proxy/proxy_test.go, routing/routing_test.go, skipper.go
=> Always close Body

filters/builtin/builtin.go
Remove deprecated unused constant
=> Remove deprecated unused constant

filters/builtin/builtin.go, filters/builtin/inlinecontentifstatus.go, filters/builtin/inlinecontentifstatus_test.go
=> Add `inlineContentIfStatus` filter

proxy/proxy.go
Makes it easier to find the original request.
=> Log flowId on proxy error

docs/reference/filters.md, filters/builtin/builtin.go, filters/xforward/xforward.go, filters/xforward/xforward_test.go
add a filter to support the standard proxy headers explicitly
=> create filter for setting the X-Forwarded-* headers

.github/workflows/ci.yaml
Travis is giving me such a bad time, let's switch to Github Actions.
=> Github Actions

docs/reference/filters.md
document the conditional inline content filter
=> document the conditional inline content filter

filters/sed/editor.go, filters/sed/testdata/wsdl-patched.xml, filters/sed/testdata/wsdl.xml, filters/sed/wsdl_test.go
fix streaming with large read buffers, where the bug is that EOF is returned too early
=> fix streaming documents through the editor

docs/reference/predicates.md, eskip/predicates.go, eskip/predicates_test.go
* Updated docs
* Guard mixing of Method and Methods predicates
=> V1 > Method / Methods

dataclients/kubernetes/ingress.go, dataclients/kubernetes/ingressdefinitions.go, dataclients/kubernetes/kube_test.go
This is nicer than the `True() && True() && True()` hack.
=> V1 > Use Weight predicate to give Traffic more priority

delivery.yaml, packaging/Makefile
=> fix arm docker build targets

packaging/Makefile
=> fix cross compile build command

docs/reference/predicates.md
Please update the docs when this is merged.
=> Docs > Explain `True()` and `False()` predicates

filters/auth/oidc.go
cleanup unused rand data which does not provide value as discussed internally
=> cleanup unused rand data

docs/reference/scripts.md, script/script.go
fix #1426 lua() should have access to host header
=> fix lua() should have access to host header

filters/auth/oidc.go
For each ingress Skipper will hash a new cookie. If several ingresses for the same domain are defined, either by several hosts or sub-paths, it will accumulate cookies on the client browser which can lead to side effects like header limits exceeded or heavy request payloads.
Example which generates several cookies when the annotations are identical besides of the `RedirectURL` parameter. This as of now results into 3 cookies which would not be necessary.:
```
path: "/" --> ingress: portal
path: "/subpathA" --> ingress: serviceA
path: "/subpathB" --> ingress: serviceB
```
There might be better approaches to tackle this issue by specifying the actual path of its ingress on the cookie, however this information is apparently not available at the filter level for now.
This simple approach 
1. …
=> Deduplicate OIDC cookies

docs/index.md
the removed text seemed unnecessary
=> removed extra text

filters/auth/oidc_introspection.go
Turns out the `gjson` internal map access for "modifiers" is not thread safe:
https://github.com/tidwall/gjson/issues/173
It accesses a map unsyncronized causing application crashes during RW operations:
```
fatal error: concurrent map writes
goroutine 4555 [running]:
runtime.throw(0x1041950, 0x15)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc001dc5338 sp=0xc001dc5308 pc=0x434b42
runtime.mapassign_faststr(0xecda00, 0xc000118f60, 0x102fe84, 0x1, 0x0)
/usr/local/go/src/runtime/map_faststr.go:291 +0x3de fp=0xc001dc53a0 sp=0xc001dc5338 pc=0x41375e
github.com/tidwall/gjson.AddModifier(...)
/go/pkg/mod/github.com/tidwall/gjson@v1.4.0/gjson.go:2612
```
This workaround uses `Mutex` semaphores in order to achieve thread safety, that might be slower however as an improvement the write …
=> OIDC-introspection concurrency crashes

secrets/file.go
=> Logs secret update on registerSecretFile

docs/reference/egress.md
=> doc: fix egress example

docs/reference/egress.md
=> add more context in how to use multiple backends as egress targets

docs/kubernetes/routegroup-crd.md
=> Fixing link to the routegroup CRD

docs/kubernetes/routegroups.md
=> doc: fix backend references in RouteGroup examples

docs/kubernetes/routegroups.md
=> doc: fix gradual traffic switching

proxy/proxy.go, skipper.go
Expose ability to wrap http.Handler and http.RoundTripper
when using skipper in library mode. It was previously internal.
This allows to inject additional logic (like tracing) into skipper.
To make this possible also depend on http.RoundTripper interface
internally.
https://github.com/zalando/skipper/pull/1458/commits/ffd302f53a4de9101bade3611ccb0609c833eeb3#diff-3ac192716a1df66bbd1008d327af8792R318
See examples on how it could be used:
https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-go-handler.html
https://docs.newrelic.com/docs/agents/go-agent/instrumentation/instrument-go-transactions#http-handler-txns
=> Allow to wrap http.Handler and http.RoundTripper

loadbalancer/algorithm_test.go
=> add load balancer algorithm tests

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml
=> fix routegroup crd schema for json validation

docs/reference/filters.md
=> doc: add docs to the new logHeaders feature

script/script.go, script/script_test.go
=> Fixes static check

.github/workflows/pr.yaml, filters/auth/oidc.go
=> Adds checks into pull request workflow

dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/lbannotationfilters_test.go, dataclients/kubernetes/lbtarget_test.go, dataclients/kubernetes/lbtrafficswitch_test.go, dataclients/kubernetes/path_test.go, dataclients/kubernetes/update_test.go
=> Fixes 'composite literal uses unkeyed fields' vetoes

config/config.go, logging/log.go, logging/log_test.go, skipper.go
=> Adds flag to output application logs in JSON format

readme.md
Add WAF plugin from [Coraza WAF](https://github.com/jptosso/coraza-waf) to the readme.md plugins section.
=> Add WAF plugin to readme.md

proxy/proxy.go
=> Fixes -insecure flag ignored by upgrade request

docs/reference/filters.md, filters/builtin/builtin.go, filters/tracing/statebagtotag.go, filters/tracing/statebagtotag_test.go
=> add state bag to tag filter

Makefile, cmd/webhook/main.go, packaging/Dockerfile, packaging/Makefile
Making it possible to run the webhook from the skipper image
Signed-off-by: Muaaz Saleem <muhammad.muaaz.saleem@zalando.de>
=> Adding the webhook to packaging

docs/reference/filters.md, eskip/string.go, filters/builtin/builtin.go, filters/fadein/fadein.go, filters/fadein/fadein_test.go, loadbalancer/algorithm.go, loadbalancer/doc.go, loadbalancer/fadein_test.go, logging/loggingtest/logger.go, proxy/fadein_test.go, proxy/fadeintesting_test.go, routing/routing.go, skipper.go, skptesting/analyze_fadein.r, skptesting/run_fadein_test.sh
=> Fadein for new backend endpoints

docs/operation/operation.md, proxy/proxy.go, ratelimit/cluster.go, ratelimit/ratelimit.go, ratelimit/redis.go, skipper.go
- timer metrics for redis communication
- opentracing for redis communication
=> Redis ratelimit monitoring

ratelimit/redis.go
remove the Redis keys from the logs
=> remove the Redis keys from the logs

ratelimit/redis.go
=> do not leak clear text data to redis

docs/kubernetes/routegroups.md
=> Fixes backend references in routegroups documentation

proxy/proxy.go
=> remove package global hostname and set it in proxy creation

dataclients/kubernetes/ingress.go, dataclients/kubernetes/kube_test.go
=> Set HostRegexps for Service of type ExternalName

proxy/proxy.go, proxy/proxy_test.go
=> flush stream to client also on error path

loadbalancer/algorithm.go, loadbalancer/fadein_test.go
use weighted shifting instead of shifting to oldest when there are no available stable endpoints
=> handle the case smoother when all endpoints are fading in

dataclients/kubernetes/ingress.go
=> fix: annotation filter

Dockerfile, packaging/Dockerfile, packaging/Dockerfile.arm, packaging/Dockerfile.arm64
=> update MAINTAINER to LABEL maintainer

proxy/proxy.go, routing/matcher.go
Reverts zalando/skipper#1547
because of https://github.com/zalando/skipper/issues/1575
=> Revert "Normalizes URLs for upstream"

config/config.go, docs/operation/operation.md, skipper.go
=> drop experimental flag from TCP-lifo

dataclients/kubernetes/ingress_test.go, dataclients/kubernetes/ingressdefinitions.go, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport.eskip, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport.yaml, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport2.eskip, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport2.yaml, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport3.eskip, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport3.yaml, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport4.eskip, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport4.yaml, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport5.eskip, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-multiport5.yaml, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-no-match.eskip, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-no-match.yaml, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-same-name.eskip, dataclients/kubernetes/testdata/ingress/named-ports/named-ports-same-name.yaml, dataclients/kubernetes/testdata/ingress/named-ports/named-ports.eskip, dataclients/kubernetes/testdata/ingress/named-ports/named-ports.yaml, dataclients/kubernetes/testdata/ingress/named-ports/numbered-ports-no-match.eskip, dataclients/kubernetes/testdata/ingress/named-ports/numbered-ports-no-match.yaml, dataclients/kubernetes/testdata/ingress/named-ports/ports-without-name.eskip, dataclients/kubernetes/testdata/ingress/named-ports/ports-without-name.yaml
fix #1582 
- [ ] confirm fix
- [ ] cleanup
=> fix bug with service and target port matching

proxy/proxy.go, proxy/upgrade.go
https://github.com/zalando/skipper/issues/1593
=> Remove hijacked connection flush

.github/workflows/pr.yaml
=> tests used old go version

dataclients/kubernetes/ingress.go
=> Set level of log message to debug in case a shuntroute is added

docs/reference/scripts.md, script/script.go, script/script_test.go
* Adds request cookie getter
* Implements request cookie iteration
Fixes #1601
=> Add request cookie support to Lua scripts

.github/workflows/master.yaml, .github/workflows/pr.yaml, swarm/nodeinfo.go, tracing/tracers/basic/basic.go, tracing/tracers/jaeger/jaeger.go
=> fix: security scanner warnings

docs/reference/predicates.md, predicates/source/source.go, predicates/source/source_test.go, skipper.go
=> feature: ClientIP predicate checks only request.RemoteAddr

secrets/encrypter_test.go, secrets/registry.go
Fix for mention in https://github.com/zalando/skipper/pull/1609#discussion_r531738700
=> fix non synced map access in secrets.Registry#GetEncrypter

cmd/webhook/admission/admission.go, ratelimit/ratelimit.go, ratelimit/redis.go, ratelimit/swim.go
=> fix sensitive data in logs found by GH code scanning

filters/builtin/header_test.go
=> Adds tests for case-insensitive name parameter of header filters

proxy/proxy.go, proxy/proxy_test.go
* Removes unreachable branches from net.Error status code mapping
* Splits roundTripper creation (fastcgi) and actual backend round trip
=> Refactors makeBackendRequest error handling

filters/apiusagemonitoring/filter.go, filters/apiusagemonitoring/spec.go
=> fix: filters should not hold reference to spec

.zappr.yaml
we moved the responsibility of the project https://github.com/zalando/skipper/pull/1184
=> we moved the responsibility of the project 

Dockerfile, packaging/Dockerfile
=> Zalando changed its compliant base image

filters/diag/absorb.go, filters/diag/absorb_test.go
* Logs consumed bytes at regular intervals of one second
=> Fixes absorb(Silent) filter spec name

proxy/proxy.go
=> fix: we leak vars to func scope where if scope is enough

Makefile, filters/filters.go, predicates/cookie/cookie.go, predicates/predicates.go
=> fix linter staticcheck -ST1022

loadbalancer/healthchecker.go
These logs report about frequent normal operation, not necessary to print them.
=> cleanup log entries of normal operation in healthcheck postprocessor

proxy/split_test.go, proxy/teebody.go
=> clone the RequestURI field with the request when splitting for loopback

Makefile, config/config.go, config/config_test.go, dataclients/kubernetes/kubernetestest/fixtures.go, etcd/etcdtest/mocketcd.go, filters/diag/diag.go, filters/flowid/standard.go, filters/flowid/ulid.go, loadbalancer/algorithm.go, metrics/codahale.go, predicates/traffic/traffic.go, routing/pathgen/pathgen.go, script/script.go, skipper.go
=> update staticcheck and gosec

skipper.go
Support multiple files in `-routes-file`
=> Support multiple files in `-routes-file`

config/config.go, config/config_test.go
=> simplify min TLS version lookup

docs/reference/filters.md, secrets/file.go
=> fix bearerinjector secrets key docs

proxy/ratelimit_test.go
=> Refactors flaky ratelimit tests

ratelimit/ratelimit.go, ratelimit/ratelimit_test.go
=> ratelimit cannot be set to 0 rate

proxy/tracing.go, proxy/tracing_test.go
See https://github.com/zalando/skipper/issues/1516#issuecomment-748941875
=> Fixes flow id tracing tag name

proxy/proxy.go
Based on discussion in https://github.com/zalando/skipper/issues/1654
=> Changed client canceled error to info log level

readme.md
=> add pkg.go.dev badge

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml
=> doc: kubectl explain routegroups

readme.md
=> Fix slack invite link

docs/kubernetes/routegroup-validation.md, mkdocs.yml
=> RouteGroup validation webhook docs

docs/kubernetes/routegroups.md
fix absolute minimal RG configuration example
=> fix absolute minimal RG configuration example

config/config.go, config/config_test.go, ratelimit/redis.go, skipper.go
=> add redis dial timeout

docs/kubernetes/ingress-controller.md
doc: latest tag was wrong and added more why you should use a versioned tag
=> doc: latest tag was wrong and pitch latest release instead

proxy/proxy.go
`Proxy.errorResponse()` sets `http.status_code` on the OpenTracing span _before_ it actually computes the correct value. This leads to very confusing traces where clients get a 404, but Skipper reports a 500 instead. Fix by computing the response status first.
=> Opentracing: set http.status_code correctly

docs/reference/filters.md
=> add formula with examples on clientRatelimit filter

proxy/proxy.go
=> increase visbility for route not found

routing/routing.go, routing/routing_test.go
=> Wait for multiple dataclients. Fixes #1709

config/config.go, config/config_test.go, config/test.yaml, ratelimit/redis.go, ratelimit/redis_test.go, skipper.go
=> Password support for Redis

loadbalancer/algorithm.go, loadbalancer/algorithm_test.go
=> Improves consistent hash endpoint selection strategy

docs/reference/filters.md, filters/tracing/spanname.go
- document tracing span name filter
- remove experimental flag
=> document tracing span name filter, remove experimental flag

docs/reference/filters.md, eskip/template.go, eskip/template_test.go
=> Adds request method and host template placeholders

filters/tracing/baggagetotag_test.go, filters/tracing/spanname_test.go, filters/tracing/tag_test.go
=> increase tracing filters coverage

skipper.go, skipper_test.go
=> Adds SwarmRegistry callback

docs/reference/predicates.md, predicates/interval/interval.go, predicates/interval/interval_test.go
=> Adds timezone support for interval predicates

config/config.go, net/redisclient.go, net/redisclient_test.go, ratelimit/cluster.go, ratelimit/cluster_test.go, ratelimit/ratelimit.go, ratelimit/redis.go, ratelimit/redis_test.go, ratelimit/registry.go, skipper.go
refactor out redisclient from ratelimit/redis to net package
=> refactor out redisclient from ratelimit/redis to net package

docs/kubernetes/ingress-usage.md
a route groups link was pointing in to one folder up
=> correct path to routegroups

go.mod, go.sum
=> update lightstep tracer lib to fixed merged version

Dockerfile, packaging/Dockerfile
Update to the latest zalando base image based on alpine 3.13
=> Update to latest base image

eskip/fuzz.go
Closes https://github.com/zalando/skipper/issues/945
This PR adds the first fuzzer for skipper.
The fuzzer is implemented by way of go-fuzz.
It will also run continuously through OSS-fuzz, and I will be happy to set up an integration application over there, so it can run continuously. Once integrated, OSS-fuzz will send out notifications if any bugs are found.
=> Add eskip fuzzer

docs/tutorials/auth.md
https://github.com/zalando/skipper/blob/d0b249a4aa8993a050b87cecc11cc6ca839195a4/config/config.go#L607
=> adjust docs according to source code

filters/auth/grant.go, filters/auth/grant_test.go
=> Terminates grant flow on missing tokeninfo subject

filters/auth/oidc_introspection.go, filters/auth/oidc_introspection_test.go, filters/auth/oidc_test.go
=> Supports whitespaces in oidcClaimsQuery strings

docs/reference/filters.md, filters/ratelimit/backendratelimit.go, filters/ratelimit/backendratelimit_test.go, proxy/backendratelimit_test.go, proxy/proxy.go
=> Makes backendRatelimit response code configurable

MAINTAINERS
=> join Alexander

filters/auth/grantlogout.go
=> Fixes grantLogout error logging

docs/reference/filters.md, filters/log/log.go
=> fix wrong regexp

eskipfile/remote.go, eskipfile/remote_test.go
Making RemoteWatchOptions public
=> Make RemoteWachOptions fields public

ratelimit/swim_test.go
=> skip swim test because of flakyness

Makefile
=> update gosec to 2.8

skipper.go
Forgot to register the predicates
=> Register forwarded predicates

docs/tutorials/development.md
=> add some better dev setup tutorial to make you up to speed fast

ratelimit/redis.go
add ratelimit type as Tag to Span, such that we can see what type was used and search
=> add ratelimit type as Tag to Span

config/config.go, go.mod, go.sum, net/redisclient.go, skipper.go
expose hashing algorithm of redis ring client and have extra implementations for rendezvous with vnodes, jump and multi probe consistent hash, defaults to rendezvous without vnodes
=> redis ring client hashing algorithms

docs/reference/backends.md, docs/reference/filters.md, filters/builtin/builtin.go, filters/consistenthash/balancefactor.go, filters/consistenthash/balancefactor_test.go, loadbalancer/algorithm.go, loadbalancer/algorithm_test.go
Implements https://github.com/zalando/skipper/issues/1769
=> Consistent hash bounded load

docs/kubernetes/ingress-usage.md
Couple examples had the indentation wrong.
=> docs: fixed indentation in examples

loadbalancer/algorithm.go, loadbalancer/algorithm_test.go
closes https://github.com/zalando/skipper/issues/1796
=> Improve consistent hash key distribution

filters/auth/oidc_test.go, go.mod, go.sum
GH code scan found that we have a vulnerable library used in a test, so lets fix it
=> GH code scan found a vulnerable test

docs/reference/filters.md
=> fix user docs examples that miss the closing "

logging/loggingtest/logger.go, proxy/backendratelimit_test.go, proxy/backendtimeout_test.go, proxy/clienttimeout_test.go, proxy/tracing_test.go
=> Unmutes testlogger if test verbose output is enabled

cmd/skipper/main.go
=> Adds go runtime version info

docs/operation/operation.md
=> add response serving documentation

filters/tee/teeloopback_test.go, proxy/backendtest/backendrecorder.go, proxy/context.go, proxy/proxy.go, proxy/teebody.go
set the RemoteAddr for the cloned tee loopback requests
=> set the RemoteAddr for the cloned tee loopback requests

mkdocs.yml
=> add external name handling to kubernetes docs

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml
=> fix invalid escape sequence

filters/tee/teeloopback_test.go, proxy/backendtest/backendrecorder.go, proxy/backendtest/backendrecorder_test.go
=> Closes backend recorder test server when done waiting

proxy/proxy.go
=> Fixes stream headers end tracing event

Makefile, packaging/Dockerfile, packaging/Makefile
add routesrv binary to our oss docker image
=> package routesrv

dataclients/kubernetes/testdata/ingress/external-name/all-allowed.yaml, dataclients/kubernetes/testdata/ingress/external-name/external-name-validation-not-enabled.yaml, dataclients/kubernetes/testdata/ingress/external-name/none-allowed.yaml, dataclients/kubernetes/testdata/ingress/external-name/some-allowed.yaml
=> Fixes ingress apiVersion

skipper.go
See
* https://github.com/golang/go/issues/26918
* https://github.com/kubernetes/kubernetes/pull/91277
=> Uses debug log for `http: TLS handshake error ... EOF`

filters/auth/oidc.go, filters/auth/oidc_test.go
Currently, Skipper hard-codes the maxAge of the OIDC cookie to one hour, even if the expiration time of the claim is longer than that. This results in early re-authentication, even though it might not really be necessary yet.
With this change, the exp field is attempted to be parsed. If it's successful, it will use that value as the maxAge for the OIDC cookie.
=> Set OIDC cookie maxAge according to claims exp

go.mod, go.sum
=> Updates github.com/miekg/dns

config/config.go, config/multiflag.go, net/request.go, net/request_test.go
=> Adds support to refuse request that match configured payload

config/config_test.go, config/multiflag.go, config/testdata/test.yaml
=> Fixes multiflag yaml parsing

net/request.go, net/request_test.go
```
$ go test ./net -run NONE -bench BenchmarkMatchesRequest -benchmem -benchtime=10s
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/net
BenchmarkMatchesRequest-8       10136718              1176 ns/op               0 B/op          0 allocs/op
PASS
ok      github.com/zalando/skipper/net  13.125s
```
=> Refactors request matching and adds benchmark

Makefile
=> update gosec and staticcheck

net/httpclient.go, net/httpclient_example_test.go, net/httpclient_test.go
add all options from stdlib to our httpclient net.Client and pass them as is
=> add all options from stdlib to our httpclient 

dataclients/kubernetes/ingressv1.go, dataclients/kubernetes/ingressv1beta1.go
=> add backend type

ratelimit/redis.go, ratelimit/redis_test.go
* moves metric collection outside of ratelimit logic
* uses single tracing span for allow check
* fails early on Redis error
* updates tests to verify result of each `Allow` call
=> ratelimit: refactor AllowContext

proxy/proxy_test.go
=> proxy: refactor backend request retry test

filters/scheduler/lifo.go, filters/scheduler/lifo_test.go
=> filters/scheduler: add error tag to span on lifo error

config/config.go, metrics/metrics.go, skipper.go
=> add: block, mutex, memory profiler configurations

config/config.go, config/config_test.go, docs/kubernetes/ingress-usage.md, docs/reference/filters.md, filters/builtin/compress.go, filters/builtin/compress_test.go, filters/builtin/decompress.go, filters/builtin/decompress_test.go, filters/filters.go, go.mod, go.sum, skipper.go
Adding brotli compression / decompression to skipper
References: https://github.com/zalando/skipper/issues/696
=> Add brotli to skipper

config/config.go, docs/operation/operation.md, proxy/proxy.go, proxy/tracing.go, proxy/tracing_test.go, skipper.go
=> opentracing: add flag to disable creation of filter spans

filters/auth/webhook.go
fix goroutine leak in webhook filter that you can observe if dataclients trigger regular updates and this filter will be recreated. A common fix is the way tokeninfo caches the authclient by target
=> fix goroutine leak in webhook filter

go.mod, go.sum
=> update depencies to fix dependabot alerts

queuelistener/listener.go, queuelistener/listener_test.go
=> queuelistener: measure accept latency

docs/reference/filters.md
=> doc: latency() can also fed with time.Duration string

Makefile
=> Install `gover` via go install

dataclients/kubernetes/ingressdefinitions.go, dataclients/kubernetes/testdata/routegroups/convert/routegroup-with-ipv6-backend.eskip, dataclients/kubernetes/testdata/routegroups/convert/routegroup-with-ipv6-backend.yaml
fix https://github.com/zalando/skipper/issues/1997
=> fix ipv6 concat port to ip address string

docs/reference/architecture.md, docs/tutorials/basics.md
=> docs: fixes weight predicate link anchor

readme.md
=> chore: add slack channel in badges for more reachability

config/config.go, net/headers.go, net/headers_test.go
feature: add xff headers that are required by authelia, see also https://github.com/authelia/authelia/issues/3492
=> feature: add xff headers that are required by authelia

cmd/webhook/main.go, routesrv/routesrv.go
=> gosec: configure http.Server timeouts to fix G112

SECURITY.md
=> update vulnerability report link

docs/tutorials/basics.md
=> doc: route creation

skipper.go
=> feature: add cgroup v2 memory limit detection

Makefile
=> build static binary as make target

mkdocs.yml
=> enable math rendering

docs/reference/filters.md
=> doc: fix markdown list

routing/datasource.go
refactor: replace hardcoded predicate name
=> Fixed hardcoded predicate name

proxy/proxy.go, proxy/proxy_test.go
=> proxy: pass url via request context

config/routechangerconfig.go, config/routechangerconfig_test.go, docs/operation/operation.md
Change -edit-route and -clone-route to support arbitrary pattern separator
=> Custom separator edit route

docs/reference/filters.md
=> docs: fix clusterClientRatelimit typo

.github/workflows/master.yaml, Makefile, delivery.yaml
=> enable govulncheck

docs/reference/filters.md, filters/builtin/builtin.go, filters/builtin/mod_header.go, filters/builtin/mod_header_test.go, filters/filters.go
=> Added modResponseHeader filter

go.mod, go.sum
=> fix govulncheck reported issue

dataclients/kubernetes/clusterstate_test.go
=> Added some performance tests for cachedEndpoints

predicates/query/query_test.go
=> test: query predicate add more error cases

loadbalancer/algorithm.go
Followup on https://github.com/zalando/skipper/pull/2087
=> gosec: ignore use of weak random number generator

config/config.go, config/config_test.go, filters/builtin/builtin.go, skipper.go, skipper_test.go
=> Allow to selectively disable filters

dataclients/kubernetes/ingress.go, dataclients/kubernetes/ingressv1.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kubernetestest/fixtures.go, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-default-backend-and-force-k8s-service-flag-enabled.eskip, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-default-backend-and-force-k8s-service-flag-enabled.kube, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-default-backend-and-force-k8s-service-flag-enabled.yaml, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-label-selector-filter-and-force-k8s-service-flag.eskip, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-label-selector-filter-and-force-k8s-service-flag.kube, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-label-selector-filter-and-force-k8s-service-flag.yaml, dataclients/kubernetes/testdata/ingressV1/ingress-data/lb-traffic-switch-and-force-k8s-service-flag.eskip, dataclients/kubernetes/testdata/ingressV1/ingress-data/lb-traffic-switch-and-force-k8s-service-flag.kube, dataclients/kubernetes/testdata/ingressV1/ingress-data/lb-traffic-switch-and-force-k8s-service-flag.yaml, docs/kubernetes/ingress-controller.md, routesrv/options.go, routesrv/routesrv.go, skipper.go
PR relating to issue https://github.com/zalando/skipper/issues/2089
=> Add an option to override the routing via services instead of endpoints

docs/kubernetes/ingress-controller.md
change copied from https://github.com/zalando/skipper/pull/2056/
=> doc:update document for ingress-v1 support feature

docs/reference/filters.md
=> doc: group filters reference, such that you can navigate more easily

net/httpclient_example_test.go
Updates https://github.com/zalando/skipper/issues/2102
=> net: add custom open tracing tag example

.github/workflows/master.yaml, .github/workflows/pr.yaml, delivery.yaml, go.mod
=> Update build to Go 1.19

loadbalancer/fadein_test.go
- Adds an array of keys which can be used to select each backend endpoint one by one for consistent hash, emulating round robin.
- Increases the tolerance, I saw failures locally for random and round robin too
=> Improve reliability of fadein test

routesrv/eskipbytes.go, routesrv/routesrv_test.go, routing/routing.go, routing/routing_test.go
=> feature: routesv HEAD response with X-Count header

config/config.go, config/config_test.go, docs/reference/scripts.md, script/module.go, script/options_test.go, script/script.go, script/script_test.go, skipper.go
=> lua: add flag to selectively enable modules and symbols

proxy/proxy.go
=> proxy: add request host to error log

routing/routing.go
=> doc: remove eperimental entry for Pre/PostProcessors

delivery.yaml
=> build: remove unbound variable check

ratelimit/redis.go
=> add context if ratelimit allows/denies to the span as Tag

config/config.go, routesrv/options.go, routesrv/polling.go, routesrv/routesrv.go, routesrv/routesrv_test.go, routesrv/testdata/lb-target-multi-with-edit-route.eskip
Follow up on https://github.bus.zalan.do/pg9/issues/issues/33
Right now CloneRoute testcase fail but we really care now about EditRoute. So to follow up on CloneRoute check here https://github.com/zalando/skipper/pull/2132
=> Add EditRoute flag to RouteSRV

readme.md
doc: binary vs source install
refactor: godoc.org -> pkg.go.dev
doc: add blogposts from opensource.com
=> doc: readme changes

eskip/eskip.go, eskip/eskip_test.go, routesrv/testdata/lb-target-multi-with-clone-route.eskip
fixes https://github.com/zalando/skipper/issues/2134
=> Refactor `CloneRoute` testcase

eskip/eskip.go, eskip/eskip_test.go, routesrv/routesrv_test.go, routesrv/testdata/lb-target-multi-with-clone-route.eskip
Follow up on https://github.com/zalando/skipper/pull/2131
=> Add CloneRoute testcase to RouteSRV

.github/workflows/pr.yaml
Adding `gokart` job in the CI as an additional security scanner.
Reference: https://github.com/zalando/skipper/issues/1894
=> Add gokart job in CI

dataclients/routestring/string_test.go, eskip/eskip_test.go, eskipfile/remote_test.go, go.mod, go.sum
=> refactor: replace litter with cmp

filters/shedder/admission.go, go.mod, scheduler/scheduler.go
Addresses https://github.com/zalando/skipper/issues/2064
Signed-off-by: noor <noormuhammadmalik95@gmail.com>
=> Refactor go.uber.org/atomic to sync/atomic

eskipfile/main_test.go, eskipfile/remote.go, eskipfile/remote_test.go, eskipfile/watch.go, filters/builtin/compress_test.go, filters/builtin/creationmetrics_test.go, filters/builtin/header_test.go, filters/builtin/main_test.go, filters/builtin/redirect_test.go, filters/diag/main_test.go, filters/ratelimit/fail_closed_test.go, filters/ratelimit/main_test.go, filters/scheduler/fifo_test.go, filters/scheduler/lifo_test.go, filters/scheduler/loopback_test.go, filters/scheduler/main_test.go, filters/tee/main_test.go, filters/tee/teeloopback_test.go, proxy/proxytest/proxytest.go, routing/datasource_test.go, routing/example_test.go, routing/main_test.go, routing/predicates_test.go, routing/routing_test.go, routing/subtreeconflict_test.go, routing/testdataclient/dataclient.go, routing/tree_test.go, secrets/main_test.go
Adds `main_test.go` with `noleak.CheckMain(m)` into more packages and fixes leaks in tests.
=> Fixes goroutine leaks in tests

net/redisclient.go, proxy/backendtimeout_test.go, proxy/fadeintesting_test.go, proxy/longpoll_test.go, proxy/loopback_test.go, proxy/main_test.go, proxy/proxy_test.go, proxy/ratelimit_test.go, proxy/upgrade_test.go
=> proxy: fix goroutine leaks in tests

.gitignore, docs/data-clients/eskip-file.md, docs/data-clients/eskip-remote.md, docs/data-clients/example.eskip, docs/tutorials/basics.md, mkdocs.yml
=> docs: add remote eskip example

.github/workflows/codeql-analysis.yml, .github/workflows/gh-packages.yaml
Follow up on https://github.com/zalando/skipper/issues/2114
=> Fix workflows permissions

filters/auth/grantconfig.go, filters/auth/grantconfig_test.go, secrets/file.go
=> filters/auth: handle SecretProvider errors in OAuthConfig

filters/block/block_test.go, filters/block/main_test.go
test: block filter better coverage
=> test: block filter better coverage

net/redisclient_test.go
=> net: fix flaky TestRedisClient/With AddrUpdater

proxy/proxy.go
=> refactor: drop else, which is not needed

net/httpclient.go, proxy/proxy.go
related issues:
- https://github.com/open-telemetry/opentelemetry-go/issues/2314
- https://github.com/golang/protobuf/issues/1228
=> fix: invalid utf-8 in grpcmessage

swarm/swarm.go
fix: https://github.com/zalando/skipper/issues/2182
=> fix: missleading log messagein swarm

config/config.go, config/config_test.go, filters/auth/oidc.go, filters/auth/oidc_test.go, skipper.go
expose cookie validity as config
fix https://github.com/zalando/skipper/issues/2157
TODO:
=> expose cookie validity as config - fix #2157

config/config.go, docs/reference/filters.md, skipper.go
=> skipper: create OIDC filters only when -oidc-secrets-file is provided

proxy/proxy.go, proxy/tracing.go
=> ensureutf8 on all strings that are passed to tracer

ratelimit/ratelimit.go, ratelimit/ratelimit_test.go
=> test: ratelimit abstractions and lookuper coverage

filters/ratelimit/ratelimit.go, filters/ratelimit/ratelimit_test.go, go.mod, go.sum, proxy/proxy.go, ratelimit/ratelimit.go, ratelimit/ratelimit_test.go, ratelimit/redis.go, ratelimit/redis_test.go, ratelimit/registry.go, ratelimit/swim.go, ratelimit/swim_test.go
fixes https://github.com/zalando/skipper/issues/2136
Ran tests local with check removed and worked fine.
=> Remove `nil` check for ctx

docs/reference/predicates.md, predicates/content/content_length_between.go, predicates/content/content_length_between_test.go, predicates/predicates.go, skipper.go
it should help to route requests based on content length header value
coauthored: @a1exsh
=> content length header predicate

dataclients/kubernetes/kube.go, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-duplicate-host-different-path.eskip, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-duplicate-host-different-path.yaml, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-duplicate-host-different-service.eskip, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-duplicate-host-different-service.yaml, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-duplicate-host.eskip, dataclients/kubernetes/testdata/ingressV1/ingress-data/ing-with-duplicate-host.yaml, dataclients/kubernetes/testdata/routegroups/examples/duplicate-host.eskip, dataclients/kubernetes/testdata/routegroups/examples/duplicate-host.yaml
Updates https://github.bus.zalan.do/pg9/issues/issues/33
=> Remove duplicate host routes from k8s dataclient

filters/shedder/admission.go
=> visibility: expose ok/deny counters in admissionControl filter

docs/reference/filters.md, docs/tutorials/auth.md, filters/auth/grantlogout.go, filters/auth/grantlogout_test.go
=> filters/auth: fix grantLogout when token revocation is disabled

Makefile, filters/auth/oidc_test.go, filters/builtin/compress_test.go, proxy/idle_test.go
=> Fix Makefile to pass CDP check for go1.20

filters/diag/diag_test.go
test: fix flaky test in uniformLatency and normalLatency diagnostics filters
=> test: fix flaky test in uniformLatency and normalLatency diagnostics filters

filters/auth/bearer_test.go, filters/auth/grant_test.go, filters/auth/grantclaimsquery_test.go, filters/auth/main_test.go, filters/auth/oidc_introspection_test.go, filters/auth/oidc_test.go, filters/auth/tokeninfo_test.go, filters/auth/tokeninfocache_test.go, go.mod, go.sum, net/dnstest/dnstest.go
* fixes leak in dnstest
* cleans up global auth clients after tests
=> filters/auth: check goroutine leaks

secrets/file.go
=> secrets: log updates only when content changes

docs/reference/filters.md, filters/builtin/builtin.go, filters/diag/diag.go, filters/diag/wrap_test.go, filters/filters.go
=> filters: add wrapContent

docs/operation/operation.md, net/redisclient.go
feature: expose number of known redis shards
=> feature: expose number of known redis shards

config/config.go, config/config_test.go, filters/auth/grant.go, filters/auth/grant_test.go, filters/auth/grantconfig.go, skipper.go
=> filters/auth/grant: configurable tokeninfo keys

.github/workflows/pr.yaml
See https://github.com/praetorian-inc/gokart/issues/88
=> build: fix go version for gocart

docs/reference/filters.md, filters/apiusagemonitoring/spec.go
=> Improve apiUsageMonitoring filter logging

cmd/webhook/admission/admission_test.go
This is a preparation for removing kubernetes dependency
* remove encoding/decoding tests as it is covered by RouteGroupAdmitter test
* use literal json test input and output
=> webhook: refactor test

config/config.go, config/config_test.go
Such change makes skipper and routesrv configuration more incapsulated, os.Args slice is not used directly in tests any more.
Updates #2175
=> Use flags.FlagSet to increase testability

secrets/file_test.go
Refactors secrets file tests into multistep scenarios.
For https://github.com/zalando/skipper/issues/1858
=> secrets: refactor file tests

secrets/file.go, secrets/file_test.go
Updates https://github.com/zalando/skipper/issues/1858
=> secrets: do not log subdirectory read errors

go.mod, go.sum
=> indirect dependency with CVE-2023-27561 update

config/listflag.go, config/listflag_test.go
=> skipper: fix handling of empty value in listFlag

docs/reference/scripts.md
=> doc: -lua-sources

script/script_test.go
Related to https://github.com/zalando/skipper/pull/2269
=> script: use filtertest context in tests

proxy/context.go
Followup on https://github.com/zalando/skipper/pull/2269
=> proxy: cache context logger

docs/data-clients/eskip-file.md, docs/kubernetes/external-addresses.md, docs/kubernetes/ingress-controller.md, docs/kubernetes/routegroup-crd.md, docs/kubernetes/routegroup-validation.md, docs/kubernetes/routegroups.md, docs/operation/operation.md, docs/reference/backends.md, docs/reference/development.md, docs/reference/plugins.md, docs/tutorials/auth.md, docs/tutorials/basics.md, docs/tutorials/common-use-cases.md, docs/tutorials/development.md, docs/tutorials/operations.md, docs/tutorials/shadow-traffic.md
Signed-off-by: Bartosz Ocytko <bocytko@gmail.com>
=> Adds missing shell, yaml formatting to code blocks

.github/workflows/docs.yaml
Related to https://github.com/zalando/skipper/issues/2278
=> Automate docs deployment

docs/reference/filters.md, filters/builtin/builtin.go, filters/builtin/timeout.go, filters/builtin/timeout_test.go, filters/filters.go, filters/filtertest/filtertest.go, logging/loggingwriter.go, proxy/context.go, proxy/proxy.go
feature: read timeout filter and write timeout filter
=> feature: read timeout filter and write timeout filter

.github/workflows/codeql-analysis.yml, .github/workflows/docs.yaml, .github/workflows/gh-packages.yaml, .github/workflows/master.yaml, .github/workflows/pr.yaml
fix: use best practice from openssf and use pinned dependencies in gh actions
=> fix: use pinned dependencies in gh actions

eskipfile/file_test.go
test: increase coverage of eskipfile package to >80%
=> test: increase coverage of eskipfile package to >80%

.github/dependabot.yml
automation: dependabot for gh action and go modules
=> automation: dependabot for gh action and go modules

.github/workflows/docs.yaml
Follow up https://github.com/zalando/skipper/pull/2291
=> Duplicate permissions block

.github/workflows/docs.yaml
follow up on https://github.com/zalando/skipper/pull/2300
=> Use local permissions to fix openssf

readme.md
fix: build status badge
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
=> fix: build status badge

readme.md
fix: status badge link to GH action
=> fix: status badge link to GH action

docs/reference/filters.md, filters/block/block.go, filters/block/block_test.go, filters/filters.go, skipper.go
feature: `blockContentHex("deadbeef", "00a0")` filter
=> feature: blockContentHex filter

.github/workflows/codeql-analysis.yml, .github/workflows/docs.yaml, .github/workflows/gh-packages.yaml, .github/workflows/openssf-scorecard.yaml, .github/workflows/pr.yaml
pipeline: do not run expensive action on dependabot PRs
=> pipeline: do not run expensive action on dependabot PRs

.github/workflows/codeql-analysis.yml, .github/workflows/docs.yaml, .github/workflows/gh-packages.yaml, .github/workflows/openssf-scorecard.yaml
=> fix: gh action syntax error

.github/workflows/master.yaml, Makefile
tool: osv vulnerability scanner
https://github.com/zalando/skipper/security/code-scanning/110 suggest to add this and https://osv.dev/ looks like it makes sense to use as it is OpenSSF related project
=> tool: osv vulnerability scanner

predicates/traffic/segment_test.go
Follow up on https://github.com/zalando/skipper/pull/2287
=> predicates/traffic: fix racy test

dataclients/kubernetes/testdata/routegroups/convert/service-with-lb-algorithm.eskip, dataclients/kubernetes/testdata/routegroups/convert/service-with-lb-algorithm.yaml
test: add test to make sure that you can use lb algorithm with service
=> test: add test to make sure that you can use lb algorithm with service

Makefile
Make without target should run build.
Followup on #2325
=> build: fix default make target

etcd/etcdtest/mocketcd.go
etcd stores its data in the `data-dir`. If this directory is not explicitly specified as a parameter, etcd creates a directory `default.etcd` in the directory where the etcd process is started.
When the Skipper etcd tests begin, the directory `default.etcd` is created by etcd for storing its data but it is not deleted after the etcd process is terminated.
During subsequent tests in the same environment, Skipper would receive routes from previous tests because of the preserved data in etcd and by calling `etcdGetUpdates()` (using `etcdIndex` and `waitIndex`).
This causes the tests to behave unexpectedly.
This patch creates a temporary `data-dir` before starting etcd and makes sure that it is deleted after the tests.
This way the tests are always running with an empty etcd in a defined …
=> test: use and clean up temporary etcd data directory

metrics/metrics.go
refactor: simplify metrics path handling
=> refactor: simplify metrics path handling

predicates/traffic/segment_test.go
TrafficSegment predicate has a weight of -1 and thus does not affect final route weight.
This test verifies that requests with a specific header do not match routes with TrafficSegment despite the same number of predicates.
=> predicates/traffic: add TrafficSegment route test

loadbalancer/fadein_test.go, skptesting/analyze_fadein.r
=> Added comments in loadbalancer/fadein_test.go

loadbalancer/fadein_test.go
=> Make fadeIn tests more stable

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml
=> crd: update RouteGroup CRD

docs/tutorials/built-your-own.md, mkdocs.yml
docs: tutorial built your own proxy
close https://github.com/zalando/skipper/issues/2283
=> docs: tutorial built your own proxy

docs/tutorials/development.md
Fix documentation, see: https://github.com/zalando/skipper/issues/2280
=> fix: new filter creation examples

go.mod, go.sum, net/httpclient.go, net/httpclient_test.go
noleak update is a noop really, see https://github.com/AlexanderYastrebov/noleak/commit/d13f4619f090cd43af78a36f53b6a9b417cd59e3
=> net: close idle connections on Transport.Close

eskip/fuzz_test.go
=> add build tag to run oss-fuzz

docs/reference/backends.md, docs/reference/filters.md
=> docs: note that powerOfRandomNChoices does not support fadeIn

filters/auth/authclient.go, filters/auth/tokeninfo_test.go
fixes https://github.com/zalando/skipper/issues/2140
=> auth: log if http status code is 5xx

docs/tutorials/ratelimit.md
**Notes**
- Rate limit docs update
=> docs/ratelimit.md > add missing double quotes

docs/reference/predicates.md
=> docs/predicates: add TRACE method

net/redistest/redistest.go
=> Move net/redistest skip deadline

.gitignore
=> .gitignore: remove oauth/

delivery.yaml
doc: release should contain the multiarch build and remove outdated arm64/armv7 builds
=> doc: release should contain the multiarch build and remove outdated arm64/armv7 builds

routesrv/eskipbytes.go, routesrv/polling.go, routesrv/routesrv_test.go
* log and change route update metric only when routes changed
* speedup tests from 20s to 2.5s by reducing poll interval
=> routesrv: log route updates only when changed

routesrv/routesrv_test.go
Due to missing rs.StopUpdates() finished tests continue to write to the shared test log which could be observed as a lot of "failed to fetch routes" messages.
If k8s api server of the current test happens to start on the same port as the server from the previous test then current test would react on the log messages produced by the route server of the previous test and may fail sporadically.
The better fix would be to get rid of the shared test logger but this requires larger refactoring and could be done later.
=> routesrv: fix flaky TestESkipBytesHandlerWithStaleEtag and others

.github/dependabot.yml
=> build: update dependabot configuration

filters/auth/webhook_test.go
=> fix: flaky test webhook

proxy/proxy_test.go
=> proxy: fix flaky TestResponseHeaderTimeout

delivery.yaml
=> build: remove unused variables from delivery.yaml

dataclients/routestring/example_test.go, proxy/backendtimeout_test.go
Increase delays in flaky tests.
Fixes #2544
=> all: fix flaky tests

filters/diag/absorb_test.go
Instead of waiting for each match to timeout wait for a single unexpected match.
Before:
```
$ go test ./filters/diag/ -count=1
ok      github.com/zalando/skipper/filters/diag 22.729s
```
After:
```
ok      github.com/zalando/skipper/filters/diag 7.836s
```
=> filters/diag: speedup TestAbsorbSilent

packaging/Dockerfile
This reverts commit 392dc7ec6e178e01ad79324684cd445efc72bb96.
=> Revert "packaging: update Dockerfile (#2563)"

delivery.yaml
=> deploy: do not mangle markdown in release notes

ratelimit/redis.go
We observed that error message is not logged as part of span. This PR introduces sampled logging for redis errors.
Fixes https://github.com/zalando/skipper/issues/1546
=> Add sampled error logging for redis errors

routing/endpointregistry.go, routing/endpointregistry_test.go
Clean up removed endpoints in endpointregistry
=> Clean up removed endpoints in endpointregistry

delivery.yaml
=> build: remove Co-authored-by from release notes

routesrv/polling.go
Log route changes for debugging
=> routesrv: log route changes for debugging

routesrv/eskipbytes.go, routesrv/polling.go
=> routesrv: log etag on routes update

routesrv/redishandler.go
=> routesrv: use debug log level for Redis updater

.github/workflows/master.yaml, Makefile, delivery.yaml
Towards #2598 
Adds [capslock](https://github.com/google/capslock) to highlight capabilities of Skipper's dependencies.
Output of `make capslock` attached: [capslock-skipper-output.log](https://github.com/zalando/skipper/files/12724961/capslock-skipper-output.log)
=> Add capslock for capability check

filters/fadein/fadein_test.go
Check endpointregistry Detected field in CI tests
=> Check endpointregistry Detected field in CI tests

cmd/routesrv/main.go
=> routesrv: enable logs in JSON format

filters/diag/histogram_test.go
=> Fix flaky TestHistogramRequestLatency 

proxy/shadow_test.go
test: add shadow traffic tests
=> test: add shadow traffic tests

delivery.yaml
drop: gosec from blockin build in CI pipeline
=> drop: gosec from blockin build in CI pipeline

.github/workflows/gh-packages.yaml, .github/workflows/master.yaml, .github/workflows/pr.yaml
update setup-go action, not sure why this was not updated by dependabot, last week there were updates of some actions.
https://github.com/actions/setup-go/compare/93397bea11091df50f3d7e59dc26a7711a8bcfbe...bfd2fb341f32be7281829126376a12a780ca79fc
=> update setup-go action

cmd/webhook/admission/admission_test.go, dataclients/kubernetes/definitions/routegroupvalidator.go, dataclients/kubernetes/definitions/testdata/errorwrapdata/errors.log
follow up on https://github.com/zalando/skipper/pull/2691
=> Use `%q` instead of `%s` for strings with quotes

Makefile
fix: master build using flaky tests
=> fix: master build using flaky tests

readme.md
=> fix: coverage badge

eskip/fuzz.go
fix: gofuzz integration for oss-fuzz
=> fix: gofuzz integration for oss-fuzz

docs/data-clients/kubernetes.md, docs/kubernetes/ingress-controller.md, readme.md
doc: update readme and docs to fit the current skipper project
=> doc: update readme and docs to fit the current skipper project

filters/diag/logheader_test.go
test: increase test coverage for logHeader and test truncate authorization header
=> test: increase test coverage for logHeader and test truncate authorization header

.github/dependabot.yml, fuzz/Dockerfile
=> scorecard: pin dependencies as sugested by OpenSSF scorecard

filters/tracing/statebagtotag_test.go
Followup on https://github.com/zalando/skipper/pull/2775
=> filters/tracing: add allocations test for stateBagToTag

predicates/auth/headersha256.go
* fix array conversion that was necessary due to https://github.com/golang/go/issues/46505
* preallocate slice
=> predicates/auth: fix array conversion

go.mod, go.sum
bundled update Go dependencies
=> update Go dependencies

docs/reference/filters.md
=> Fixed the typo in clusterRatelimit filter docs

circuit/ratebreaker.go, circuit/registry.go, filters/diag/diag.go, loadbalancer/algorithm.go, proxy/fadeintesting_test.go, proxy/proxy_test.go, secrets/certregistry/certregistry.go
=> refactor: name mutexes consistently

filters/auth/jwt_validation.go, filters/auth/oidc_introspection.go, proxy/backendtest/backendrecorder.go, secrets/encrypter.go
=> refactor: name RW mutexes consistently

filters/diag/logbody.go
=> filters/diag/logbody: use correct calculation of bytes left to log

filters/filtertest/filtertest.go
Lounge by Zalando requires the capability to easily mock `OriginalRequest` in their unit tests.
=> minor: Added OriginalRequest to the filter test utils

.github/workflows/codeql-analysis.yml
follow up of: https://github.com/zalando/skipper/pull/2850
=> fix codeql error v2

filters/block/block.go
follow up from https://github.com/zalando/skipper/pull/2828
=> refactor: pkg alias to skpio instead of io

net/net.go, net/net_test.go
=> fix: 2852 unspecified addresses should fail

loadbalancer/fadein_test.go
The amount of request is good enough for tests to be stable (not flaky).
```
$ R -q -e "x <- read.csv('/tmp/nums.txt', header = F); summary(x); sd(x[ , 1])"
> x <- read.csv('/tmp/nums.txt', header = F); summary(x); sd(x[ , 1])
V1        
Min.   :176653  
1st Qu.:233142  
Median :249576  
Mean   :278887  
3rd Qu.:340053  
Max.   :538605  
[1] 67193.54
> 
> 
```
```
$ go test ./loadbalancer/ -run=^TestFadeIn$ -count=100 -timeout=1h
ok  	github.com/zalando/skipper/loadbalancer	854.949s
$ go test ./loadbalancer/ -run=^TestFadeIn$ -count=25 -timeout=1h -race
ok  	github.com/zalando/skipper/loadbalancer	1101.778s
```
=> Make TestFadeIn send number of reqs which is close to predefined constant

routing/endpointregistry.go, routing/endpointregistry_test.go, routing/export_test.go
https://github.com/zalando/skipper/pull/2823#discussion_r1450672228
=> Fixed EndpointRegistry.Do method to do nothing for unrelated backend types

proxy/proxy.go
Keep `max loopbacks reached` part of the error message intact in case someone greps logs for it.
=> proxy: add last route id to the 'max loopbacks reached' error

docs/reference/filters.md
Followup on #2203
Followup on #2244
Followup on #2457
Updates #2898
=> docs: describe additional oauthGrant flags

.github/workflows/master.yaml
see also https://github.com/google/capslock/issues/87
=> build: fix go1.22 issue with capslock

filters/builtin/comment.go
Also use value receiver for empty struct type.
Followup on #2905
Alternative to #2909
=> filters/builtin: do not allocate filter slice

proxy/backendtest/backendrecorder_test.go
Wait for test requests to complete before closing the recorder server via Done().
Fixes #2723
=> proxy/backendtest: fix flaky TestServerShouldCloseWhenAllRequestsAreFulfilled

filters/auth/grant_test.go, filters/auth/grantclaimsquery_test.go, filters/auth/grantcookie_test.go, filters/auth/grantlogout_test.go
* pass testing.T to simplify error handling
* return multiple cookies
For #2953
=> filters/auth: refactor grant test token cookie

docs/tutorials/auth.md
=> docs: fix list rendering

fuzz/Dockerfile
fix: go fuzzer build
test fuzzer run, maybe it works
=> fix: go fuzzer build

loadbalancer/algorithm.go, proxy/healthy_endpoints_test.go
Fixed PHC for consistentHash with balance factor and made unit test cover this type of load balancing as well.
=> Fixed PHC for consistentHash with balance factor

docs/operation/operation.md, proxy/healthy_endpoints.go, proxy/healthy_endpoints_test.go, proxy/proxy.go
related to https://github.com/zalando/skipper/issues/2346
=> phc: add a metric counter for endpoints that opted out before load balancing

proxy/proxy.go
Use setTag helper to enable tag exclusion
This is follow up fix for #3039
=> proxy: use proxy tracing setTag helper

ratelimit/redis.go
add span logs for redis spans with error
=> add span logs for redis spans with error

docs/operation/operation.md
=> Fix PHC documentation rendering

docs/reference/filters.md
=> docs: clarify jwtMetrics opt-out logic

proxy/healthy_endpoints_test.go
followup on https://github.com/zalando/skipper/pull/3058
Tried to add test case for all unhealthy but was a little bit complicated, maybe will give another try later.
=> phc: refactor testcases

docs/kubernetes/ingress-usage.md
doc: fix supported service types
=> doc: fix supported service types

docs/kubernetes/deploy/daemonset/daemonset.yaml, docs/kubernetes/deploy/deployment/deployment.yaml, docs/tutorials/basics.md, docs/tutorials/operations.md, packaging/helm/skipper-aws/templates/skipper/deployment.yaml
=> docs: cleanup deprecated -lb-healthcheck-interval flag

CONTRIBUTING.md
doc: mention DCO and what to do in your commit
=> doc: mention DCO and what to do in your commit

.github/dependabot.yml
=> dependabot: group GoLang dependencies update

dataclients/kubernetes/clusterclient.go, dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/multiple-endpointslices-one-unset.eskip, dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/multiple-endpointslices-one-unset.kube, dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/multiple-endpointslices-one-unset.yaml, dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/single-endpointslices-unset.eskip, dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/single-endpointslices-unset.kube, dataclients/kubernetes/testdata/ingressV1/service-ports-endpointslices/single-endpointslices-unset.yaml
fix #3151 unset ports in endpointslices should not be considered in our lb members list
=> fix: unset ports in endpointslices

docs/reference/filters.md
There is not forwardTokenPart filter.
=> docs: fix filter name

.zappr.yaml
This is required by COMPR checker.
=> .zappr.yaml: configure repository type

docs/reference/filters.md
=> docs/reference/filters: fix typos

config/config.go, filters/apiusagemonitoring/spec.go, filters/tls/pass_client_test.go, swarm/swarm.go
pipeline link: https://github.com/zalando/skipper/actions/runs/10387833964/job/28762375336\?pr\=3188
=> staticcheck: fix pipeline errors

go.mod
fix: test requires Go version 1.22
=> fix: test requires Go version 1.22

docs/reference/filters.md, filters/builtin/builtin.go, filters/filters.go, filters/tracing/tag.go, filters/tracing/tag_test.go
feature: add filter that sets a span tag on response status condition
=> feature: add filter that sets a span tag on response status condition

.github/workflows/gh-packages.yaml
Remove redundant quotes.
Follow up on #3251 (https://github.com/zalando/skipper/pull/3251#discussion_r1779403233)
=> github: fix org.opencontainers.image.vendor image label

docs/kubernetes/ingress-usage.md
highlight how `zalando.org/skipper-predicate` & `zalando.org/skipper-routes` work together
=> docs: add some info about annotations

docs/reference/filters.md
Add a note about the flag to `preserveHost` filter docs.
=> docs: add a note about -proxy-preserve-host flag

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml
Update CRD to include:
* https://github.com/szuecs/routegroup-client/pull/38
* https://github.com/szuecs/routegroup-client/pull/41
=> dataclients/kubernetes: update RouteGroup CRD

etcd/install.sh
install.sh: updated checksum validation to make it compatible with all OS
=> install.sh: updated checksum validation 

config/config.go
config: enable KubernetesForceService
1. updated config to enable KubernetesForceService
updates: https://github.com/zalando/skipper/issues/3477
=> config: enable KubernetesForceService

go.mod, logging/log_test.go, script/script.go, swarm/swarmtest/swarmtestutil.go
see also https://osv.dev/vulnerability/GO-2025-3749
https://osv.dev/vulnerability/GO-2025-3750
https://osv.dev/vulnerability/GO-2025-3751
=> fix: go vulnerabilities that lead to broken master build

filters/apiusagemonitoring/spec.go
fix: creation of apiUsageMonitoring filter is costly so cache filter creation based on args
```
% benchstat old.txt new.txt
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/filters/apiusagemonitoring cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
│     old.txt     │               new.txt               │
│     sec/op      │   sec/op     vs base                │
_CreateFilter_FullConfigSingleApiNakadi-16   452971.0n ± 36%   670.7n ± 1%  -99.85% (p=0.000 n=10)
│    old.txt    │               new.txt                │
│     B/op      │     B/op      vs base                │
_CreateFilter_FullConfigSingleApiNakadi-16   49.322Ki ± 0%   1.125Ki ± 0%  -97.72% (p=0.000 n=10)
│    old.txt    │              new.txt               │
│   allocs/op   │ allocs/op   vs base                │ …
```
=> fix: cache apiUsageMonitoring filter creation based on args

docs/operation/operation.md
doc: correct scaling description
=> doc: correct scaling description

docs/operation/operation.md
=> docs: phc not expermintal anymore

routing/datasource_test.go
- Add helper functions to wait for async metrics updates in Prometheus and MockMetrics tests
Fixed https://github.com/zalando/skipper/issues/3589
=> routing: fix race condition in metric tests

predicates/auth/jwt_test.go
test: add testcase for the idea that the cache would have been shared but it is cached per predicate so fine
=> test: add testcase for a wrong assumption I made in standup

predicates/auth/jwt.go
fix: jwt predicates with regexp cached on create https://github.com/zalando/skipper/issues/3609.
Routing table updates are frequently in skipper. We assume every 3s a rebuild of the routing tree. Therefore a leak in objects like predicate creation can visibly leak memory. As written in https://github.com/zalando/skipper/issues/3609 and mentioned in https://github.com/zalando/skipper/pull/3600/files\#r2313466897 we appended unbounded and never cleand up predicates in the registry Now we use a map to also cache creation of the predicate to not grow unbounded and this also speedsup predicate creation and reduces number of objects, so allocations and memory if the same eskip.Predicate string would be used often.
Implementation of course do not change the hot path:
```
% benchstat old.txt …
```
=> fix: jwt predicates with regexp cached on create.
