.gitignore, filters/noop/noop_test.go, filters/requestheader/requestheader_test.go, filters/responseheader/responseheader_test.go, mock/mock.go, proxy/proxy.go, skipper/skipper.go
This allows filters to set state and share it between the requests lifecycle
=> Added state bag to filter context

proxy/proxy.go, proxy/proxy_test.go
=> Added some basic branding (X-Powered-By and Server headers)

metrics/metrics.go, metrics/metrics_test.go, proxy/proxy.go
We found during load testing that the go-metrics mutex caused a relevant delay for super fast operations, like the route lookup.
I tested different strategies and the best approach was to update metrics as a go routine. We'll add results for this with further load testing.
=> Refactored metrics to improve performance

.gitignore, Godeps/Godeps.json, Godeps/Readme
Godeps added and Godeps/_workspace added to `.gitignore`. In this way you will NOT commit the sources of the imported projects. The dependencies can then be restored using `godep restore`. 
Let me know if this PR suits your needs.
=> Added Godeps

proxy/proxy.go
This single line is required to reuse the Host from the original request. This was our original expectation.
As we found out, the new request is built with the Host from the URL.
Go's SDK doesn't actually have the Host header in the Headers.
After we refactor the header filter we can still provide the option to change the host in the upstream request.
=> Always set the Host header from the original request by default

filters/builtin/static.go, filters/builtin/static_test.go
This pull request aims to fix the static filter to comply with the new way of shunting. The piping is a delicate issue. The reason is to fulfil 3 requirements:
1. benefit from the net/http.ServeFile implementation
2. still allow downstream filters to modify the response metadata
3. avoid buffering whole files
=> Upgrade static

filters/filtertest/filtertest.go
A while ago, the MarkServed was deprecated. Serve is supposed to handle it. This wasn't reflected in the filtertest mocks. This fixes it
=> Small fix to filtertest mocks

skipper.go
By default OpenFile will use the O_RDONLY but to write to the access log file it must be opened with write access.
=> Added write flag to log file

skipper_test.go
fixing listener tests:
- wait for listener started on the happy path
- find random available port for test listeners
=> fix race condition in listener tests

eskip/eskip.go, eskip/eskip_test.go
The situation was not specific to the Method predicate.
Any other route with multiple predicates, where the last predicate had an error, would still return a valid route, with the last predicate stripped.
This could, effectively, lead to some nasty situations.
Thanks a lot for finding this and creating the issue.
This closes #169
=> Fixed error handling in applyPredicates

packaging/readme.md
added warning about the use case and security of the docker image. Closes #157
=> add warning to the docker readme

proxy/proxy.go, proxy/upgrade.go
Normal proxy and upgrade proxy should configure tls the same way, so it
makes sense to share the `*tls.Config` already initilized with the
normal proxy.
Note this exposes the `*http.Transport` instead of "hiding" it behind the `RoundTripper` interface.
Close #203
=> #203 Share TLSClientConfig with upgrade protocol proxy

filters/tee/tee.go
@aryszka When Tee downstream has some errors, body.close were creating seg faults since body is not there
=> Fix error handling on failed tee requests

filters/builtin/path.go, filters/builtin/path_test.go
Very small changes here
1. Renamed to file to a more general `path` since it also does setPath now
2. It looked like what we really wanted was ReplaceAllString
3. My coverage metrics showed that we were missing the failure to compile the regex test case
=> Replace ReplaceAll with ReplaceAllString

eskip/doc.go, filters/builtin/builtin.go, filters/tee/doc.go, filters/tee/tee.go, filters/tee/tee_test.go
also fixes some docs (the examples from the constructor can be already found in doc.go)
=> rename tee to follow conventions

cmd/eskip/load.go, cmd/eskip/load_test.go
This is a quite easy mistake to make, and hard to debug, so I've added a check for it.
=> Added a check for repeating route ids to `eskip check`

proxy/debug.go
`Content-Type` header of responses from debug listener have `plain/text`, however the body contains JSON. This change replaces it with `application/json`.
=> Setting Content-Type header to application/json in debug

metrics/metrics.go, proxy/proxy.go
The background of this PR is the following:
We would like to create a dashboard, that shows us a distribution of where
skipper routes the requests to. Skipper currently supports metrics on a
per-backend base, but only keyed via the route-id. For our use-case, we would
need a mapping from route-id to backend-host. This is very brittle.
This is a simple solution, that would also provide a metric based on the
hostname of the backend. This would allow us to aggregate in ZMON. We could for
example create three buckets:
1. all requests, that go to *.example.org
2. all requests, that go to *.example.com
3. all others.
Plotting the request count over those three buckets would be exactly what
we want.
I tried to keep this as general as possible to be useful to others as well and
made it opt-in, …
=> Basic per backend host metrics

Makefile, filters/diag/diag.go, proxy/proxy.go, skipper.go
add a prefix to error messages that log only an error object. Closes #263
=> add prefix to error messages where it was missing

readme.md
The previous link landed on a "Not found" page
=> Updating link to packaging readme

proxy/proxy.go, proxy/proxy_test.go
this suppose to fix the trivially reproducible part of this issue: https://github.com/zalando/skipper/issues/269
EDIT: to emphasize, it enables http.Transport to retry the connection
See: https://golang.org/src/net/http/request.go#L1300
(naturally, there was a facepalm moment :) )
=> set the body to nil for outgoing requests, when the content length is zero

packaging/Dockerfile
Run the default binary, which is skipper: 
% docker run registry.opensource.zalan.do/pathfinder/skipper
Overwrite the command to eskip:
% docker run registry.opensource.zalan.do/pathfinder/skipper /usr/bin/eskip
=> set the default command to skipper

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, skipper.go
1. Add kubernetes-in-cluster flag to specify if the skipper is deployed as a pod vs running locally
2. If in-cluster use service account to authenticate with API server
3. Otherwise fall back to the current implementation 
JUST started, and I wanted to add a do-not-merge label, but apparently I don't have access to that. Will ping you once done
=> Get rid of kubectl proxy in skipper

filters/tee/tee.go, filters/tee/tee_test.go
This PR changes how the requests for the tee() filter are cloned. It replaces value based shallow copy with explicitly setting each known field in the clone.
Closes: #287
=> avoid copying unknown fields for the tee() request

cmd/skipper/main.go, dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, skipper.go
Redirect requests with `X-Forwarded-Proto: http` and `X-Forwarded-Port: 80` to HTTPS.
=> HTTP->HTTPS redirect for Kubernetes

packaging/Makefile
We use the packaging Makefile in our Jenkins task to build and we have a clean directory, so this will break.
rm skipper eskip
rm: cannot remove 'skipper': No such file or directory
rm: cannot remove 'eskip': No such file or directory
Makefile:16: recipe for target 'clean' failed
make: *** [clean] Error 1
=> packaging in a clean directory does not work

filters/tee/tee.go
removing unnecessary defer in tee response handler.
In response to comments in: https://github.com/zalando/skipper/pull/294
=> remove unnecessary defer

dataclients/kubernetes/kube.go
We've found a bug regarding the paths when reading from kubernetes ingresses.
Before, the following rule was create:
- Host: test.com Path: /test
With this, any of the following URIs matched:
- test.com/test
- test.com/foo/test
- test.com/foo/bar/test
Now, with this fix, only paths starting with the path defined on the ingress match.
=> Add '^' to start of path when getting them from kubernetes

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
@szuecs check this PR to your PR https://github.com/zalando/skipper/pull/306 whether it's fine with you. It removes the data race on the Client.healthy field.
Also, it becomes testable. Pushing a test in a bit.
=> use a select for the signal in the goroutine from which the routing calls Load*

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
When an ingress has a multiple routes, a request to the K8S API is made for each route and endpoint.
If the endpoint is the same, we can cache the response and there's no need to ask again. On the next iteration, this cache will be invalidated, so if the service changes, we'll be able to notice it.
This is very helpful in ingresses with many routes (we use 50+ in one real-world example) as the repeated calls to K8S API are slow and congest traffic on the whole. Also, each request generates a log entry, which can result in huge log files.
=> Implement caching for kubernetes service endpoints

Makefile
silence the format check in the Makefile to avoid polluting the build output with all the source files
=> silence the command expression for the format check in the Makefile

filters/builtin/builtin.go, filters/tee/tee.go, filters/tee/tee_test.go
If tee filter is created with the name `teenf`, it won't follow redirects.
=> tee filter does not follow redirects if user prefers so

filters/builtin/builtin.go, filters/cookie/cookie.go, filters/cookie/cookie_test.go, predicates/traffic/traffic.go, predicates/traffic/traffic_test.go, skipper.go
The below example, shows a possible eskip document used for green-blue
deployments of APIS, which usually don't require stickiness:
// hit by 10% percent chance
v2:
Traffic(.1) ->
"https://api-test-green";
// hit by remaining chance
v1:
"https://api-test-blue";
stickyness example:
// hit by 5% percent chance
cartTest:
Traffic(.05, "cart-test", "test") && Path("/cart") ->
responseCookie("cart-test", "test") ->
"https://cart-test"\;
// hit by remaining chance
cart:
Path("/cart") ->
responseCookie("cart-test", "default") ->
"https://cart"\;
=> implement traffic switching based on internal code

cmd/eskip/args.go
`eskip --help` -> `-innkeeper-url` part had usage text from the etcd url, updated it.
Not it looks like this:
```
-innkeeper-url string
url for the innkeeper service
```
=> Fix eskip usage text for -innkeeper-url

dataclients/kubernetes/definitions.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, routing/matcher.go
This implements `backend-weights` (or traffic switching) using an annotation `zalando.org/backend-weights` as described in #324.
It works by parsing the annotation of format:
```
zalando.org/backend-weights: |
{"my-app-v1": 90, "my-app-v2": 10}
```
and maps the weights defined in the annotation to the backend services defined in the ingress spec.
The traffic weights are computed relative to the number of backends, and subsequent backends for a path will get higher relative weight because of how the `Traffic` predicate in skipper works. E.g. if you have the following backends and weights:
```
* backend-1: 0.2
* backend-2: 0.6
* backend-3: 0.2
```
The computed traffic values will be:
```
* backend-1: 0.2
* backend-2: 0.75
* backend-3: 1.0
```
Which results in the following eskip rules:
``` …
```
=> Implement traffic switching in kubernetes dataclient

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, skipper.go
Hi!
This PR adds support for the k8s `kubernetes.io/ingress.class` [annotation on the ingress rules](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/multiple-ingress-controllers), this way you can have multiple ingress controllers.
In the end it will filter the ingresses obtained from k8s checking this annotation with these cases as result:
* If no annotation: valid
* If empty annotation: valid
* If different annotation from the desired one: invalid 
* If same annotarion as the desired one: valid
This way, the change is backwards compatible with all the ingresses that where previously being used.
By default if no ingress class is configured on run, it will be set `skipper` by default.
For example this would be a valid ingress for skipper:
```yaml
apiVersion: …
```
=> Add support for kubernetes.io/ingress.class annotation

packaging/Dockerfile, packaging/Makefile, packaging/readme.md
Added certificates to `Dockerfile` to support HTTPS requests. Without it, I got errors like `x509: failed to load system roots and no roots provided`.
Also:
- Updated env variables in the packaging README
- Fixed error on the first docker build
=> Support HTTPS requests in the Docker image

metrics/metrics.go, proxy/context.go, proxy/proxy.go
since the metrics are created on demand, and some of them have keys based on request method and host, it is possible to create unwanted number of metrics from user input. With this PR:
- use common host based metrics for those requests that were not matched against a host predicate
- allow only standard methods in metrics keys
=> use metrics keys only from known hosts and methods

metrics/metrics.go
fix of metrics keys to be consistent. (see comment in #342 )
@mo-gr chose to remove the underscore, because there was already the "_unknownroute_" before that pr.
=> consistency fix for metrics keys

.gitignore, Makefile, readme.md
- fix the license badge to point to the official url
- generate test coverage on merge to master and show it with codecov.io
fixes #348
=> fix license badge, provide coverage for sub packages

LICENSE, pathmux/LICENSE, pathmux/Makefile, pathmux/README.md, pathmux/tree.go, pathmux/tree_test.go, routing/matcher.go, routing/matcher_test.go
move pathmux (https://github.com/zalando/pathmux) to skipper:
- copy pathmux code under a subdirectory: pathmux/
- update the main license file to incorporate the different license and copyright
=> Move pathmux

logging/access.go, logging/access_test.go
Fixes #243
Flow id is added to the access logs. Info is taken from request object which is either provided with the id from the caller or filled by the filter. Works for both json and apache [format](https://gist.github.com/DeTeam/ea043b9272060e3060bcc8853942dfc3)
Question here as well: should we make "reuse" flag a default on in the `flowId`. Right now without it we'd be re-generating flow Ids on every call, it kinda destroys the purpose.
cc @aryszka @lmineiro
=> Add X-Flow-Id to the access logs

glide.lock, glide.yaml
There was a missing dependency introduced in  https://github.com/zalando/skipper/pull/362
=> add dependency which was not added in the PR

Makefile
glide list returns with non-0 exit code if any of the imported dependencies is not vendored, 0 otherwise
=> add vendoring check

cmd/skipper/breakerflags.go, cmd/skipper/main.go, skipper.go
this is a convenience flag for letting filters define breakers without having a dummy global set of settings
=> provide a shortcut flag to enable breakers without global settings

cmd/skipper/breakerflags.go
Just fixing a small typo in the breakers description
=> Fixing typo in enableBreakersUsage description

eskip/eskip.go, logging/loggingtest/logger.go, proxy/proxytest/proxytest.go, routing/matcher.go, routing/matcher_test.go, routing/pathgen/pathgen.go, routing/regexp_test.go
using now shared compiled objects for the identical regular expressions in the host and path regexp predicates. `BenchmarkRegexp` was used to check whether this comes with degradation in the overall request processing. rx.Copy() is used according to the stdlib docs: http://godoc.org/regexp#Regexp.Copy
(to help testing, there is now a Mute/Umute function on the test logger)
=> use shared compiled regular expressions

dataclients/kubernetes/kube.go
Fix small typo in Kubernetes data client. The error message was Nein Stackenblochen! :smirk: https://www.youtube.com/watch?v=d6wd78jMHDk
=> Fix typo in Kubernetes data client

dataclients/kubernetes/kube.go
health check handling change:
- on initial bootstrap LoadAll will create the full routing table including health check OK
- health check will be always OK until we received a SIGTERM (teardown handling)
=> Kubernetes ingress - health check handling change

proxy/proxy.go, proxy/proxy_test.go
preserve incoming content length, not only from the header map, but from the parsed http.request object
=> preserve incoming content length settings

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
This is a naive approach to fixing https://github.com/zalando/skipper/issues/406.
Skipper makes a series of requests in quick succession to the API server. If one request other than the first one fails the compiled list of rules is inconsistent and applying it does more harm than just doing nothing.
Therefore, instead of ignoring these errors we propagate them up which leads to no rules being changed in case of any failed request.
**However**, whilst doing it I discovered that this will also fail for errors such as referenced services that don't exist. Service names are provided by users and should not lead to skipper being permanently stuck with old rules. This needs to be fixed but I wanted to get this out early.
My idea would be that the returned error should be checked for whether it …
=> Error early when apiserver is unreachable

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, glide.lock, glide.yaml
Follow up of https://github.com/zalando/skipper/pull/409#issuecomment-321256681
It restores the original test suite that tolerates misconfiguration such as Ingresses referencing missing services (404 from the API server).
However, this adds an early return in case of network errors such as an unavailable API server. This has the effect that Skipper won't remove its routes until it gets a successful response from the API server. (Note that successful includes 500s in this case. I guess we should treat 500s in a similar "don't change the routes" way)
=> Treat network errors as transient and defer updating routes

.gitignore, Makefile
Make lint will run metalinter with enable-all and writes output to linter.log, because you may want to check this later. You have to install [gometalinter](https://github.com/alecthomas/gometalinter).
Install:
% go get -u github.com/alecthomas/gometalinter
% gometalinter -iu
Run:
% make lint # produces linter.log and a lot of lines from linters
=> add Makefile target "lint"

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, proxy/doc.go, proxy/proxy.go, proxy/proxy_test.go, skipper.go
Makes the default 'no-routes-found' http status code configurable via
the flag `--default-http-status`.
This makes it possible to treat routes not found as server errors e.g.
502 Bad Gateway, instead of treating them as client errors (defaults to 404).
When using the Kubernetes dataclient a default catchall route which
returns 404 will be configured for any host rule which doesn't specify
its own catchall rule (`""` or `/`).
Fix #408
=> Make default HTTP status configurable

cmd/skipper/main.go, metrics/metrics.go, skipper.go
adding the non route based backend and response streaming metrics. The key of the metrics has an 'all.' prefix, so that existing filter with the prefix 'backend.' or 'response.' won't include them, and so avoid ending up in duplicate sum of the values.
What I am wondering if these should be enabled only if the route based variants of these metrics are disabled. Any advice?
=> add combined metrics for backend latency and response streaming

cmd/skipper/main.go
instead of empty string which causes an error
=> set default tracer to noop

cmd/skipper/main.go, cmd/skipper/ratelimiterflags.go, filters/builtin/builtin.go, filters/ratelimit/ratelimit.go, filters/ratelimit/ratelimit_test.go, glide.lock, glide.yaml, proxy/proxy.go, proxy/ratelimit_test.go, ratelimit/ratelimit.go, ratelimit/ratelimit_test.go, ratelimit/registry.go, ratelimit/registry_test.go, skipper.go
example: skipper -ratelimits type=local,maxHits=50,timeWindow=60s
this would be applied before the filter chain
This partially implements #424
=> ratelimit support via args

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
Instead of creating a catchall route per ingress object, aggregate all ingress objects and only create a catchall route per host. This solves the problem of having multiple ingress objects with the same hostname defined where a catchall for one ingress object can shadow a catchall of another ingress object as detailed in #437.
This is the real fix and makes #437 obsolete.
Fixes #436
=> Create catchall per host instead of per ingress

cmd/skipper/main.go
This checks the length of `flag.Args()` which will be non-empty in case some flags were not parsed. This is to ensure that you don't accidentally run skipper with the wrong args.
We had an issue were the args were specified like: `./skipper skipper -kubernetes ..` which means non of the args are parsed because the `skipper` command is invalid meaning it's the same as running `./skipper`. With this check skipper would crash rather then running with the unintended default configuration.
=> Check length of flag.Args() to ensure the were parsed correctly

pathmux/tree_test.go, pathmux/viztree.go, pathmux/viztree_test.go
The visualization tree is basically an explosion of the radix tree used in pathmux.
It looks like a tree representation of a path broken down by its slashes. However, it is built from the original pathmux Tree.
It is included in the pathmux so it can access the inner representation of the tree.
=> Add visualization Tree built from pathmux

filters/builtin/builtin.go, filters/builtin/redirect.go, filters/builtin/redirect_test.go
- Close #328
- Add `redirectToLower` filter for case-insensitive redirects
- Add enum `redirectType` to differentiate between redirect filter types
- Fix syntax and `gofmt` warnings
=> Add redirectToLower filter for case-insensitive redirects

cmd/eskip/args.go, cmd/eskip/doc.go
ref: https://github.com/zalando/skipper/issues/449
Introduce new flag: -no-tty
=> Allow non-TTY applications to execute eskip commands

filters/builtin/redirect.go
fixing the builtin.Redirect() function to avoid using the package internal redirectType type
=> compatibility fix to the public builtin.Redirect() function

cmd/skipper/main.go, metrics/metrics.go, skipper.go
Add -metrics-exp-decay-sample option. If set, metrics will use an exponentially decaying sample for the histograms instead of the uniform one. Once we're satisfied with the results, we can switch the defaults.
Fix #428.
Fix #363.
=> Allow using an exponentially decaying sample for histograms

.travis.yml, cmd/eskip/load.go, eskip/string.go, eskip/string_test.go
Fix route printing:
- Unify Fprint and Print
- Add semicolon to the last printing route line, too
- Fix Fprint adding extra lines in non-pretty mode
=> Fix route printing

cmd/skipper/main.go, logging/loggingtest/logger.go, routing/datasource.go, routing/datasource_test.go, routing/routing.go, skipper.go
when the -suppress-route-update-logs is set, only a summary of the rout changes will be logged
=> create a flag to disable detailed route update logging

eskip/doc.go, filters/builtin/builtin.go, filters/builtin/inlinecontent.go, filters/builtin/inlinecontent_test.go
creates a filter that can be used to return static inline content, primarily for testing or demo
=> create a filter for inline content

filters/builtin/builtin.go, filters/builtin/copy.go, filters/builtin/copy_test.go
requestCopyHeader() and responseCopyHeader() that can copy the content of header "src" to "dst" in the request or response pass of the proxy.
Closes #426
=> header copy filters 

Makefile
use common git command to get version (sort -V) is not available on bsd like systems or you have to use gsort
added 2 build targets one for osx and one for windows
=> fix build for osx/win

metrics/codahale.go, metrics/doc.go, metrics/metrics.go, metrics/metrics_test.go
Minor fixes pointed out on #507 PR that's already merged.
* Typos on doc
* Set better status code on not allowed path for metrics endpoint `/`: `400` -> `404`
* Set better status code on not allowed method `POST` on codaHale format metrics enpoint: `400` -> `405`
=> Minor fixes for prometheus metrics

cmd/eskip/args.go, cmd/eskip/args_test.go, cmd/eskip/doc.go, cmd/eskip/media.go, cmd/eskip/media_test.go, cmd/eskip/mediadefaults.go, cmd/eskip/mediadefaults_test.go, cmd/eskip/readclient.go, cmd/eskip/writeclient.go, etcd/etcd.go, etcd/etcd_test.go
This is a first draft with missing new tests to enable eskip to handle oauth. Just did it straight forward and added it to the client.
Also introduced a new `oauth-token-etcd` argument to have no collisions with current innkeeper implementation.
=> Enable eskip to handle OAuth when working with etcd

eskip/lexer.go, filters/flowid/standard.go
- instead of `errors.New(fmt.Sprintf())`
=> eskip, filters: use `fmt.Errorf` directly

proxy/tracing_test.go
- drop unnecessary returns
- set arguments and receivers to `_` to make clear, they aren't used
This is more like personal/cosmetic changes. If you don't want to take it, let me know.
=> proxy: simplify satisfying an interface

filters/diag/diag.go, logging/handler.go, logging/log_test.go, metrics/prometheus.go, proxy/proxy_test.go, routing/matcher_test.go, routing/routing_test.go
* `time.Since` instead of `time.Now().Sub`
* `strings.Contains` instead of `strings.Index`
* `bytes.Buffer.String` instead of `string(bytes.Buffer.Bytes())`
* `copy` instead of for loop
=> all: simplifications

routing/datasource.go
When processing of routes fail, we currently only output the error, but nothing to identify the broken route. This can be a problem when there are many thousands of routes.
This change improves the logging in case of broken routes by also outputting the id of the route that failed.
=> Improve error logs for invalid routes

script/script.go
with this we can have a body with an error message like in
```lua
function request(ctx, args)
local ok, token, err = pcall(extract_token, ctx)
if not ok then
-- in case pcall fails, the error is in the token var
print("ERROR: " .. token)
ctx.serve({status_code=500, body="Internal Server Error\n"})
return
end
if err ~= nil then
print("ERROR: " .. err)
ctx.serve({status_code=401, body=tostring(err)})
return
end
-- do more here
end
```
=> [lua] add body="string" to ctx.serve()

dataclients/routestring/string.go, filters/builtin/path.go, filters/builtin/query.go, filters/flowid/filter.go, proxy/tracing_test.go, ratelimit/ratelimit.go
- this satisfies golint and also a follow up on
https://github.com/zalando/skipper/pull/521#discussion_r158845373
=> all: drop underscore if param or receiver is unused

dataclients/kubernetes/definitions.go, dataclients/kubernetes/definitions_test.go, dataclients/kubernetes/kube.go
This will fix  #563
Given an ingress spec:
spec:
rules:
- host: foo.example.org
http:
paths:
- backend:
serviceName: foo
servicePort: http
path: /
And a service definition:
spec:
ports:
- name: http
port: 80
protocol: TCP
targetPort: 9090
- name: metrics
port: 9911
protocol: TCP
targetPort: 9911
selector:
application: foo
type: ClusterIP
would result in 2x the replica count one for each pod :80 and :9911. 
This PR will fix it and make sure only selected endpoints will be used (with port :80).
=> fix endpoint.Targets() to filter selected targets also by ports

packaging/Dockerfile
The default port of 9090 should be exposed in the Docker image.  Adding the EXPOSE instruction informs Docker that the container listens on the specified network ports at runtime.
=> Expose default port 9090 in the Dockerfile

eskip/lexer.go, eskip/parser_test.go
Using regex delimiter fails in character list in eskip #134 
Tried to keep behaviour related to `\` in `/.../` same.
=> Using regex delimiter fails in character list in eskip #134

dataclients/kubernetes/httpsredirect_test.go
- removing unnecessary wait (root cause for time sensitive test runs)
- handling the timeout for the effective wait
=> fix test timeout in kubernetes http redirect

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/lbtarget_test.go
- fix: remove load balancing when using service fallback, therefore removing invalid route with 0 size group
- fix: ID formatting, therefore remove duplicate IDs, therefore broken load balancing for default backends
- improve: remove unnecessary load balancing loopback when there's just a single target endpoint, but keep using the target endpoint
- refactor: remove unused method (listRoutes)
=> Fix: empty group when no target endpoints + fix: id formatting for default backends with target endpoints + small improvements

dataclients/kubernetes/doc.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/lbtarget_test.go, docs/dataclients/kubernetes.md, docs/kubernetes/ingress-usage.md
This is an idea of how we could allow specifying custom routes on an ingress resource, to make it very simple to extend the application at the ingress layer.
My use case is that I have a REST API which is now called by a client-side application so I need to respond with the correct `Access-Control-Allow-Origin` headers. Instead of extending my application, with this I can just add an annotation (`zalando.org/skipper-routes`) to my ingress and quickly extend the API to send the right headers. The filter or predicate annotations are not enough because I need to respond with just the headers for the `OPTIONS` request and I can't proxy to my backend because it doesn't handle the `OPTIONS` request.
This is not yet tested, I just wanted to show a PoC for you to see before I go further with the …
=> Add annotation for specifying custom routes on ingress

dataclients/kubernetes/httpsredirect_test.go
Fixes: #585 
This PR only fixes the tests but not the root cause.
As it turns out, the failing tests were not caused here due to a concurrency race condition, but because of the current ingress client accepts multiple default backends from different ingress specs, therefore there are multiple default routes that can match a request that doesn't match any host and path rules.
The problem is referenced here: https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/kube.go#L352
The reason, why the test only occasionally fails, is that the routing package uses maps internally during processing the routes, and this introducses a certain level of randomness.
This PR removes the competing ingress specs from the https redirect tests.
=> remove concurrent test specs from https redirect test

Makefile, routing/datasource.go, routing/datasource_test.go, routing/routing_test.go
Fixing a bug where on route config updates, the recovery request for the full route config from a data client is not handled correctly, causing that routes that were deleted during the failing period are not removed from the active configuration.
=> fixing routing config recovery after differential update errors

cmd/eskip/load_test.go, cmd/eskip/write_test.go, etcd/etcd_test.go, etcd/etcdtest/mocketcd.go
shortcheck should not rely on etcd tests, ignoring all of them and hack around testing.Main to return on running with shortcheck
=> fix flaky tests relying on etcdtest

cmd/skipper/main.go, plugins.go, skipper.go
skipper currently cannot be started if the plugin dir is missing. This is fine if an explicit plugin dir is specified, but not when plugins are not intended to be used, and breaks compatibility this way.
The fix is a cheap one: ignore if the error is a path error and the dirname is the default. Open for better suggestions.
This is related to: https://github.com/zalando/skipper/pull/598
=> prevent startup failure when default plugin dir is missing

doc.go
- properly implement predicate interface
- add naming to routes.eskip to avoid parsing errors
- add missing imports to hello.go
=> doc(doc.go) fix hello world code example

docs/kubernetes/ingress-usage.md
I was trying to find information on enabling gzip with Skipper and couldn't find any documentation on it. A search led me to https://github.com/zalando/skipper/issues/87 which shows the feature implemented in https://github.com/zalando/skipper/pull/161 without any documentation update.
=> Add documentation for `compress()` to usage

filters/builtin/static.go
`Static` filter takes 2 arguments the error message says it takes 1.
=> Fix wrong error message for Static filter

loadbalancer/concurrency_test.go, loadbalancer/filter.go, proxy/proxytest/proxytest.go
* Added failing test with the meaninglessly updating routing;
* Starting round robin with a random member, not with the first one;
Fixes https://github.com/zalando/skipper/issues/614
=> Fix balancer route update

.gitignore, Makefile, _test_plugins/dataclient_noop.go, _test_plugins/filter_noop.go, _test_plugins/multitype_noop.go, _test_plugins/predicate_match_none.go, _test_plugins_fail/fail.go, cmd/skipper/main.go, cmd/skipper/pluginFlags.go, docs/plugins.md, plugins.go, skipper.go, skipper_test.go
so https://github.com/aryszka/configfilter could be converted to a plugin ;-)
*  when loading a `.so` file, it is checked if there is also a `.conf` file
with the same base, e.g. for `./plugins/noop.so` a config of
`./plugins/noop.conf` is attempted to open. If it exists, each line
in this file is passed as argument to the plugin loader function
(leading and trailing spaces stripped, lines beginning with a `#`
after space stripping are ignored).
* add support for multitype plugins complete auto detection and `.conf`
file support
* add some noop plugins in _test_plugins and add a make target to build
and try loading as test
=> Multi plugins, plugin .conf filles

Makefile
fixing the make tasks: .coverprofile-all and bench
=> run the plugin compilation for the coverprofile and benchmark tasks

filters/auth/oauth.go, filters/builtin/builtin.go, filters/log/log.go, filters/log/log_test.go, logging/access.go, logging/access_test.go
implement #631 unverifiedAuditLog logs "sub" from 2nd part of decoded base64 jwt token if possible.
@hjacobs this is what you meant? Any idea for the prefix? I just did "Audit sub: " for now but I guess we want something else.
Audit sub: c4ddfe9d-a0d3-4afb-bf26-24b9588731a0 ::1 - - [30/Apr/2018:09:39:59 +0200] "GET /ffff09 HTTP/1.1" 200 0 "" "curl/7.49.0" 0 localhost:9999
Audit sub: c4ddfe9d-a0d3-4afb-bf26-24b9588731a0 ::1 - - [30/Apr/2018:09:39:59 +0200] "GET /ffff10 HTTP/1.1" 200 0 "" "curl/7.49.0" 2 localhost:9999
=> unverifiedAuditLog - fix #631 

filters/log/log.go, filters/log/log_test.go
To not log user specified random data this proofs that Sub claim contains "valid" string information and not random data chosen by the user sending the request.
@aermakov-zalando thanks for the hint!
=> fix prepared wrong garbage in unverified auditlog

docs/kubernetes/ingress-controller.md
Added sample manifests for:
* ServiceAccount
* ClusterRole
* ClusterRoleBinding
* adopted DaemonSet
see issue in [kube-ingress-aws-controller](https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/153)
=> Document how to deploy with enabled RBAC

cmd/skipper/main.go
Wire skipper's ```IgnoreTrailingSlash``` option to cmd argument.
=> add ignore-trailing-slash as skipper cmd arg

dataclients/kubernetes/kube.go
In order to fix #647 this PR set hardcoded timeouts to kubernetes api server to stop waiting until Kernel will timeout TCP connection.
10s seems to be a good choice, because it is far less than before and more than enough.
I doubt noone needs to tune these values for this particular transport.
=> set timeouts to kubernetes api access

proxy/lb_failingbackend_test.go, proxy/proxy.go, routing/fallbackgroup_test.go
one part of the fix for #654 is to make sure we return a 502 in case of "No route to host".
Reply also with proxyError after retry of a loadbalanced route to make sure we create a 502 and not a 500. We have to be consistent in returning proxyError.
=> return proxyError after retry of a loadbalanced route 

cmd/skipper/main.go, filters/builtin/builtin.go, filters/tracing/spanname.go, filters/tracing/spanname_test.go, proxy/context.go, proxy/proxy.go, proxy/tracing_test.go, skipper.go
Creating a filter to set the name of the proxy span for distributed tracing.
=> create filter for setting custom span name for distributed tracing

cmd/skipper/main.go, dataclients/kubernetes/kube.go, skipper.go
Added WhitelistedHealthCheckCIDR option to main.go skipper.go and kube.go as string array
append WhitelistedHealthCheckCIDR to internalIps in kube.go
tested on docker kubernetes, healthcheck working fine
=> Add internal ip whitelist option to healthcheck to be appended to the default

proxy/proxy.go
fix #654 
if stdlib cancels or time exceeded, then return proxy timeout instead of 500
=> fix #654 - return gw timeout

docs/dataclients/eskip-file.md, docs/dataclients/kubernetes.md, docs/deployments.md, docs/kubernetes/ingress-backends.md, docs/kubernetes/ingress-controller.md, docs/kubernetes/ingress-usage.md, docs/operations.md, docs/videos.md
Make "Skipper" and "Kubernetes" more consistent in the docs.
=> fix proper nouns

filters/auth/oauth.go
fix tokeninfo filters to use Set() and not Add() to manipulate querystring
=> fix tokeninfo filters

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/path_test.go, docs/kubernetes/ingress-usage.md, skipper.go
fixes: #662 and #360
introducing path handling modes in order to allow control over how ingress paths are interpreted by default and per-ingress.
=> provide path modes for Kubernetes ingress paths

dataclients/kubernetes/kube.go, dataclients/kubernetes/lbtrafficswitch_test.go
Currently, when the traffic switching is used together with load balanced routes, the right route often may not be found. When there multiple load balanced route groups with traffic control, the route decision may keep looping, until the maxLoopback is reached.
The reason is that the Traffic() predicate is set for the member routes in the load balancing group, and it causes the already selected route match only with a certain chance.
This PR would move the Traffic() predicate to the loadbalancing group decision route from the member routes.
=> move the traffic predicate to the decision route

proxy/testtracer_test.go, proxy/tracing_test.go
- move global variables to a part of the test tracer object
- move the test tracer type to its own go file
=> refactor tracing tests

proxy/context.go, proxy/proxy.go, proxy/proxy_test.go, proxy/testtracer_test.go, proxy/tracing_test.go
Currently, we set two spans in the proxy for opentracing:
- server span ("ingress")
- client span ("proxy")
The proxy span starts before making the backend request. However it is closed as soon as the response headers are parsed, or the request failed. After discussing it with @lmineiro, I believe the proxy span should include the duration while the response content is fully copied onto the incoming connection. This PR moves finishing the proxy span after the stream copying is done or aborted.
=> include the response streaming duration in the proxy span

cmd/skipper/main.go
(#677) Just forwarding the parameters from cmd to skipper:
```
timeoutBackend
keepaliveBackend
enableDualstackBackend
tlsHandshakeTimeoutBackend
maxIdleConnsBackend
```
=> wire in missing connection, timeout parameters

dataclients/kubernetes/kube.go
sort ingress and endpoints to be more predictable with route updates
This will not entirely fix the problem of unstable blue-green traffic switching.
=> do less route updates

routing/datasource.go, routing/routing.go
sort routing table output to create simply diffs if you want to investigate differences of 2 routing tables
=> sort routing table output on support endpoint

cmd/skipper/main.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, docs/kubernetes/ingress-controller.md, skipper.go
Issue Reference: https://github.com/zalando/skipper/issues/686
**Purpose**
We have a use-case where we deploy identical environments on the same cluster, segregating them by `Namespace`. To aid in configuration it'd be nice to use the same `ingress.class` in each namespace (e.g. `ingress.class: api`) without having to add the namepsace to the class.
This also has the added benefit of being able to further restrict RBAC permissions by combining a `ClusterRole` and `RoleBinding` to ensure that the associated `ServiceAccount` can't list ingresses in another namespace.
**Implementation**
I've added a `-kubernetes-namepsace` option that defaults to `""`.
* When the argument is omitted (empty) it will use `/apis/extensions/ingresses`
* When a namespace is provided it will use …
=> Support for Limiting Ingress Lookups to a Single Namespace

docs/predicates.md
* The slashes for HeaderRegexp are misleading. Could be the initial example was using this format: `HeaderRegexp("Server", /skipper/)`.
* Use a request header for the examples.
=> Fix Header and HeaderRegexp examples

.travis.yml
preventing travis build with go1.11beta1 because it changes gofmt formatting
=> use go1.10.x in travis

proxy/proxy.go
this fix will render godoc correctly and remove the golint warning
=> typo in godoc

proxy/proxy.go
upstream issue: https://github.com/golang/go/issues/23699
Tested with:
```
% ./bin/skipper -inline-routes '* -> "https://www.example.org"'
% curl -H Connection:\ Keep-Alive http://localhost:9090
```
=> fix invalid connection header issue reported via slack channel

docs/operations.md
This PR adds information about getting the routes from Skipper. It explains the limit of routes given by default and how to configure it.
It fixes #713
=> Improve the routing table information documentation

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
This fixes an issue, where given an ingress with the custom routes
annotation `zalando.org/skipper-routes` and multiple rules defined, the
route would only be created for the last rule.
I.e. the following ingress:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
annotations:
zalando.org/skipper-routes: |
Method("OPTIONS") -> status(200) -> <shunt>
name: app
spec:
rules:
- host: app-default.example.org
http:
paths:
- backend:
serviceName: app-svc
servicePort: 80
- host: app-alt.example.org
http:
paths:
- backend:
serviceName: app-svc
servicePort: 80
```
Would produce the custom route:
```
Host(/^app-alt[.]example[.]org$/) && Method("OPTIONS") ->
status(200) -> <shunt>
```
When it should create routes for both host names:
```
1: Host(/^app-default[.]example[.]org$/) && …
```
=> Fix custom routes for multiple hosts

cmd/skipper/main.go, metrics/metrics.go, metrics/prometheus.go, skipper.go
If set, use a custom set of buckets for Prometheus histogram metrics instead of the default one.
Example: 
./bin/skipper -enable-prometheus-metrics -histogram-metric-buckets=.005,.01,.02,.03,.04,.05,.06,.07,.08,.09,.1,.2,.3,.4,.5,.6,.7,.8,.9,1,1.5,2,2.5,3,3.5,4,4.5,5,6,7,8,9,10,15,20,25,30,40,50,60,70,80,90,100,125,150,200,275,425,600,1000
Fixes #721.
=> Add -histogram-metric-buckets option

docs/plugins.md
add reference in the documentation to the problem of plugins and vendoring
=> docs: link plugins and vendoring problem

cmd/skipper/main.go, filters/auth/doc.go, filters/auth/oauth.go, filters/auth/oauth_test.go, readme.md, skipper.go
=> Add flag for Oauth request timeout

dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/lbannotationfilters_test.go, dataclients/kubernetes/lbtarget_test.go, dataclients/kubernetes/lbtrafficswitch_test.go, dataclients/kubernetes/path_test.go
fix #718 kube dataclient: custom-routes annotation should specify the path with pathmode if set in the ingress spec
=> fix kube dataclient: custom-routes should set path according to ingress

filters/auth/tokeninfo.go, filters/auth/tokeninfo_test.go
#739 tokeninfo filter should cache authclient per tokeninfoURL and reuse it instead of creating one for each filter
Right now a hashmap for the cache is not really needed, but we can easily create filters, that can pass the target tokeninfoURL to be able to change this per route.
```
% go test -benchmem -bench=BenchmarkOAuthTokeninfoFilter -run='^$' ./filters/auth/ -v
goos: darwin
goarch: amd64
pkg: github.com/zalando/skipper/filters/auth
BenchmarkOAuthTokeninfoFilter-8           300000              4481 ns/op            1739 B/op         17 allocs/op
PASS
ok      github.com/zalando/skipper/filters/auth 1.499s
% go test -benchmem -bench=BenchmarkOAuthTokeninfoFilter -run='^$' ./filters/auth/ -v
goos: darwin
goarch: amd64
pkg: github.com/zalando/skipper/filters/auth …
```
=> cache authclient per tokeninfoURL

delivery.yaml
CDP now has an 'official' Golang overlay which simplifies the build a lot. Use that instead of installing Go manually.
=> Simplify CDP build with golang overlay

docs/predicates.md
Fix the examples for `PathRegexp` which were wrong.
=> Fix docs about PathRegexp

docs/filters.md
also added a note about overriding the `proxyPreserveHost` behavior
=> fix preserveHost filter documentation

docs/filters.md, filters/builtin/builtin.go, filters/builtin/querytoheader.go, filters/builtin/querytoheader_test.go
queryToHeader("q", "X-Q") will copy the value of q param to the value of X-Q header.
The optional 3rd argument can be used to prepend the value, for example to add "Bearer ".
=> add queryToHeader filter

delivery.yaml, packaging/Dockerfile.alpine, packaging/Dockerfile.lightstep, packaging/Makefile
Build lightstep image based on alpine. This is done to reduce the image size. It's a reduction from `179MB` -> `45.6MB` compared to the ubuntu based image.
```
REPOSITORY                                                           TAG                                        IMAGE ID            CREATED             SIZE
registry.opensource.zalan.do/pathfinder/skipper-lightstep-test       pr-762-9                                   de824efae48c        4 minutes ago       45.6MB
registry.opensource.zalan.do/pathfinder/skipper-lightstep            v0.10.68                                   61a3b1c0a562        24 hours ago        179MB
```
It's implemented by adding new make targets `alpine.build` and `alpine.plugins` that builds skipper and plugins in a `golang:alpine` based image such that both …
=> Build lightstep image based on alpine

delivery.yaml, etcd/install.sh
Speed up CI build time in two ways.
1. Download etcd binary instead of pulling all sources and building from source.
2. Reduce `delivery.yaml` configuration to a single build step with multiple commands. Each build step is run on a separate VM so this reduces the build time a lot because we build all images on a single VM and avoid pulling the same dependencies three times on three different build VMs.
=> Speedup CI buildtime

go.mod, go.sum
fix opentracing wireformat should use only key-value pairs and not propagate a list of values for one key
It will use https://github.com/szuecs/opentracing-go/commit/e14b9d480998f9aa58be64079be26a6d730a7fa2 to have the proposed change from
https://github.com/opentracing/opentracing-go/pull/191 merged.
=> fix opentracing wireformat

delivery.yaml
#770 tried to speed up the CDP build but introduced a bug where it would build the lightstep image with the statically linked skipper binary from the previous build step.
The fix is to run `make clean` before building the lightstep image so we build a new `skipper` binary linked against musl similar to the plugin.
Works!
```
$ docker run registry.opensource.zalan.do/pathfinder/skipper-lightstep-test:pr-777-1 
Unable to find image 'registry.opensource.zalan.do/pathfinder/skipper-lightstep-test:pr-777-1' locally
pr-777-1: Pulling from pathfinder/skipper-lightstep-test
8e3ba11ec2a2: Already exists 
fed9443358de: Pull complete 
61cc3ffcb3b8: Pull complete 
c8dedfa011d4: Pull complete 
9457ac0abbeb: Pull complete 
ca1a567d4505: Pull complete 
Digest: …
```
=> Correctly build skipper binary for lightstep image

go.mod, go.sum
https://github.com/opentracing/opentracing-go/pull/191 was merged, so we no longer need the fork introduced in https://github.com/zalando/skipper/pull/774
=> Switch back to upstream of github.com/opentracing/opentracing-go

Makefile, filters/auth/webhook_test.go, readme.md
- adding GO111MODULE=on switch for tasks: test, vet, build plugins
- side effect: gofmt -s -w simplified webhook_test.go
=> fix: add go modules to all tasks

docs/reference/filters.md, filters/accesslog/control.go, filters/accesslog/control_test.go, filters/accesslog/disable.go, filters/accesslog/disable_test.go, filters/accesslog/doc.go, filters/builtin/builtin.go, proxy/proxy.go, proxy/proxy_test.go
As was discussed in https://github.com/zalando/skipper/pull/752#issuecomment-421052414
* Creating `disableAccessLog` and `enableAccessLog` filters.
* Deprecating `accessLogDisabled`.
=> Deprecate accessLogDisabled in favor of disableAccessLog and enableAccessLog filters

logging/loggingwriter.go, logging/loggingwriter_test.go, proxy/proxy.go, proxy/proxy_test.go
Fixes #802 
During logging refactoring error condition was missed
```
if err != nil {
p.errorResponse(ctx, err)
return
}
```
=> Fix logging regression after #752

dataclients/kubernetes/kube.go, dataclients/kubernetes/lbannotationfilters_test.go
fix #808 and add dropRequestHeaders filter before the filters from the annotations applied by users
=> fix dropRequestHeaders in kubernetes should be applied before user filters

readme.md
Adds a link to the Zalando Tech blog article with some context of the article. Should fix #244. As there wasn't more context given I did by best effort. Open for proposals.
=>  Add link to zalando tech blog

docs/reference/filters.md
The actual documentation does not display some of the parameters of the filters correctly due to the lack of an empty line before the bullet-point list.
=> Fix filter documentation (bullet lists)

metrics/prometheus.go
I've found that the Prometheus metrics does not have the default compatibility options activated by default.
If you see the comment for `DisableCompatibilityDefaults`, you can see the following:
https://github.com/zalando/skipper/blob/7d1e7ba519fc513bae8a7ecb8a5faec398c24ef1/metrics/metrics.go#L141-L146
So, with this PR, the compatibility defaults are also applied on Prometheus metrics.
=> Activate compatibility defaults on Prometheus metrics

readme.md
I've updated the Docker documentation to include examples of how to run both `eskip` and `skipper` from inside the container by passing in a local `.eskip` file.
=> Updated Docker section

cmd/skipper/main.go, routing/routing.go, routing/routing_test.go, skipper.go
Closes: https://github.com/zalando/skipper/issues/835
If the -wait-first-route-load flag is set, then the listener will be started only after the first batch of routes are received.
=> wait for first routes loaded before starting the listener

dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/redirect.go
this header is used for prioritization. Since there is no guarantee that this header is always present, replacing it with an additional, always matching path regexp predicate.
Closes: #838
=> replace the usage of X-Forwarded-Port for HTTPS redirects in Kubernetes

docs/kubernetes/ingress-usage.md
fix TOC and links to the userdocs and most often remove links to godoc, which should be linked from the specfic userdocs
=> doc: fix TOC and links

delivery.yaml, mkdocs.yml
fix pipeline to not error caused by docs can not be pushed because of permissions
add east-west to kubernetes TOC
=> fix doc pipeline and add east-west to TOC

proxy/proxy.go
instead of preserving the context.Context of the incoming request to the outgoing request, preserve only the opentracing span. `skptesting/benchmark-proxy.sh` showed that this eliminates the 'context cancelled' errors.
=> preserve only the span not the entire context of the incoming request

dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/lbannotationfilters_test.go, dataclients/kubernetes/lbtarget_test.go, dataclients/kubernetes/lbtrafficswitch_test.go
This fixes a ID generation issue when a single ingress contains two hostnames that would collide given the previous `routeID` function.
The problem was caused because of the sanitization rule, that replaced any non-word with an underscore. Given `my-api.prd.company.com` and `my-api-prd.company.com`, they would be sanitized to the same name, `my_api_prd_company_com`.
Somewhere down the code, one would effectively replace the other rule, allowing only one of the domains to be actually registered. (probably by putting the routes on a map using `eskip.Route.Id` as key)
My solution was to include the index of the ingress `host` in the name. Anything else that could make the ID unique would work as well (hashing, etc)
=> Fix kubernetes rule name hashing

.gitignore, skptesting/benchmark-proxy.sh, skptesting/benchmark.inc
- check dependencies and add error message to point to a dependency if not satisfied
- use GO111MODULE=on to build skipper in skptesting
=> skptesting fix

skptesting/benchmark-proxy-lbroute.sh, skptesting/lb.eskip
```
[warmup]
Running 3s test @ http://127.0.0.1:9090/lorem.html
Requests/sec:   6472.76
Transfer/sec:    847.02KB
[warmup done]
[benchmarking skipper]
Running 12s test @ http://127.0.0.1:9090/lorem.html
2 threads and 128 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    16.81ms    8.36ms  95.39ms   72.78%
Req/Sec     3.88k   462.79     6.14k    75.00%
92910 requests in 12.08s, 11.87MB read
Requests/sec:   7694.21
Transfer/sec:      0.98MB
[benchmarking skipper done]
```
```
[warmup]
Running 3s test @ http://127.0.0.1:9090/lorem.html
Requests/sec:   7359.63
Transfer/sec:      0.94MB
[warmup done]
[benchmarking skipper]
Running 12s test @ http://127.0.0.1:9090/lorem.html
2 threads and 128 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    19.14ms …
```
=> add lb test proxy bench

cmd/skipper/main.go, proxy/proxy.go, skipper.go
add configurable timeouts for missing available in http.Transport timeouts for backend calls
=> add missing available in http.Transport timeouts

cmd/skipper/main.go, filters/builtin/builtin.go, filters/ratelimit/ratelimit.go, go.mod, go.sum, ratelimit/cluster.go, ratelimit/ratelimit.go, swarm/kubernetes.go, swarm/nodeinfoclient.go, swarm/swarm.go, swarm/utils.go
fix: clusterClientRatelimit was no initialized correctly
fix: kubernetes-swarm retry connection to kube-apiserver
fix: kubernetes-swarm add connection timeouts to http client
fix: add missing configuration to intialize swarm
fix: kubernetes-swarm tear down handling stops goroutine
fix: clusterClientRatelimit filter parsing
log: reduce log volume caused by swarm
=> fix swarm/clusterClient reatlimit integration

proxy/proxy.go, tracing/tracing.go
related:  #860
feature: trace filters and log filter names start/stop
feature: add hostname tag to ingress span to show the instance of the trace
feature: trace log retries
=> enhance tracing

readme.md
The `-routes-file` flag was missing from the example before the file
path argument.
=> Fix Docker command example

docs/reference/predicates.md
The docs state that regular expressions should be surrounded by slashes
(`/`), but just below, the `Host` example was surrounded by double
quotes.
In the `Host` paragraph, there were both slashes and quotes; the example
would fail. I have changed them to just slashes for consistency.
=> docs: Fix the Host predicate regex example

docs/kubernetes/ingress-usage.md, filters/auth/authclient.go, filters/auth/webhook.go, filters/filters.go, filters/filtertest/filtertest.go, proxy/context.go, proxy/proxy.go, script/script_test.go
Added the filter span to filter context so that it can used in the filters. Also implemented opentracing for webhook authentication so that a span is created and propagated forward to the downstream.
The result trace looks like as show below:
=> Added parent span to context so that it can be used in filters

filters/auth/authclient.go, filters/auth/tokeninfo.go, filters/auth/tokenintrospection.go
Using features implemented in PR #890 added opentracing into calls to the tokeninfo and tokenintrospection backends.
Signed-off-by: Arjun Naik <arjun.rn@gmail.com>
=> Added opentracing spans to calls to tokeninfo and tokenintrospection endpoints

skipper.go
Added support to pass in a tls.Config in skipper options which would be used for the proxy HTTP server instance. 
- Allows fine grained control over TLS settings for the proxy listener including ability to setup two way SSL.
- Existing CertPathTLS and KeyPathTLS settings left unchanged and will work as fallback options so that current usages do not break.
- No changes done in skipper main.go to make use of the new config.
Signed-off-by: UltraNemesis <dev.ajayabraham@gmail.com>
=> Full TLS Config for proxy server in skipper options

proxy/proxy.go, skipper.go
Expose ClientTLS in skipper options for passing client TLS settings
- Allows passing custom CA list or client certificates for connecting to backend's
Signed-off-by: UltraNemesis <dev.ajayabraham@gmail.com>
=> Expose ClientTLS in skipper options for passing client TLS settings

docs/reference/filters.md, filters/accesslog/control.go, filters/accesslog/control_test.go, filters/accesslog/disable.go, filters/accesslog/disable_test.go, proxy/proxy.go, proxy/proxy_test.go
Adds ability to enable/disable logs based on response code returned by the backend. This would allow more fine grained control for high throughput systems which don't want to log 2xx responses (~99.99% of responses) but still would like to log errors.
Fixes #909
=> Access log disable filter

filters/accesslog/control.go
from the failing check:
"assigning the result of this type assertion to a variable (switch prefix := prefix.(type)) could eliminate the following type assertions:"
=> fix static check for type switch

cmd/skipper/main.go, skipper.go
This commit adds command line flags for the following etcd options:
- Timeout
- Insecure
- OAuthToken
- Username
- Password
```bash
skipper -etcd-urls="https://etcd.example.org" -etcd-timeout=2s -etcd-insecure \
-etcd-oauth-token="deadbeef" -etcd-username="user" -etcd-password="pass"
```
```bash
...
-etcd-insecure
ignore the verification of TLS certificates for etcd
-etcd-oauth-token string
optional token for OAuth authentication with etcd
-etcd-password string
optional password for basic authentication with etcd
-etcd-prefix string
path prefix for skipper related data in etcd (default "/skipper")
-etcd-timeout duration
http client timeout duration for etcd (default 1s)
-etcd-urls string
urls of nodes in an etcd cluster, storing route definitions
-etcd-username string
optional username …
```
=> Add command line flags for all etcd options

skipper.go
PR #928 introduced the possibility to add TLS client config to the proxy.
It was also added to the main skipper.Options, but not passed on. This commit fixes this.
Signed-off-by: Martin Bertschler <mbertschler@gmail.com>
=> Make proxy client TLS work with skipper.Options

cmd/skipper/main.go, docs/reference/filters.md, filters/apiusagemonitoring/doc.go, filters/apiusagemonitoring/filter.go, filters/apiusagemonitoring/filter_clientmetrics_test.go, filters/apiusagemonitoring/filter_endpointmetrics_test.go, filters/apiusagemonitoring/pathinfo.go, filters/apiusagemonitoring/spec.go, filters/apiusagemonitoring/spec_test.go, filters/apiusagemonitoring/testutils_test.go, skipper.go
=> API usage monitoring filter improvements

docs/kubernetes/ingress-usage.md
Warning against multiple ingresses defining the same Host header
because that causes routing to become non-deterministic
=> Warning against multiple Ingresses

dataclients/kubernetes/definitions.go, dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/lbannotationfilters_test.go, dataclients/kubernetes/lbtarget_test.go, dataclients/kubernetes/lbtrafficswitch_test.go, dataclients/kubernetes/orderingbug_test.go, dataclients/kubernetes/update_test.go
Instead of fetching individual services/endpoints for every ingress, fetch them all at once when refreshing. In clusters with lots of ingresses and/or skippers this will bring down the apiserver RPS by Skipper from 1500+ to  15.
=> kubernetes: fetch endpoints/services once

skipper.go
check error and add a log if ListenAndServe call fails for supportListener
=> fix support listener not ready

docs/kubernetes/east-west-usage.md, docs/kubernetes/ingress-usage.md, docs/tutorials/development.md, mkdocs.yml
Use the native mkdocs page references where the `.md` is included in the
link. This has the advantage of generating the correct links and you
don't have to think about adding `/` to the end of the link or not.
Fixes a few broken links.
=> Use native Mkdocs page references

filters/apiusagemonitoring/noop.go, filters/apiusagemonitoring/spec.go, filters/apiusagemonitoring/spec_test.go
We don't want Skipper route creation to fail if a monitoring filter is provided with an invalid configuration. Let's make it less strict for now and return a `noop` filter if some information is missing.
Related to #949
=> Create noop filter in case of invalid monitoring filter config

docs/reference/filters.md
=> fix(apiusagemonitoring): add doc entry about no-op filter in case of invalid config

filters/apiusagemonitoring/filter.go, filters/apiusagemonitoring/filter_clientmetrics_test.go, filters/apiusagemonitoring/pathinfo.go
fixes #968.
With respect to #972 I state, that I see absolutely no need to complicate maintenance with an own low level `sync.Map` implementation, that for real use cases has a performance difference of ±5%. This is a premature optimization.
By the way, @maxim-tschumak checked this in a small micro benchmark. For congestion patterns, the sync.Map even outperformed the manual implementation, but this seems not to be very realistic for our use case.
=> fix: protect concurrent map access in apimonitoring (#968)

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
improves #979.
While this in no complete fix, it addresses memory issues when creating east-west-routes. It decrease the GC pressure during east-west-route creation by more than 50% for a single route, by 66% for two routes and up to 75% for four routes.
=> fix: reduced memory allocations for east-west-route creation (#979)

proxy/proxy.go, proxy/proxy_test.go
Fixes #982.
The url in the request has the selected host for any type of routes.
I am not sure if any more changes are needed but with a local websocket server, this fix was enough.
This area of the code is not tested at all and this PR does not try to improve upon the situation. The added test just cover the bug that is fixing.
=> Support loadbalancing routes for HTTP Upgrade handling.

proxy/proxy_test.go, proxy/upgrade_test.go
This does not achieve 100% coverage but it checks for some error conditions like the backend not being accessible or closing the connection too early.
It also validates that communication is working.
Closes #987 
Signed-off-by: Ângela Igreja <angela.igreja@zalando.de>
=> Add tests for HTTP Upgrade.

.travis.yml
Go 1.12 is the latest stable version of Go and also used in the CDP
build.
=> Update travis config to use Go 1.12.x

cmd/skipper/breakerflags.go, cmd/skipper/main.go, cmd/skipper/ratelimiterflags.go, docs/kubernetes/ingress-usage.md, docs/reference/filters.md, ratelimit/doc.go, ratelimit/ratelimit.go
fix -close-idle-conns-period flag handling to use plain time.Duration parsing and not adjusted string handling which does not work
=> fix close-idle-conns-period flag

skipper.go
Stop being graceful on SIGINT, which is used locally and not by any autmation, which use SIGTERM instead
=> Stop being graceful on SIGINT

docs/tutorials/auth.md, filters/auth/oidc.go, filters/auth/oidc_test.go
The downstream now receives the OIDC token and claims/userinfo in a header which it can use. Also improved the host extraction logic so that it can also be used with raw IPs.
=> OIDC filter enhancements and tutorial

docs/reference/filters.md, filters/log/log.go, filters/log/log_test.go
Adds an optional single input value to the unverifiedAuditLog filter
which acts as a lookup key for the Auth token in case you need to
log something other than the sub. If no parameter is provided for
the unverifiedAuditLog filter then it will default to "sub"
=> Make unverifiedAuditLog configurable

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
Fix memory spike in east west route creation, which drops memory usage from 6-9Gib to 200Mib instead with enabled eastwest routes, measured in different cases with 50k-70k routes and up to 50k ingress.
We will have to rethink the complex route cases with custom routes. Right now the custom routes from eastwest can overwrite the standard eastwest routes. 
=> fix memory spike in east west route creation

CODE_OF_CONDUCT.md, MAINTAINERS
we have to define key roles in the project to achieve silver in CII best practices https://bestpractices.coreinfrastructure.org/en/projects/2461
=> define key roles and cleanup maintainers file

docs/reference/filters.md, filters/auth/auth.go, filters/auth/tokeninfo.go, filters/auth/tokeninfo_test.go
This addresses https://github.com/zalando/skipper/issues/1035
If the OAuthTokeninfo* family of filters reject a request
due to invalid scopes, then we will return a 403 response
code instead of the 401 response code to indicate that the
token was successfully authenticated but access to the resource
was rejected due to missing scopes in the token.
=> Differentiate authentication and authorization issues in response codes

docs/reference/backends.md, proxy/proxy.go, proxy/proxy_test.go
When using dynamic backend, it is expected to use one of the
`setDynamicBackend*` filters to fill the host and scheme for the request
URL. However, there are cases in which we don't want to set it explicitly,
for example:
foo: * -> compress("text/html") -> <dynamic>
Now if I do something like:
curl -x http://skipper:9090 http://httpbin.org/anything
it complains about URL scheme and host not being set.
In this commit, the host and scheme part are automatically set for the
request URL before they're set from the statebag. This still allows the
user to modify host and scheme using the `setDynamicBackend*` filters
but if let unset, it will fallback to some sane defaults.
=> Set URL from Host and TLS in dynamic backend

tracing/tracers/lightstep/lightstep.go
this can be used to set tags present on any span, example
```
./bin/skipper -opentracing="lightstep tag=cluster=localhost token=<myToken> tag=foo=bar"
```
will set the tags `foo=bar` and `cluster=localhost` on any span
Signed-off-by: Hanno Hecker <hanno@zalando.de>
=> add tag= parameter for lightstep plugin

proxy/proxy.go
Currently, skipper creates spans that serializes to ~2.5 KB of payload in protobuf format based on my experiments. The main contributors to this are `skipper.route` tag, logs for marking filter start & done events, and the response stream events.
We can reduce the size by dropping these attributes however we may lose debugging abilities. To get around this, I propose we add feature flags under `OpenTracingParams` that would be passed to `Proxy`. In this way, we can enable logging these attributes when it is needed and keep it turned off by
default.
For now, we can drop `skipper.route` tag to reduce the size of the messages shipped for OpenTracing client.
In the future, we can have feature toggles to have the logs & additional tags enabled/disabled when necessary.
Relates to #1065 …
=> Drop `skipper.route` tag to reduce the size of the messages shipped

cmd/skipper/main.go, proxy/proxy.go, proxy/proxytest/proxytest.go, proxy/tracing.go, proxy/tracing_test.go, skipper.go
Overall the PR adds 2 CLI options that are used in `Proxy`: `opentracing-excluded-proxy-tags` & `opentracing-log-filter-lifecycle-events`.
Some notes on additional changes:
- As a part of the PR I also attempted to unify how we set tags on `Proxy` level. 
- We could also extend functionality offered by `proxyTracing` by moving `tracing.CreateSpan` there as well as it is not used anywhere outside of `Proxy`.
Relates to #1065
=> Add options to reduce the payload shipped per request

cmd/skipper/main.go
I missed these on https://github.com/zalando/skipper/pull/1066. Otherwise those flags are parsed but not passed to skipper while creating an instance.
Relates to #1065 as well.
Signed-off-by: Serbay Arslanhan <serbay.arslanhan@zalando.de>
=> Add missing opentracing related flags

cmd/skipper/main.go, packaging/Makefile
When working as a proxy, is usually need to pass to backend server certification data.
Currently skipper libs are prepared to fill this data, but there is not main flags to provide this info when using the main branch or the generated images.
This PR add two flags to provide these:
```
-client-tsl-cert string
TSL certificate files for backend connections, multiple keys may be given comma separated - the order must match the keys
-client-tsl-key string
TSL Key file for backend connections, multiple keys may be given comma separated - the order must match the certs
```
=> add init flags to pass certificates files to connect with backend

net/net.go, net/net_test.go, predicates/source/source_test.go
fix source from last predicate was based on wrong assumptions, we do not get parsed headers into string slice, but a plain string, so use Header.Get and work on the string ourselves
reported by a user
=> fix source from last predicate

filters/scheduler/lifo.go, proxy/proxy.go
make sure each lifo done() is called and handle done() for multiple lifo() filters
=> fix stuck lifo() -> done() notifications

proxy/upgrade.go
kubectl exec uses POST and reviewing rfcs based on an internal request, show that upgrade headers are fine with non GET requests
=> fix upgrade headers for kubectl exec

proxy/proxy.go
This adds span logs for when roundtrip to backend is started and ended. This should enable us to better understand when a backend was called and how long it took to get the response.
Without this log we only see `dial_context` logs in some cases where a new connection has to be established but often we don't see it when a connection is re-used meaning we only see the `stream_Headers` logs when we start to stream the response from the backend back to the client calling skipper.
Example of how this looks:
Here the backend has a latency of `50ms`
=> Add roundtrip start/end span logs

dataclients/kubernetes/definitions.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go
feature: #549 ingress with backend svc type ExternalName to do a proxy call to the externalName defined in the target service
=> support ingress with service type ExternalName

proxy/context.go, proxy/proxy.go
fix #1103 http headers should be sent before the body
=> fix chunked transfer-encoding

skptesting/benchmark.inc
avoid conflicting support listeners when more skipper instances are started during a test
=> fix: benchmark startup

Makefile, dataclients/kubernetes/kube_test.go
- update the check-fmt Makefile task to match fmt
- fix formatting of code file that was formatted without the `-s` flag 
=> fix format check to be as strict as format

docs/reference/predicates.md, go.mod, go.sum, predicates/cron/cron.go, predicates/cron/cron_test.go, skipper.go
Link to the small library that I created for this: https://github.com/sarslanhan/cronmask
Summary of the features removed because they don't match the use case:
- [Non-standard characters](https://en.wikipedia.org/wiki/Cron#Non-standard_characters)
- Year field - We could probably add this as well if you see the need.
- Command section
- Text representation of the fields "month" and "day of week"
Relates to https://github.com/zalando/skipper/issues/1082
=> Add "Cron" pred. that supports cron-like expressions to match routes

skipper.go
when a file defined by the -access-log and -application-log flags doesn't exist, skipper currently cannot create it. This PR aims to fix it.
=> add create flag for log output files

docs/reference/predicates.md
List item is misaligned due to this missing line https://opensource.zalando.com/skipper/reference/predicates/#cron
=> Add the missing new line Cron predicate documentation

proxy/proxy.go
log error from stdlib that we do not handle good enough and we want to differentiate error from backend and error during roundtrip
=> differentiate error from backend and error during roundtrip

docs/reference/filters.md, filters/apiusagemonitoring/filter_clientmetrics_test.go, filters/apiusagemonitoring/filter_endpointmetrics_test.go, filters/apiusagemonitoring/pathinfo.go, filters/apiusagemonitoring/spec.go, filters/apiusagemonitoring/spec_test.go, filters/apiusagemonitoring/testutils_test.go
the API monitoring tag supports multiple instances of an application (such as staging and prod) in the same k8s cluster.
=> recognize api monitoring tag

skipper.go
Provide a way to specify the `metrics.Metrics` backend used by skipper to report metrics.
Fix #1151
=> add option to provide a metrics backend instance (#1151)

docs/reference/filters.md, filters/builtin/builtin.go, filters/tracing/baggagetotag.go, filters/tracing/baggagetotag_test.go, tracing/tracingtest/testtracer.go
Add baggageItemToTag filter
This filter adds an opentracing tag for a given baggage item in the trace. 
Syntax:
```
baggageItemToTag("<baggage_item_name>", "<tag_name>")
```
Example: If a trace consists of baggage item named `foo` with a value `bar`. Adding below filter will add a tag named `baz` with value `bar` 
```
baggageItemToTag("foo", "baz")
```
=> feat: Add baggageItemToTag filter

tracing/tracers/jaeger/jaeger.go, tracing/tracers/jaeger/jaeger_test.go
Besides adding support for tags, the logic for parsing options has been moved into a dedicated function to be able to add tests.
I had a hard time understanding how exactly options need to be passed in via the `-opentracing` flag. The tests can serve as a reference for that. That's why I added them.
Fixes #1162
=> Add support for tags in jaeger tracing implementation

cmd/skipper/main.go, dataclients/kubernetes/definitions.go, dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, docs/reference/filters.md, filters/apiusagemonitoring/filter_clientmetrics_test.go, filters/apiusagemonitoring/filter_endpointmetrics_test.go, filters/apiusagemonitoring/spec.go, filters/apiusagemonitoring/spec_test.go, filters/builtin/builtin.go, filters/builtin/creationmetrics.go, filters/builtin/creationmetrics_test.go, filters/builtin/originmarker.go, filters/builtin/originmarker_test.go, skipper.go
Adds a metric that measures the route creation time.
The end time of the measurement is the successful creation of the route.
The start time of the measurement is taken from..
1. the creation time of ingresses for the kube DataClient - this creates the `routeCreationTime.default` metric
2. a provided creation time of apiUsageMonitoring filter - this creates the `routeCreationTime.apiUsageMonitoring` metric
3. other DataClients are not supported yet
=> monitor route creation time

proxy/proxy.go, proxy/ratelimit_test.go
relates to https://github.com/zalando/skipper/pull/1171
=> fix: allow ratelimiting for shunt routes

Makefile
=> use fixed version of staticcheck for Go1.13

dataclients/kubernetes/kube.go
I spend 2 hours yesterday fighting with Skipper because it didn't log this error:
```
Failed to find target port for service xx, fallback to service: GetTargetPort: target port not found [xx 80 http] given http
```
Only after enabling debug mode I discovered it.
=> Use Errorf when port defition is wrong

scheduler/scheduler.go
fixing counter causing fake warnings
=> fix warning on multiple lifo filters

eskipfile/watch.go
delete routes only on ENOEXIST when using file watching
=> delete routes only on ENOEXIST when using file watching

Makefile, ratelimit/cluster_test.go
add redis based cluster ratelimits to coverage and test the dispatch to create different cluster ratelimits
=> increase cluster ratelimit coverage report

docs/reference/filters.md
Note in the docs that `inlineContent` filter is special and must be last in the chain.
=> Note that inlineContent filter is special

routing/matcher.go, routing/matcher_test.go, routing/predicates_test.go
=> keep the trailing slash in the path for regexp matching

go.mod
revert the go version in go.mod, as it is set automatically by go.
=> set the go.mod go version to the automatically applied one

docs/reference/filters.md, filters/flowid/ulid.go
Clarify that flowIds must be of a certain format to be reusable
=> Clarify that flowIds must be of a certain format to be reusable

dataclients/kubernetes/kube.go, dataclients/kubernetes/update_test.go
attempt 2
previous attempt: https://github.com/zalando/skipper/pull/1197
**The problem:**
The `DataClient.LoadUpdate()` should return any routes only when there were any changes, but only the changes: updated routes, or new routes, and it should return the IDs of the deleted routes. Otherwise, it should return nil for each return argument. When there are any changes, the routing tree is recreated. When there are no changes, there's no new routing tree created.
See also: https://godoc.org/github.com/zalando/skipper/routing#hdr-Data_Clients
The Kubernetes DataClient, in order to be able to detect the changes, stores the current generation of routes, and when the Kubernetes API is polled again, it compares the new routes with the old ones, to see if there were any changes.
The Kubernetes …
=> set origin markers only when there were any changes to the routes

cmd/skipper/pluginflags_test.go
There was a [build failing](https://travis-ci.org/zalando/skipper/builds/598737424?utm_source=github_status&utm_medium=notification) because of these tests.
This is happening because a map is iterated in order to fill `[][]string`. The order is not guaranteed.
=> Fix flaky tests

filters/ratelimit/ratelimit.go
removing this warning, because it's unactionable for those users who don't compile the binary on their own. When the filter is actually referenced in the route config, a warning still will be logged.
=> remove reporting deprecated filter from startup

filters/cors/cors.go, filters/cors/cors_test.go
If the backend sets the `Access-Control-Allow-Origin` header, the current corsOrigin filter appends another value. This pr makes it override the value instead.
Example chrome error from having multiple values in the allowed origin header: 
```
Access to XMLHttpRequest at 'https://4ce88b85.ngrok.io' from origin 'https://59298408.ngrok.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'https://nsns.ngrok.io, https://59298408.ngrok.io', but only one is allowed.
```
=> Allowed origin header should be a single value, not a list

eskip/eskip.go, eskip/eskip_test.go
The issue is that as soon as one has at least 3 prepend filters, all routes get the filters from the last route.
=> fix bug when having at least 3 prepend filters

config/config.go, docs/operation/operation.md, proxy/proxy.go, skipper.go
A new skipper argument/config option was added.
`-disable-http-keepalives` makes each request use new connection to the
backend.
=> Added option to disable HTTP keepalives

docs/reference/filters.md, filters/builtin/backendisproxy.go, filters/builtin/backendisproxy_test.go, filters/builtin/builtin.go, filters/filters.go, proxy/proxy.go, proxy/proxy_test.go
The filter notifies the proxy that the backend this request is going to be sent to is also
proxy. This means that the request is going to be sent the usual proxy way:
// HTTP request
GET http://example.com HTTP/1.1
...
// HTTPS request
CONNECT https://example.com HTTP/1.1
...
Example:
foo1:
*
-> backendIsProxy()
-> "http://proxy.example.com";
foo2:
*
-> backendIsProxy()
-> <roundRobin, "http://proxy1.example.com", "http://proxy2.example.com">;
foo3:
*
-> setDynamicBackendUrl("http://proxy.example.com")
-> backendIsProxy()
-> <dynamic>;
Signed-off-by: Stepan Bujnak <stepan.bujnak@gmail.com>
=> Added new filter backendIsProxy

Makefile
The default setting for GOPROXY is "https://proxy.golang.org,direct" since go version 1.13.
With current implementation, the option direct is missing, that is fallback to original sources.
=> Remove excplict set of GOPROXY

net/httpclient.go
=> Fix: CPU hot busyloop by setting a default timeout to 30s, if not set

go.mod, go.sum, ratelimit/redis.go
- upstream issue was fixed in go-redis v7 (beta), so we switch to TxPipeline to be safe
- add EXPIRE call to remove keys automatically, if we have no writes since specified time window + 1s
=> fix two small issues in redis usage by cluster*Ratelimit filters

docs/reference/filters.md, filters/auth/authclient.go, filters/auth/doc.go, filters/auth/webhook.go, filters/auth/webhook_test.go
Update the `webhook` filter so that it can take a second argument, a comma-separated list of header names, that should be copied from the webhook response to the continuing request, if the webhook response is authorized.
i.e. `webhook("auth-endpoint", "Headers-To-Copy,And-More")`
=> Forward headers from webhook filter responses

queuelistener/listener.go
fix #1268 and expose TCP lifo runtime config via log
=> expose TCP lifo runtime config via log

filters/auth/oidc.go, filters/auth/oidc_test.go
This solves a cookie size overflow issue #1089 where at some point the cookie is not accepted by the browser due to its size
* adding a `chunkCookie` function that splits an existing cookie based on limits defined at `cookieMaxSize`
* the value of `cookieMaxSize` is taken by well-known projects and verified with Chrome
* the approach is `non-deterministic` as the signature of cookies might change over time
* mergerCookies return a single (virtual) cookie, ordered by the suffix. This approach should be least invasive to the current code
* switching serialization to Base64 instead of Base16 since it reduces the transaction data by 33% and is considered common practice. It does not influence other cookies of Skipper
=> implementing cookie chunks for OIDC

proxy/upgrade.go, proxy/upgrade_test.go
In case the backend rejects a connection upgrade and returns something other than `101` we just responded with the HTTP status code as the body e.g. `Bad Request`
Instead we should respond with the body of the response which may have important information on why it failed.
=> Forward body from backend on connection upgrade errors

config/config.go, config/config_test.go, config/test.yaml, skipper.go
feature: add optional startup checks, that are checked to return 200 before we start listener -startup-checks="https://www.zalando.de/,https://www.google.com/,http://127.0.0.1:12345/health"
=> feature: add optional startup checks

docs/reference/filters.md, docs/tutorials/auth.md, filters/auth/auth.go, filters/auth/oidc.go, filters/auth/oidc_introspection.go, filters/auth/oidc_introspection_test.go, filters/auth/oidc_test.go, go.mod, go.sum, skipper.go
This filter is intended to be chained after one of `OAuthOidc*Claims` OIDC flow provider, making use of the token information saved in `stateBag` to classify **authorization**
* It leverages the query syntax of `GJSON` to express a matching of the token.
* It allows validation per path request, matching one or more queries.
* Each argument of the filter expresses a path/query relation, one or several paths can be defined
* The first positive match wins
Format:
`<path>:[<query>]`
Following example statements would be possible:
```
"/some/path:@_:sub==\"somesub\")"
"/some/path:[@this].#(sub==\"somesub\")"
"/another/path:groups.#(%\"CD-*\")"
"/asdf/:groups.#(%\"CD-*\") 'groups.#(%\"*-Test-Users\")' groups.#(%\"Purchasing-Department\")"
"/:groups.#(%\"Purchasing-Department\")"
```
These would …
=> Authorization support for OIDC

docs/kubernetes/deploy/deployment/deployment.yaml, docs/kubernetes/deploy/deployment/rbac.yaml, docs/kubernetes/ingress-controller.md
doc: update deployment manifests to enable routegroups via rbac.
https://github.com/zalando/skipper/pull/1300 should be merged before this one, because we reference the v0.11.40, which fixes the log spam
=> doc: update deployment manifests to enable routegroups via rbac.

dataclients/kubernetes/clusterclient.go, secrets/file.go, secrets/file_test.go
fix https://github.com/zalando/skipper/issues/1305 validated in a dev cluster
fix: SecretPaths should support symlink to file for Kubernetes secrets and clusterclient should report errors for this more clearly
=> fix: SecretPaths should support symlink to file for Kubernetes secrets

skipper.go
Add `Methods` predicate to custom bundled predicates during startup.
Related: https://github.com/zalando/skipper/pull/1309
=> Add predicate Methods to custom bundled predicates

Makefile, skipper.go
removing deprecated certificate naming
=> remove deprecated certificate naming

docs/reference/filters.md, filters/builtin/redirect.go, filters/builtin/redirect_test.go
This allows you to skip the `location` argument to `redirectTo`:
```diff
-redirectTo(301, "")
+redirectTo(301)
```
Much nicer, right? :)
=> RedirectTo > Make location argument optional

packaging/helm/skipper-aws/.helmignore, packaging/helm/skipper-aws/Chart.yaml, packaging/helm/skipper-aws/README.md, packaging/helm/skipper-aws/crds/awsiamroles.yaml, packaging/helm/skipper-aws/crds/routegroups.yaml, packaging/helm/skipper-aws/templates/external-dns/aws-iam-role.yaml, packaging/helm/skipper-aws/templates/external-dns/deployment.yaml, packaging/helm/skipper-aws/templates/external-dns/rbac.yaml, packaging/helm/skipper-aws/templates/external-dns/svc.yaml, packaging/helm/skipper-aws/templates/external-dns/vpa.yaml, packaging/helm/skipper-aws/templates/ingress-controller/aws-iam-role.yaml, packaging/helm/skipper-aws/templates/ingress-controller/deployment.yaml, packaging/helm/skipper-aws/templates/ingress-controller/rbac.yaml, packaging/helm/skipper-aws/templates/ingress-controller/vpa.yaml, packaging/helm/skipper-aws/templates/kube-aws-iam-controller/deployment.yaml, packaging/helm/skipper-aws/templates/kube-aws-iam-controller/rbac.yaml, packaging/helm/skipper-aws/templates/kube-aws-iam-controller/vpa.yaml, packaging/helm/skipper-aws/templates/kube2iam/daemonset.yaml, packaging/helm/skipper-aws/templates/kube2iam/psp.yaml, packaging/helm/skipper-aws/templates/kube2iam/rbac.yaml, packaging/helm/skipper-aws/templates/skipper/deployment.yaml, packaging/helm/skipper-aws/templates/skipper/hpa.yaml, packaging/helm/skipper-aws/templates/skipper/psp.yaml, packaging/helm/skipper-aws/templates/skipper/rbac.yaml, packaging/helm/skipper-aws/templates/skipper/service-internal.yaml, packaging/helm/skipper-aws/templates/skipper/service.yaml, packaging/helm/skipper-aws/templates/skipper/skipper-redis-service.yaml, packaging/helm/skipper-aws/templates/skipper/skipper-redis.yaml, packaging/helm/skipper-aws/values.yaml
fix https://github.com/zalando/skipper/issues/1233 and add a helm chart which can optionally enable clusterRatelimits, eastwest, and use kube2iam or kube-aws-iam-controller to get AWS credentials for external-dns and kube-ingress-aws-controller
=> add helm chart

docs/reference/scripts.md, script/README.md
I checked the code and `redirectTo("http://localhost:9980")` seems invalid? This fixes it.
=> Docs > Fix wrong redirectTo

docs/reference/filters.md, filters/builtin/builtin.go, filters/builtin/mod_header.go, filters/builtin/mod_header_test.go
This allows you to do things like this:
```
add_www: Host("^example\.") -> modHost("example.(\w+)", "www.example.$1") -> redirectTo(301) -> <shunt>;
```
or
```
add_www: Host("^example\.") -> modHost("(.*)", "www.$1") -> redirectTo(301) -> <shunt>;
```
```
curl -I -H 'Host: example.com' localhost:9090/hello
HTTP/1.1 301 Moved Permanently
Location: https://www.example.com/hello
Server: Skipper
Date: Sat, 29 Feb 2020 10:26:56 GMT
```
=> Add modRequestHeader filter

docs/reference/filters.md
Explain content type for inlineContent() filter
=> Docs > Explain content type argument

eskip/lexer.go, eskip/parser_test.go, eskip/string.go, eskip/string_test.go
This is a different approach to solve #1339.
I have the following route:
```eskip
test:
Path("/test")
-> inlineContent("Line 1\nLine 2")
-> <shunt>;
```
When I run this, Skipper will return my content wrong:
```
$ http get localhost:9090/test
HTTP/1.1 200 OK
Content-Length: 14
Content-Type: text/plain; charset=utf-8
Date: Fri, 06 Mar 2020 14:52:13 GMT
Server: Skipper
Line 1\nLine 2
$ http get localhost:9090/test | hexdump
0000000 4c 69 6e 65 20 31 5c 6e 4c 69 6e 65 20 32
000000e
// 5c = \
// 6e = n
```
As you can see, the `\n` is not a real newline char (10). 
In the log of Skipper I see this:
```
[APP]INFO[0156] route settings, update, route: test: Path("/test") -> inlineContent("Line 1\\nLine 2") -> <shunt> 
```
It escaped the escape char.
The only way to get this working is by creating …
=> Support newlines in lexer

dataclients/kubernetes/httpsredirect_test.go, dataclients/kubernetes/redirect.go, dataclients/kubernetes/testdata/routegroups/https-redirect/custom-code.eskip, dataclients/kubernetes/testdata/routegroups/https-redirect/no-redirect-for-east-west.eskip, dataclients/kubernetes/testdata/routegroups/https-redirect/no-redirect-if-proto-predicate.eskip, dataclients/kubernetes/testdata/routegroups/https-redirect/redirect-implicit-route.eskip, dataclients/kubernetes/testdata/routegroups/https-redirect/redirect-simple.eskip, docs/reference/architecture.md, docs/reference/predicates.md, docs/tutorials/basics.md, eskip/eskip_test.go, predicates/cookie/cookie.go, routing/datasource.go, routing/matcher.go, routing/routing.go, routing/weight_test.go
I noticed this odd looking double Regexp in my Kubernetes Skipper instance:
```eskip
route: 
Host(/^www[.]xxx[.]no$/) && 
PathRegexp(/.*/) && 
PathRegexp(/.*/) && 
Header("X-Forwarded-Proto", "http")
-> <roundRobin, "http://xxx:80">;
```
Turns out it's by design:
https://github.com/zalando/skipper/blob/ae2a3bfe499c888154a630bbab008de4a84b11c3/dataclients/kubernetes/redirect.go#L90-L99
Let's fix this.
=> Introduce Weight predicate

predicates/traffic/traffic_test.go
=> Reduce N to prevent flaky tests on MacOS

dataclients/kubernetes/eastwest.go, dataclients/kubernetes/ingress.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/path_test.go, dataclients/kubernetes/redirect.go, dataclients/kubernetes/routegroup.go, dataclients/routestring/string_test.go, eskip/eq.go, eskip/eq_test.go, eskip/eskip.go, eskip/eskip_test.go, eskip/json.go, eskip/predicates.go, eskip/string.go, eskip/string_test.go, loadbalancer/concurrency_test.go, proxy/debug_test.go, proxy/idle_test.go, routing/datasource.go, routing/matcher_test.go, routing/predicates_test.go, routing/routing_test.go, routing/testdataclient/example_test.go
This extracts the `Path` predicate to `predicates` package.
I also introduced a mechanism to guard against duplicate predicates like `Weight`, `Path` and maybe more in the future. See `AppendPredicate` and `PrependPredicate` in `eskip.go`.
=> Release v1 move predicates

dataclients/kubernetes/kube_test.go, eskip/predicates.go, eskip/predicates_test.go
=> Guard against mixed usage of `Path` and `PathSubtree`

docs/kubernetes/routegroups.md
No longer needed now that https://github.com/kubernetes-sigs/external-dns/releases is merged, right?
=> Docs > Route Groups > Remove important note

docs/reference/backends.md
Filters always need to be lowercase first.
=> Docs > Lowercase filter

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml, packaging/helm/skipper-aws/crds/routegroups.yaml
The backend algorithms should be specified like so, `roundRobin`/`random`/`consistentHash`: https://github.com/zalando/skipper/blob/master/loadbalancer/algorithm.go#L113-L129.
This PR aligns the CRD definitions to this.
When applying a route group with, say, `roundRobin`, I get
```
routegroups.zalando.org "test" was not valid:
<...>
spec.backends.algorithm in body should be one of [roundrobin random consistent-hash]
```
but if i apply `roundrobin`, I get an error in skipper saying `unsupported algorithm`.
Signed-off-by: Daniel Middlecote <dlmiddlecote@gmail.com>
=> Fix: Align CRD backend algorithms to those allowed by skipper

proxy/clienttimeout_test.go, proxy/proxy.go
Instead of logging:
```
time="2020-03-31T14:44:16Z" level=error msg="error while proxying, route kube_frontend__frontend__www_ticketswap_nl with backend , status code 499: dialing failed false: context canceled"
```
it will now log:
```
time="2020-03-31T14:44:16Z" level=error msg="error while proxying after 5m41s, route kube_frontend__frontend__www_ticketswap_nl with backend , status code 499: dialing failed false: context canceled"
```
Also, discovered that when you use loadbalanced backends, the error log will be an empty string:
```
time="2020-03-31T14:44:16Z" level=error msg="error while proxying, route kube_frontend__frontend__www_ticketswap_nl with backend , status code 499: dialing failed false: context canceled"
```
Look at `with backend , `. 
This is because the single `Backend` …
=> Log call duration, backendType + backend on proxy error

filters/builtin/compress_test.go
removing early close of the response body as it is closed by the enclosing function
=> remove early close of the response body

proxy/proxy.go
Looks better in the logs.
```
level=error msg="client canceled after 48.961234ms, route x with backend lb http://100.109.163.119:80, flow id -, status code 499: dialing failed false: context canceled"
```
Kinda weird, that single dash.
Much better:
```
level=error msg="client canceled after 48.961234ms, route x with backend lb http://100.109.163.119:80, flow id not set, status code 499: dialing failed false: context canceled"
```
=> Change default value for no flow id

proxy/fastcgi/fastcgi.go, proxy/proxy.go
Please review commit-by-commit.
=> Improvements for FastCgi

eskipfile/example_test.go, etcd/example_test.go, filters/builtin/redirect_test.go, filters/example_test.go, filters/filtertest/example_test.go, proxy/breaker_test.go, proxy/example_test.go, proxy/idle_test.go, proxy/loopback_test.go, proxy/pathpatch_test.go, proxy/proxy.go, proxy/proxy_test.go, proxy/proxytest/proxytest.go, proxy/ratelimit_test.go, proxy/tracing_test.go, proxy/upgrade_test.go, skipper.go, skipper_test.go
Now that `Proxy.New` is removed, can we rename `Proxy.WithParams` to `Proxy.New`? I changed this in 3e353e1. We can remove the commit if this is not what you want.
=> V1 > Remove deprecated Proxy.New

proxy/proxy.go
This makes it easier to debug why a proxy request failed.
```
[APP]ERRO[0040] error while proxying after 225.477µs, route php with backend network fastcgi://0.0.0.0:55212, flow id not set, status code 500: dialing failed false: gofast: failed creating client: dial tcp 0.0.0.0:55212: connect: connection refused, remote host: 1.2.3.4, request: "GET /hello HTTP/1.1", user agent: "HTTPie/2.0.0" 
```
=> Log request info on proxy error

queuelistener/listener.go, queuelistener/listener_test.go
fix measuring the connection count in cases when the server sides closes connections multiple times
=> fix measuring the connection count in TCP-LIFO

docs/reference/predicates.md, predicates/traffic/traffic.go, predicates/traffic/traffic_test.go
This is not optimal (because the user should just delete the other routes), but in some cases it makes it a lot easier to define the routes. An example is defining a route where the weight passed to the `Traffic()` predicate is parameterised and then changing it between `0.0` and `1.0`. The users would expect `1.0` to work, but currently it doesn't.
Update the documentation and the comments to mention that both values are now allowed (`0.0` used to work but was documented as not working).
=> Traffic(): allow weight of 1.0

docs/reference/filters.md, filters/auth/oidc.go, filters/auth/oidc_test.go
Similar to [Keycloak Gatekeeper Custom Claim Headers](https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/oidc/keycloak-gatekeeper.adoc#custom-claim-headers) we need Skipper to inject headers to upstream endpoints to provide user identity.
As of now the "Skipper-Oidc-Info" header provides this information but in a custom, not ready to use format which would require to adapt each backend application.
Like Gatekeeper this information should be possible to be specified per use case on the ingress annotation level.
This implementation uses the `GJSON` syntax already used for other purposes to define and parse the information that is requested and inject as the defined header name.
For backward compatibilty, this additional field is optional, falling back to …
=> flexible upstream headers

docs/reference/scripts.md, script/README.md, skptesting/benchmark-lua.sh, skptesting/redir.eskip, skptesting/strip-query-lua.eskip, skptesting/strip-query.eskip
* Fixes redirectTo status
* Fixes port number for [benchmarking strip-lua]
* Updates examples of benchmark result
* Fixes -help
=> Fixes lua benchmark

config/ratelimiterflags.go, config/ratelimiterflags_test.go, ratelimit/ratelimit.go
Relates to #1428 
The cluster-based rate-limiting implementations are available but couldn't be passed in via command-line flags.
This PR enables `clusterClient` and `clusterService` as valid types for rate-limiting as well as the `group` flag.
=> Fix -ratelimit flag to accept cluster based options

filters/auth/oidc.go
This is a security issue mitigation, where a potential attack would be that a person is sending manipulated header that are parsed for authentication.
Currently the OIDC header are `.Add` that is an `append` operation, which keeps the user generated values as precedence.
This PR solves the issue by changing the header output to a `.Set` operation which replaces potential existing headers accordingly.
=> OIDC header integrity

config/config.go, dataclients/kubernetes/clusterclient.go, dataclients/kubernetes/clusterclient_test.go, dataclients/kubernetes/kube.go, docs/kubernetes/routegroups.md, skipper.go
Closes #1452.
Few todos that I'd love some pointers on, if possible.
todo:
=> Filter RouteGroups via an annotation

docs/tutorials/shadow-traffic.md
The note was not understandable for me because "weight" means two different things in this tutorial (weight of traffic switching vs. weight of a Skipper route).
=> Shadow Traffic: make clear what "weight of the route" means

proxy/proxy.go
=> log: fix concatenation of error messages in proxy error logs

filters/diag/logheader.go, filters/diag/logheader_test.go
compatible version of logHeader() filter which logs the request headers.
logHeader support 2 args: "request" and "response"
The new version also logs if we have a non nil body
=> logHeader filter to have options "request" and "response"

docs/reference/scripts.md, script/README.md, script/load_ok.lua, script/not_a_filter.lua, script/script.go, script/script_test.go
* Compiles lua script [1] during filter initialization
to avoid compilation on every filter run
* Detects presence of request and response functions during filter initialization
to avoid presense check on every filter run
* Uses metatable for context value access
to avoid initialization of unused context fields
Applied optimisations led to lua performance increase from 42% to
80% of native performance on redirect benchmark
1. https://github.com/yuin/gopher-lua#sharing-lua-byte-code-between-lstates
=> Implements lua scripting optimizations

dataclients/routestring/example_test.go, filters/auth/tokenintrospection_test.go
* in filters/auth/tokenintrospection_test.go creates downstream servers once for all test cases
* in dataclients/routestring/example_test.go introduces delay for server to startup
Tests flakiness detected via:
```
$ while go test -count=1 github.com/zalando/skipper/filters/auth; do : ; done
ok      github.com/zalando/skipper/filters/auth 3.950s
...
ok      github.com/zalando/skipper/filters/auth 3.851s
time="2020-07-09T15:54:06+02:00" level=error msg="Failed to create new provider no%20url: Get \"no%20url/.well-known/openid-configuration\": unsupported protocol scheme \"\"."
time="2020-07-09T15:54:08+02:00" level=error msg="Error while calling tokeninfo: Get \"http://127.0.0.1:45657/test-auth\": net/http: timeout awaiting response headers."
time="2020-07-09T15:54:08+02:00" level=error …
```
=> Mitigates server startup race conditions in tests

filters/auth/oidc.go
we had a confusing output in our logs which displayed none as a  property value.
this pull request changes the property name of the OauthState Nonce
=> Fixing typo in OauthState which was confusing in the log output

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml
* Add a regex for hostnames (matching one used for Ingress validation).
* Fix array validation to use `minItems` (`minLength` doesn't do anything).
* Make `hosts` required; having a RouteGroup that matches everything is an extremely unlikely case, so I'd rather optimise for the users not being able to break anything in a cluster by deploying a match-all RG.
=> Improve RouteGroup CRD schema

proxy/proxy.go
When trying to access the ParentSpan() inside a Response filter like this:
```go
fc.ParentSpan()
```
Which is common when trying to instrument filters like this:
```go
filterSpan := fc.Tracer().StartSpan("myCoolFilter", opentracing.ChildOf(fc.ParentSpan().Context()))
```
The ParentSpan still returns the request_filters span, since the filtersSpan created in the `applyFiltersToResponse` didn't set the parentSpan variable before passing the context.
In the image bellow, the `headerSize` is a Response filter, but the span ends up in the request_filter span:
=> setting the parentSpan for response filters

.gitignore, config/config.go, dataclients/kubernetes/kube.go, dataclients/kubernetes/kubernetestest/fixtures.go, dataclients/kubernetes/routegroup.go, dataclients/kubernetes/routegroups_test.go, dataclients/kubernetes/testdata/routegroups/tracing-tag/explicit-routes-no-backend.eskip, dataclients/kubernetes/testdata/routegroups/tracing-tag/explicit-routes-no-backend.kube, dataclients/kubernetes/testdata/routegroups/tracing-tag/explicit-routes-no-backend.yaml, dataclients/kubernetes/testdata/routegroups/tracing-tag/explicit-routes.eskip, dataclients/kubernetes/testdata/routegroups/tracing-tag/explicit-routes.kube, dataclients/kubernetes/testdata/routegroups/tracing-tag/explicit-routes.yaml, dataclients/kubernetes/testdata/routegroups/tracing-tag/implicit-routes.eskip, dataclients/kubernetes/testdata/routegroups/tracing-tag/implicit-routes.kube, dataclients/kubernetes/testdata/routegroups/tracing-tag/implicit-routes.yaml, skipper.go
This is a simple change that adds an idiomatic OpenTracing tag (`skipper.backend_name`) for all routes originating from RouteGroups containing a backend reference name. That can be very helpful in debugging (clearly visible which logical backend was serving instead of seeing just actual service IPs) and metrics gathering/comparison (imagine comparing metrics between a primary and canary or AB test).
It's implemented adding an implicit `tracingTag` filter to all generated routes. (implemented this way for RouteGroups only as by default Skipper backends do not have names so it is not universal to all sources of routes).
=> tracingTag with a backend name for RouteGroup-generated routes

loadbalancer/concurrency_test.go
Increases route **poll** timeout to fit into 5% distribution tolerance
Fixes #1481 
=> Fixes flaky TestConstantlyUpdatingRoutes

metrics/metrics.go, metrics/prometheus.go, skipper.go
We are maintaining several custom filters and thus use skipper as a library. Prometheus is our monitoring system of choice.
The default API methods of the `metrics` package like `IncCounter()` or `UpdateGauge()` sometimes do not cut it for us.
In some cases we would like to be able to change the name of the metric instead of the label `key` to aid in discovery. Or it would be useful to add more than one label to a metric.
This change allows passing a registry down to the Prometheus implementation of the `metrics` package. This makes it possible to create custom metrics for filters, register them with the custom registry and instruct skipper to use that custom registry.
The code falls back to the current behavior of creating a new registry if no custom registry is passed from the outside.
=> Allow setting a custom Prometheus registry

proxy/upgrade.go
When firefox sends a websocket request, it sends it with a connection header of
Connection: keep-alive, Upgrade
Due to skipper having multiple definitions of an upgrade request, these requests are rejected with 400 bad request. This patch unifies skippers idea of what an upgrade request is.
=> Unify detection of upgrade requests.

.github/workflows/master.yaml, .github/workflows/pr.yaml, filters/auth/oidc_introspection.go, filters/auth/oidc_test.go
- upgrade go version in github actions
- fix string conversion from rune for go1.15 compiler checks
=> upgrade to go1.15

filters/builtin/compress.go
On a cluster with a lot of routes where many of those routes activate the `compress()` filter, skipper uses significantly more CPU on route updates.
We saw an increase of 100% - 400% of CPU usage during route updates, e.g. a Kubernetes worker joining or leaving or a new Deployment resource being created. Sometimes skipper pods also started to OOM.
This issue can be traced down to the check for validity of the compression level in the spec of the `compress()` filter.
This change replaces the creation of writers to check for validity of the compression level with comparing the levels directly without creating a writer for each type of compression.
=> Validate compression level in compress filter by comparing integers

filters/auth/authclient.go
AuthClient used by `oauthTokeninfo*` filters does not consume response body when token is invalid:
https://github.com/zalando/skipper/blob/e3372b500d401c8133367fdcb208f35e73ee4022/filters/auth/authclient.go#L110-L114
According to https://golang.org/pkg/net/http/#Client.Do
> If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) 
may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request.
That is requests with invalid token prevent tokeninfo TCP connection reuse which leads to higher latencies.
Consider the following setup:
```
$ cat /tmp/tokeninfo.eskip 
tokeninfo: Path("/oauth2/tokeninfo")
-> status(400) -> inlineContent("{\"error\":\"invalid_request\",\"error_description\":\"Access Token …
```
=> Drains tokeninfo response body to enable TCP connection reuse

eskipfile/watch_test.go
Adds test file error handling to simplify [flaky watch_test.go](https://github.com/zalando/skipper/runs/1028484357?check_suite_focus=true) debugging when it fails next time as it is hard to reproduce the failure reliably.
=> Adds watch_test.go error handling

docs/reference/filters.md, filters/builtin/header_test.go, filters/builtin/headerfilter.go
Template resolution is implemented for `setRequestHeader`, `appendRequestHeader`, `setResponseHeader` and `appendResponseHeader` filters.
Uses filter context path params and string state bag values to resolve template variables.
See #1453, #1444
=> Implements variable template resolution in header filters

cmd/webhook/admission/admission.go
To help debug ValidatingWebhookConfiguration, logging requests to the
webhook. Note that this will only be requests from the API server since
the webhook is not accessible otherwise.
Signed-off-by: Muaaz Saleem <muhammad.muaaz.saleem@zalando.de>
=> Logging requests to webhook during debug logging

docs/kubernetes/deploy/daemonset/daemonset.yaml, docs/kubernetes/deploy/daemonset/rbac.yaml, docs/kubernetes/deploy/demo/deployment.yaml
Missing selector on k8s demo (deployment.yaml) causes following error;
`error: error validating "docs/kubernetes/deploy/demo/deployment.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false`
fixed.
Signed-off-by: Fatih Boy <fatih@enterprisecoding.com>
=> fixed: missing selector on k8s demo

filters/auth/authclient.go
bind main request context to tokeninfo requests so that the tokeninfo opentracing spans would be connected to the main request span
=> use main request context for tracing tokeninfo requests

tracing/tracers/lightstep/lightstep.go, tracing/tracers/lightstep/lightstep_test.go
this can be used to talk to lightstep satellites without TLS (e.g. an in-cluster
service).
Signed-off-by: Hanno Hecker <hanno@zalando.de>
=> add plaintext=bool parameter to lightstep tracer

readme.md
=> share temp invite link because the old invite does not work anymore

proxy/proxy.go
degrade log level to debug because lookuper is called in the hot path and provide not much value at runtime, because it is likely dependent on user configuration
=> log: degrade level to debug in case no lookuper

docs/reference/filters.md
* Adds inline content with status example
* Adds note on automatic json content type detection (https://github.com/golang/go/issues/10630)
* Explains why it must be the last in the chain
Improves on #1202 and #1451
=> Updates `inlineContent` filter documentation

proxy/proxy.go, routing/matcher.go
Currently the matching logic normalizes paths, but these transformation are not applied when proxied upstream. So /malicious/../nice will pass because the matcher sees /nice but upstream will see /malicious/../nice instead!
=> Normalizes URLs for upstream

logging/access_test.go, logging/log.go, logging/log_test.go, skipper.go
Expose Logrus JSON formatter in `skipper.Options` so the defaults can be overwritten.
Issue: [feature request 1535](https://github.com/zalando/skipper/issues/1535)
=> Pass the logrus JSONFormatter along so options can be changed

docs/kubernetes/routegroup-crd.md
* `hosts` field was made manadatory by #1490
* `routes` field is mandatory according to `routegroups_crd.yaml`
=> Documents `hosts` route group field as mandatory

proxy/proxy.go, proxy/proxy_test.go
`Content-Length` header disables `Transfer-Encoding: chunked` and allows
client to fail earlier in case ServeHTTP hangs for some reason.
Consider malformed server that hangs:
```go
package main
import (
"fmt"
"log"
"net/http"
"time"
)
func main() {
http.HandleFunc("/error", func(w http.ResponseWriter, r *http.Request) {
code := http.StatusBadGateway
text := http.StatusText(code)
if r.URL.Query().Get("cl") != "" {
w.Header().Set("Content-Length", fmt.Sprintf("%d", 1+len(text)))
}
http.Error(w, text, code)
f := w.(http.Flusher)
f.Flush()
time.Sleep(10 * time.Hour)
})
fmt.Printf("Starting server at port 8080\n")
if err := http.ListenAndServe(":8080", nil); err != nil {
log.Fatal(err)
}
}
```
and
```
$ go run error.go 
Starting server at port 8080
```
so
```
$ curl -v "localhost:8080/error"
* …
```
=> Adds Content-Length header for error response

proxy/context.go, proxy/proxy.go
fix https://github.com/zalando/skipper/issues/1564
hijacked connections panic if we flush on so mark via statebag that we are upgraded and if not we flush
=> fix upgrade connections create panic logs on connection tear down

eskipfile/watch_test.go, logging/loggingtest/logger.go
* Ensures `loggingtest.Logger` always writes to clear return channel (otherwise `Reset` will wait forever)
* Fixes race condition in `createFileWith` between `Create` (truncate) and `WriteString`
* Uses `Fatal` to fail fast
Reproduced/verified with:
```
while true; do go test -race -test.short -count=10 -timeout=10s github.com/zalando/skipper/eskipfile; done
```
Fixes #612
=> Fixes `watch_test` race conditions

dataclients/kubernetes/deploy/apply/routegroups_crd.yaml, dataclients/kubernetes/lbannotationfilters_test.go, dataclients/kubernetes/routegroup-proposal.md, docs/kubernetes/routegroup-crd.md, docs/kubernetes/routegroups.md, docs/reference/backends.md, loadbalancer/algorithm.go, loadbalancer/algorithm_test.go, loadbalancer/concurrency_test.go, loadbalancer/doc.go, packaging/helm/skipper-aws/crds/routegroups.yaml, proxy/proxy.go, routing/routing.go
This pull request is rewritten version of https://github.com/zalando/skipper/pull/1507. 
I tested in locally;
- Run 5 simple Go HTTP Servers(same code, different ports and random sleeps 0-2000 milliseconds)
- Skipper eskip configuration, `hello: * -> <powerOfRandomNChoices, "http://localhost:8001", "http://localhost:8002", "http://localhost:8003", "http://localhost:8004", "http://localhost:8005">;`
- Python script sending 2000 request with asyncio.
it distributes traffic better than round robin. However, this is just a first phase trial, it is better to test algorithm in real time traffic or suggested any other method does not come to my mind.
=> Introduce powerofnchoices algorithm in Load Balancer

docs/reference/filters.md
Currently, there are no mentions in the documentation about `copyRequestHeader` & `copyResponseHeader` filters, which makes an impression that such functionality is not implemented.
=> Add documentation for copyRequestHeader & copyResponseHeader filters

filters/diag/diag.go, filters/diag/diag_test.go
* Uses `Context.Serve` and `io.LimitReader` to use constant memory regardless of generated length
* Uses local `rand.Rand` to avoid global rand contention and locking per character generated
=> Improves randomContent filter performance

proxy/proxy.go
this is removing the `streamBody.byte:` logs which make up the biggest chunk of logs per proxy span.
Errors are still logged with the `streamBody.byte:` log.
=> drop excessive span logs

filters/builtin/builtin.go, filters/ratelimit/ratelimit.go, filters/ratelimit/ratelimit_test.go, proxy/proxy.go, ratelimit/ratelimit.go, skipper.go
At present per-route ratelimit filters do not perform actual ratelimiting but rather
store a configuration marker in request context. Ratelimits are
considered by proxy after request path of filter chain is executed but
before backend request.
For example in `clientRatelimit(3, "1m") -> oauthTokeninfoAnyScope("s1")` route
`oauthTokeninfoAnyScope` filter will request tokeninfo even if ratelimit is reached.
This change:
* refactors ratelimit filters to actually consult ratelimits and
shunt request path of filter chain with `429 Too Many Requests` if limit
is reached
* removes per-route ratelimit handling from proxy
Part of #1238
=> Refactors per-route ratelimit handling

logging/access.go, logging/access_test.go
`X-Forwarded-For` may contain a comma-separated list of IP addresses
without ports. Stripping port will truncate list if one address contains port, e.g.:
```
X-Forwarded-For: 8.8.8.8:80, 4.4.4.4
```
will be logged as
```
8.8.8.8 - - [19/Oct/2020:21:27:02 +0200] "GET / HTTP/1.1" 404 10 "-" "curl/7.58.0" 0 localhost:9090 - -
```
=> Logs X-Forwarded-For header without modification in access log

filters/builtin/header_test.go, filters/builtin/headerfilter.go
=> Support lowercase parameters in copyRequestHeader and copyResponseHeader filters

docs/reference/filters.md, filters/auth/oidc.go, filters/auth/oidc_test.go
On OIDC auth filters, Auth Code Options will be able to be dynamically set by a query parameter.
Enhancement Request Issue #1501
=> Make authCodeOptions dynamic on OIDC auth filters

dataclients/kubernetes/kube.go, dataclients/kubernetes/kube_test.go, dataclients/kubernetes/update_test.go
This code was for measuring a zalando internal SLO, which we do differently now. We mark the option as deprecated, log message and ignore the option
=> kubernetes dataclient - mark OriginMarker as deprecated

dataclients/kubernetes/httpsredirect_test.go
```
% nilness ./...
/home/sszuecs/go/src/github.com/zalando/skipper/dataclients/kubernetes/httpsredirect_test.go:94:9: impossible condition: nil != nil
zsh: exit 3     nilness ./...
```
=> condition already checked before

proxy/clienttimeout_test.go, proxy/proxy.go
When client abruptly closes request the context gets `context canceled` error but the roundtrip
may end up with either `unexpected EOF` or the same `context canceled` error nondeterministically.
This change checks request context error before checking roundtrip error.
See https://github.com/zalando/skipper/issues/1631#issuecomment-739110280
Fixes #1631
=> Checks request context error before roundtrip error

net/httpclient.go
feature: support HTTP_PROXY, HTTPS_PROXY and NO_PROXY in net.Client that is used in authclient for example
=> support HTTP_PROXY, HTTPS_PROXY and NO_PROXY in http clients

proxy/proxy.go
Supersedes https://github.com/zalando/skipper/pull/1568
=> Uses io.CopyBuffer for response streaming

docs/reference/filters.md, filters/builtin/builtin.go, filters/diag/diag.go, filters/diag/diag_test.go
`repeatContent` filter generates response of specified size from repeated text
=> Adds repeatContent filter

filters/apiusagemonitoring/filter.go, filters/log/log.go, jwt/token.go, jwt/token_test.go, predicates/auth/jwt.go
Introduces non-validating JWT parser and refactors three call sites to use it 
=> Introduces JWT token parser

dataclients/kubernetes/kube.go
This change suppresses logging of the Skipper health check path in normal conditions, reducing log noise.
The logging is enabled if the health check fails or debugging levels are enabled
=> suppress health check noise

docs/reference/filters.md, eskip/template.go, eskip/template_test.go
Adds support for the following placeholders:
* request header
* request url query
* request cookie
* response header
See #1444
=> Extends templating with request/response placeholders

docs/reference/filters.md, filters/builtin/builtin.go, filters/builtin/timeout.go, filters/builtin/timeout_test.go, filters/filters.go, proxy/backendtimeout_test.go, proxy/clienttimeout_test.go, proxy/context.go, proxy/proxy.go
* Adds `backendTimeout` filter to configure route backend timeout
* Proxy sets up request context with configured timeout and responds
with 504 status on timeout (note: if response streaming has already
started it will be terminated, client will receive backend status and
truncated response body).
See #1041
=> Implements route backend timeout

metrics/codehale_test.go
Failure was reproduced via
```
go test -race -short -count=100 -run TestCodaHaleProxyMetrics github.com/zalando/skipper/metrics
```
* Removes wait procedure in favor of simple sleep as the rest of the tests use sleep anyway
=> Fixes flaky metrics test

docs/reference/filters.md, filters/tracing/tag.go, filters/tracing/tag_test.go
Fixes #704
See also https://github.com/zalando/skipper/issues/1516#issuecomment-748941875
=> Enhances `tracingTag` filter to support template placeholders

Makefile, _test_plugins/multitype_noop.go
* Fixes `_test_plugins` type redeclation (`gosec` treats `_test_plugins` as a package)
* Excludes `G402` `gosec` check due to https://github.com/securego/gosec/issues/551 and https://github.com/securego/gosec/issues/528
=> Fixes gosec errors

docs/reference/filters.md, docs/tutorials/auth.md, skipper.go
Using shared secret reader is not safe in multitenant setup where users
can define their own routes and thus can access grant secret via `bearerinjector` filter.
=> Uses separate secret reader for grant filters

proxy/ratelimit_test.go
Fixes three tests with the following structure:
```
0. setup ratelimit: N requests/time window
1. do N requests and expect 200 OK
2. do N requests and expect 429 Too Many Requests
3. sleep for time window
4. do N requests and expect 200 OK
```
Such test passes only if steps 1 and 2 are complete within time window.
If requests are slow (e.g. CI pipeline) then time window may pass before
steps are complete, limit expires and expectaions fail on step 2
(`expected 429, got 200`).
This change reduces N thus allowing lower request rate.
Followup on #1671
=> Fixes flaky ratelimit tests

ratelimit/redis.go
Removes ring availability check from ratelimiter constructor
in order not to block requests when ring is not available.
Fixes #1690
=> Removes Redis ring availability check

proxy/breaker_test.go
If test requests are slow (e.g. CI pipeline) circuit breaker can go
from open to half-open and closed states and open state check step will fail.
This change increases test circuit breaker timeout.
=> Fixes flaky breaker tests

proxy/upgrade.go, proxy/upgrade_test.go
Proxy copies data via `io.Copy` between upgraded request and backend connections in
two goroutines and waits for both copy calls to complete:
```
wait {
copy backend to request // 1
copy request to backend // 2
}
```
When backend connection is closed, first copy call completes
but the second is still blocked on read from request connection until
it is closed (i.e. client disconnects).
This change waits for either copy to complete and closes both request and
backend connections and thus unblocks the second copy.
Fixes #1669
=> Closes upgraded connection on copy completion

docs/tutorials/auth.md
After the oauth grant flow related filters where merged I realised that I could clean up our routes file and remove a manually added `grantCallback` route since it gets automatically added by Skipper. I then realised that this automatically added route does not apply the default filters. I think that is it relatively rare that users would want to apply default filters here but it should still be pointed out in the documentation.
=> Document default filters with regards to grantCallback route

docs/reference/filters.md, eskip/template.go, eskip/template_test.go
Adds three new template placeholders that resolve into request IP address similar to existing `Source`, `SourceFromLast` and `ClientIP` predicates.
* could be handy to support default key in "Configurable consistent hash request key" (#1711)
* allows client rate limit based on last value of `X-Forwarded-For` (`XForwardedForLookuper` supports only first value)
* named after existing predicates to avoid confusion (could be extended if/when "Configurable ClientIP utility function" (#1620) is implemented)
=> Adds request IP address template placeholders

ratelimit/redis.go
=> If redis is in all logs we can more easily grep for them

tracing/tracers/lightstep/README.md, tracing/tracers/lightstep/lightstep.go, tracing/tracers/lightstep/lightstep_test.go
add protocol arg to be used to switch of GRPC, a string arg was introduced instead of bool, because protocol might change in the future
=> add protocol arg to be used to switch of GRPC

proxy/fastcgi/fastcgi.go, proxy/proxy.go, proxy/proxy_test.go
The issue this PR tries to fix is the case where we want to forward the lookup path the the fastcgi backend to serve different files and not only index.php.
Last commit adds the return code 404 when file is not existing on backend :
```
::1 - - [03/Feb/2021:12:19:35 +0100] "HEAD /test5.php?name=foo HTTP/1.1" 404 10 "-" "curl/7.63.0" 8 localhost - -
::1 - - [03/Feb/2021:12:19:50 +0100] "GET /test2.php?name=foo HTTP/1.1" 200 28 "-" "curl/7.63.0" 7 localhost - -
```
Tested locally with docker-compose
=> Use file path on url to forward fastcgi requests

proxy/context.go, proxy/proxy.go, proxy/tracing_test.go
Try to always set `http.status_code` on the initial span too and not just on the `proxy` span to allow querying the main span by `http.status_code` regardless if the status code is coming from the downstream or by skipper itself (eg. not found route, filters serving the response).
~Should fix also #1145~
=> Always add http status code to initial span

filters/scheduler/lifo.go
to avoid flooding the logs when lifo filter overruns
=> Uses debug log level for lifo error logs

docs/reference/filters.md
`oauth2-access-token-header-name` is needed by the `oauthGrant` filter to pass the bearer token in the request headers. The documented default value did not work.
=> Update oauthGrant authorization header flag docs

tracing/tracers/lightstep/lightstep.go, tracing/tracers/lightstep/lightstep_test.go
feature: limit logs per span, log key size, log value size
test: 100% parse coverage, 2 funcs left
=> feature: limit logs per span, log key size, log value size

docs/reference/backends.md, docs/reference/filters.md, filters/builtin/builtin.go, filters/consistenthash/key.go, filters/consistenthash/key_test.go, loadbalancer/algorithm.go, loadbalancer/algorithm_test.go, proxy/proxy.go, routing/routing.go
`consistentHashKey` filter configures request key used by `consistentHash` load balancing algorithm to select backend endpoint.
Fixes #1711
=> Adds consistentHashKey filter

docs/reference/scripts.md, script/script.go, script/script_test.go
Sleep function may be useful for prototyping but unfortunately Lua's
standard library does not provide it, see http://lua-users.org/wiki/SleepFunction
=> Adds lua sleep function

docs/reference/filters.md, filters/ratelimit/ratelimit.go, filters/ratelimit/ratelimit_test.go
Add the possibility to provide the status code as an argument for `ratelimit` and `clusterRatelimit` filters.
The value will be used as response status code for a rate limited request, default value if not provided is the standard `429`.
close #1728
=> feat: add status code as arg to ratelimit and clusterRatelimit filters

proxy/proxy.go, proxy/tracing_test.go
removing URL tag in ingress span can save a lot of bytes for example with elastic search cases
Interesting observation: proxy span has no kv pairs from query, that's why I let it there.
=> remove URL tag in ingress span

docs/kubernetes/ingress-usage.md, docs/kubernetes/routegroup-crd.md, docs/kubernetes/routegroups.md, docs/operation/operation.md, docs/reference/filters.md, docs/tutorials/auth.md, docs/tutorials/development.md, docs/tutorials/operations.md, docs/tutorials/ratelimit.md
Fixes documentation links such that documentation is navigable both on github and via `mkdocs serve`.
Found broken links by crawling the branch tree and inspecting logs for 404 errors:
```
$ rev=fixes-doc-links; wget --recursive --convert-links --domains github.com -I /zalando/skipper/blob/$rev/ -I /zalando/skipper/tree/$rev/ https://github.com/zalando/skipper/tree/$rev/docs/ 2> github.log
$ wget --recursive --convert-links --domains 127.0.0.1 http://127.0.0.1:8000/ 2> localhost.log
```
Followup on #1740
See also #955 
=> Fixes documentation links

go.mod, go.sum
fix: apply https://github.com/lightstep/lightstep-tracer-go/pull/277 to fix span drop issues https://github.com/lightstep/lightstep-tracer-go/issues/275 and likely latency issues caused by create objects and GC https://github.com/lightstep/lightstep-tracer-go/issues/273
=> fix lightstep tracer span drop issues

.github/workflows/codeql-analysis.yml
fix codeql annotation warning
1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
=> fix codeql annotation warning

docs/reference/filters.md, filters/filters.go, filters/ratelimit/backendratelimit.go, filters/ratelimit/backendratelimit_test.go, net/redisclient_test.go, net/redistest/redistest.go, proxy/backendratelimit_test.go, proxy/proxy.go, ratelimit/cluster_test.go, ratelimit/redis_test.go, skipper.go
The filter limits request rate per backend host, it is similar to `clusterClientRatelimit`
but instead of client IP it uses backend endpoint address to group requests.
=> Adds backendRatelimit filter

dataclients/routestring/example_test.go
```
$ go test -count=1 github.com/zalando/skipper/dataclients/routestring
fatal error: newproc: function arguments too large for new goroutine
...
```
=> Fixes `function arguments too large for new goroutine` error

dataclients/kubernetes/routegroup.go, dataclients/kubernetes/testdata/routegroups/convert/missing-service-endpoints-and-cluster-ip.eskip, dataclients/kubernetes/testdata/routegroups/convert/missing-service-endpoints-and-cluster-ip.log, dataclients/kubernetes/testdata/routegroups/convert/target-endpoints-not-found.log
It may happen that deployment is scaled down to zero e.g. by stackset
controller or kube downscaler which leads to an empty endpoint list.
Each Skipper instance then logs info message about target endpoints not
found on every kubernetes poll cycle (default `-source-poll-timeout` is 3s)
and thus pollutes logs.
Logging seems redundant since the shunt route is created anyway.
Fixes #1773
=> Uses debug level when target endpoints are not found

docs/reference/predicates.md, predicates/forwarded/forwarded.go, predicates/forwarded/forwarded_test.go
Two predicates have been added:
* `ForwardedHeader`
* `ForwardedProtocol`.
They follow https://datatracker.ietf.org/doc/html/rfc7239
=> Predicates for Forwarded Header

docs/reference/filters.md
The headings are all converted to lowercase when they are turned into anchors so we also need to use lowercase when referencing them as internal skip links.
Signed-off-by: Knut Hühne <knut.huehne.external@zalando.de>
=> Fix anchor link capitalisation in documentation

docs/kubernetes/ingress-usage.md, docs/operation/operation.md, docs/reference/predicates.md, docs/reference/scripts.md, docs/tutorials/auth.md
Anchors with uppercase letters found via
```
find docs/ -name '*.md' -exec grep -HEo '\(.*#[a-z]*[A-Z].*\)' {} \; | grep -v http
```
Followup on #1790
=> Makes documentation anchors lowercase

routing/datasource.go
Fixed the typo in logging between route update and initial route fetch, to allow matching both with "error while receiving" in log search.
=> Fix typo in logging

filters/filters.go
Filter implementations should use `FilterContext.Request()` to modify
backend request and `FilterContext.Response()` to modify backend response.
`FilterContext.StateBag()` could be used to transfer state between request and response filter chain phases.
`FilterContext.Serve()` could be used to serve response from the request filter chain phase.
=> Deprecates `FilterContext.ResponseWriter()`

eskipfile/watch_test.go
On my linux laptop, there is a root partition and a home partition. os.Rename gives errors when trying to move a file across partitions, in this case from the root partition(/tmp) to the home partition (where my cloned repo is). The fix being applied is to use os.Create on the file, since it will truncate the file if it already exists.
Errors:
```
--- FAIL: TestWatchInitialRecovers (0.09s)
/home/fmoloney/zalando/go-code/github.com/zalando/skipper/eskipfile/watch_test.go:61: rename /tmp/watch_test-048887076 fixtures/watch-test.eskip: invalid cross-device link
--- FAIL: TestWatchUpdateFails (0.00s)
/home/fmoloney/zalando/go-code/github.com/zalando/skipper/eskipfile/watch_test.go:61: rename /tmp/watch_test-532227635 fixtures/watch-test.eskip: invalid cross-device link
--- FAIL: …
```
=> Fix test file creation when /tmp is on a different partition

loadbalancer/algorithm_test.go
Algorithm test performs `R` requests towards `N` backend
endpoints, counts requests per endpoint and verifies that expected
number of endpoints received at least one request.
For `random` and `powerOfRandomNChoices` algorithms it may happen
(by a bad luck) that some backend does not receive any requests which
fails the test.
The issue could be reproduced by
```
while go test -count=1 github.com/zalando/skipper/loadbalancer -run TestApply; do true; done
```
or by decresing `R`.
This change increases `R` from `100` to `1000` to reduce failure
chances.
=> Increases number of algorithm test iterations

net/redisclient.go
fix avalanche effect of the underlying hash, similar to https://github.com/zalando/skipper/pull/1808
=> fix/jump-hash-redisclient: fix avalanche effect of the underlying hash

proxy/breaker_with_teeloopback_test.go, proxy/proxy.go
fix https://github.com/zalando/skipper/issues/1816
in case of an open breaker and route has a teeLoopback filter like `breaker -> teeLoopback()`, we did not consume the body such that the cloned request spawned in a goroutine never finished
=> fix possible goroutine leak on breakers in case used in conjuction with teeLoopback filter

proxy/proxy_test.go
The test uses `Tee` predicate 
https://github.com/zalando/skipper/blob/33cf1d1dd14039305dc53bc8f9b81d9b30b8cff5/proxy/breaker_with_teeloopback_test.go#L22
that is not registered by the test proxy constructor method `newTestProxyWithFiltersAndParams` which leads to the request loop.
To make the problem apparent testlogger needs to be unmuted:
```
2021/08/10 10:38:46 failed to process route (shadow): predicate not found: 'Tee'
2021/08/10 10:38:46 context: failed to execute loopback request: max loopbacks reached
```
Followup on #1816 and #1819
=> Fixes TestBreakerLeak test

dataclients/kubernetes/routegroup.go, dataclients/kubernetes/testdata/routegroups/east-west-range/internal-hosts-explicit-route.eskip, dataclients/kubernetes/testdata/routegroups/east-west-range/internal-hosts-explicit-route.kube, dataclients/kubernetes/testdata/routegroups/east-west-range/internal-hosts-explicit-route.yaml
In #1676 a new loop for the internal hosts were introduced by a first
implementation and not removed. The initial implementation assumed that
multiple domains with different CIDRs could be configured, therefore,
required different route for every host. The implementation changed
during the PR discussion and with the current one multiple domains can
be set but the predicates are all added to the routes without
distinction of domain and the loop is unnecessary. Check [this
comment][0] for more details.
This commit removes the unnecessary loop and create the routes combining
all internal hosts.
[0]: https://github.com/zalando/skipper/pull/1676#discussion_r614897845
=> Remove unnecessary loop on k8s internal hosts

go.mod, go.sum
Fixes build failure on go 1.17 caused by https://github.com/cespare/xxhash/issues/54
=> Updates xxhash dependency version

.github/workflows/master.yaml, .github/workflows/pr.yaml
Also adds a link to semver documentation to clarify that version is not a prefix regexp.
The value `^1.15` is a so called ["caret" range](https://www.npmjs.com/package/semver#caret-ranges-123-025-004)
that matches 1.15 and any minor version above, e.g. 1.16 which could be
seen in the action logs:
```
Setup go stable version spec ^1.15
Found in cache @ /opt/hostedtoolcache/go/1.16.7/x64
Added go to the path
Successfully setup go version ^1.15
go version go1.16.7 linux/amd64
```
See also https://github.com/actions/setup-go/issues/101#issuecomment-814127065
=> Updates go version in workflows

docs/kubernetes/ingress-usage.md
=> Adds ingress path ratelimit example

filters/scheduler/lifo.go, scheduler/scheduler.go
After the release of #1725, it is sometimes hard to correlate HTTP status codes the action of a lifo filter.
This change increases one of two counters each time a lifo queue is either full or an entry times out. It improves the visibility of the actions a lifo filter has taken without spamming the logs.
=> Record metric if a lifo filter drops a request

config/config.go, config/config_test.go, docs/operation/operation.md, filters/xforward/xforward.go, net/headers.go, net/headers_test.go, net/net.go, net/net_test.go, predicates/source/source.go
Adds two new flags to control addition of `X-Forwarded-*` headers.
The addition happens before request routing so e.g. `SourceFromLast` predicate can rely on the header value.
=> Adds forwarded headers flags

dataclients/routestring/example_test.go, etcd/etcdtime_test.go, plugins_test.go, proxy/backendratelimit_test.go, proxy/breaker_test.go, ratelimit/cluster_test.go, ratelimit/swim_test.go, skptesting/gohttpclient.go, skptesting/prof.go
Golang 1.17 adds new syntax for build constraints, `gofmt` adds new
`//go:build` lines along with `// +build` during transition phase.
```
docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.17.0 sh -c "make fmt"
```
See https://tip.golang.org/doc/go1.17#gofmt
Note: the builds started to fail because we ask for golang version >= 1.6 (see https://github.com/zalando/skipper/pull/1835) and workflow started to build using 1.17
=> Adds golang1.17 build constraints

docs/reference/predicates.md, predicates/forwarded/forwarded.go, predicates/forwarded/forwarded_test.go
Caught corner case when multiple entries appear in the forwarded host predicate [see docs](https://www.rfc-editor.org/rfc/rfc7239#section-4)
> If the request is passing through several proxies, each proxy can add a set of parameters; it can also remove previously added "Forwarded" header fields.
> A proxy server that wants to add a new "Forwarded" header field value can either append it to the last existing "Forwarded" header field after a comma separator or add a new field at the end of the header block.  A proxy MAY remove all "Forwarded" header fields from a request.  It MUST, however, ensure that the correct header field is updated in case of multiple "Forwarded" header fields.
=> Fix forwarded host when multiple entries

go.mod, go.sum
Older version of indirect golang.org/x/sys caused SIGSEGV on Go 1.17 on MacOS Big Sur
See https://github.com/sirupsen/logrus/issues/1275
Fixes #1836
=> Updates logrus dependency

eskip/example_test.go
The https://github.com/zalando/skipper/issues/1860 pointed out a bug
https://github.com/golang/go/issues/48362 that leads to the false
positive testable example caused by a trailing comment.
Moreover https://github.com/zalando/skipper/pull/918 changed the test
input without changing the output and that went unnoticed due to this bug.
This change removes trailing comment to fix the example.
It also removes the test input instead of adding a correct output because
the input syntax is incorrect therefore misleading.
Fixes #1860
=> Fixes testable example

config/config.go, routesrv/options.go, routesrv/routesrv.go, skipper.go
feature: wire all kubernetes dataclients features that are available, also deprecated one because these might be in use
=> feature: wire all kubernetes dataclients features

config/config.go, config/config_test.go, filters/ratelimit/ratelimit.go, filters/ratelimit/ratelimit_test.go, proxy/proxy.go, ratelimit/ratelimit.go, ratelimit/ratelimit_test.go, skipper.go
`clusterRatelimit` uses single ratelimit key for all requests and therefore uses
single Redis shard to track hits.
To spread the load across multiple Redis shards this change introduces key sharding.
Based on the max allowed hits and max allowed key shards the number of key shards `K`
is the largest number from `[1, maxKeyShards]` interval such that `maxHits % K == 0`.
When number of key shards `K` is greater than one `clusterRatelimit` will use one of
`K` distinct ratelimit keys for the requests selected by round robin algorithm and
will allow up to `maxHits / K` hits per sharded key.
=> Adds key sharding to `clusterRatelimit`

filters/apiusagemonitoring/spec.go
Signed-off-by: tkrop <tronje.krop@zalando.de>
Downgrades the level of some log messages to warning, since they are not really errors but only hints about an potentially unexpected filter behavior.
=> feat: downgrade level of log message

docs/reference/predicates.md, predicates/predicates.go, predicates/primitive/shutdown.go, predicates/primitive/shutdown_test.go, skipper.go
`Shutdown` predicate evaluates to true if Skipper is shutting down after receiving
`SIGTERM` signal and can be used to implement customized healthcheck.
Updates #1899
=> Adds `Shutdown` predicate
